fix: throw error if mainjs is not present
storybookjs/storybook pull request #10097
Opened 2020-03-10 15:33 UTC by yannbf

Issue: There's no issue specifically, but it's to avoid having more issues like #9854 

## What I did
This PR throws an error if the user does not have presets.js or main.js in their project. 
It could happen either if the file is really not there or if the file is being used in an unsupported extension. 
This could help users migrate by giving them a direction when upgrading storybook.

## How to test
- Does this need an update to the documentation?
Yes. I'm pointing to 6.0 docs in the log, so the docs from next need to be merged to master.

2020-03-11 02:03 UTC, shilman approved these changes
LGTM! Great fix!

2020-03-11 02:04 UTC, shilman requested changes
What if the user is still using `config.js`?

2020-03-11 14:09 UTC, yannbf commented
> What if the user is still using `config.js`?

You are right. The intention would be to make people move away to the new configuration setup but it's better to warn with a deprecated message instead. Changes on the way!

2020-04-05 08:41 UTC, yannbf commented
Oops! sorry for inactivity, corona side effects 😓 Work will be done soon, just need to get some feedback from @shilman  👍

2020-04-06 13:15 UTC, yannbf commented
Hey @shilman changes are added! Please check if they all make sense to you.
ps: this PR will have a really small conflict with  #10288

2020-04-06 13:15 UTC, yannbf commented on lib/core/src/server/utils/interpret-files.js
> +export const boost = new Set(['.js', '.jsx', '.ts', '.tsx']);
This is where the conflict with #10288 will happen

2020-04-07 00:35 UTC, shilman requested changes
Can you update `exists` to handle the extensions code, i.e. `exists('main')`? will make the code a lot cleaner.

Also the other PR has been merged, so you can resolve the conflicts while you're at it! 😘

2020-04-07 07:59 UTC, yannbf commented
> Can you update `exists` to handle the extensions code, i.e. `exists('main')`? will make the code a lot cleaner.
Thanks for you review! Done!

> Also the other PR has been merged, so you can resolve the conflicts while you're at it! 😘
Also done!

2020-04-07 08:53 UTC, shilman approved these changes
Looking great!! 😍

2020-04-07 09:43 UTC, ndelangen approved these changes

2020-04-07 09:43 UTC, merged