Add/extract command to cli
storybookjs/storybook pull request #10146
Opened 2020-03-18 10:14 UTC by ndelangen

Storybook Composition needs a static extracted data object of the storybook stories for best performance.

I added a command the the CLI to generate such file.

`stories.json` will contain something like:

```json
{
  "stories": {
    "story-id": {
      "name": "story name",
      "kind": "story kind"
    }
  }
}
```

2020-03-20 05:13 UTC, tmeasday commented
Let's discuss this -- I don't think we can add `puppeteer` as a dependency of the CLI. We should probably make this a separate CLI package that folks can optionally install if they want to publish their SB for composition.

2020-03-21 03:03 UTC, shilman requested changes
I agree with @tmeasday that the `puppeteer` dependency makes this more suitable to a separate package. It's an awesome feature tho!!

2020-03-23 08:43 UTC, ndelangen commented
OK, I'll extract this into it's own package

2020-03-25 10:38 UTC, shilman commented on lib/cli/src/extract.js
> +            parameters: {
we might need to revisit this filtering of parameters in the future, but ok for now

2020-03-25 10:39 UTC, shilman approved these changes
AWESOME! The lazy loading is a sweet touch 😘

2020-03-25 10:41 UTC, merged