Deprecate built-in addons
storybookjs/storybook pull request #1025
Opened 2017-05-12 14:02 UTC by shilman

Issue: #1117

## What I did

Use `action` and `linkTo` addons just like any other storybook addon.
Update examples, docs, and add deprecation warning to code.

## How to test
First run:
```
npm run bootstrap
cd examples/cra-storybook
npm run storybook
```
Open browser console, and there should be no deprecation warnings.
Then, update the stories to use:

```js
import { storiesOf, action, linkTo from } from '@kadira/storybook'
```
Deprecation warnings should appear in the browser console.

2017-05-12 15:45 UTC, ndelangen requested changes

2017-05-12 15:45 UTC, ndelangen commented on packages/addon-info/.storybook/addons.js
> +import '@kadira/storybook-addon-actions/register';
Is this missing addon-links?
Or is this on purpose?

2017-05-12 15:45 UTC, ndelangen commented on packages/react-storybook/src/client/index.js
> +  _action,
This dangling underscore will become an eslint error in the future, can you pick another naming pattern?

2017-05-13 00:14 UTC, shilman commented on packages/react-storybook/src/client/index.js
> +  _action,
fixed!

2017-05-13 00:14 UTC, shilman commented on packages/addon-info/.storybook/addons.js
> +import '@kadira/storybook-addon-actions/register';
on purpose. links are not used in this example.

2017-05-13 08:20 UTC, ndelangen approved these changes

2017-05-13 09:22 UTC, merged