WIP: Add resetStyles prop to addon-docs Preview component
storybookjs/storybook pull request #10274
Opened 2020-03-31 19:59 UTC by tsnolan23

Issue: https://github.com/storybookjs/storybook/issues/10273

## What I did

Added a `resetStyles` prop the `Preview` block of `addon-docs`

## How to test

Create an documentation-only mdx file that contains a `<Preview resetStyles>` block and ensure the styles have been reset for the contents.

- Is this testable with Jest or Chromatic screenshots? : Yes
- Does this need a new example in the kitchen sink apps? : I don't think so
- Does this need an update to the documentation? : Yes

If your answer is yes to any of these, please make sure to include it in your PR.

2020-04-01 00:55 UTC, shilman requested changes
@tsnolan23 Thanks for putting this together! 🎉 

A few small requests:

1) For simplicity can we just make `Preview` reset the styles in all cases?

2) Can you refactor `resetComponents` so that it is defined once in `@storybook/components/html` and shared between `Story` and `Preview`?

3) Can you add an example to `official-storybook` to test?

Thanks!

2020-04-01 01:21 UTC, tsnolan23 commented
Sounds good, @shilman! To clarify your first point, you just want `Preview` to always reset styles? Drop the `resetStyles` prop?

2020-04-01 01:28 UTC, shilman commented
@tsnolan23 Correct. Pretty sure it makes sense to always reset the styles, right?

2020-04-01 01:29 UTC, tsnolan23 commented
Yeah, I agree! Thanks

2020-04-20 19:21 UTC, tsnolan23 commented on lib/components/src/html.tsx
> +Object.keys(rawComponents).forEach((key) => {
I'm not sure if you'd prefer this somewhere else than the root export?

2020-04-20 19:24 UTC, tsnolan23 commented
Sorry for the delay on this. I think I addressed all the feedback!

2020-04-20 21:19 UTC, shilman approved these changes
Thanks @tsnolan23 , this looks great. Merging!

2020-04-20 21:19 UTC, merged

2020-04-20 21:22 UTC, tsnolan23 commented
Fantastic, thanks for all the feedback, appreciate it!