CHANGE folder structure && CHANGE package-names
storybookjs/storybook pull request #1031
Opened 2017-05-14 08:34 UTC by ndelangen

## What I did
I implemented the proposed changes to the folder structure and package names

2017-05-14 11:47 UTC, shilman requested changes
@ndelangen when i try to test it, I get this error:

```
lerna ERR! execute npm ERR! 404 Not found : @storybook/storybook-database-cloud
lerna ERR! execute npm ERR! 404 
lerna ERR! execute npm ERR! 404  '@storybook/storybook-database-cloud' is not in the npm registry.
lerna ERR! execute npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

It is referenced by `addon-comments`. I think we should either migrate `database-*` to the monorepo, revert to `@kadira/database-cloud`, or remove `addon-comments` from the monorepo for now.

2017-05-14 11:49 UTC, shilman commented on addons/actions/README.md
> +import { storiesOf, action } from '@storybook/react'
FYI all of these are going to conflict with the changes I made in https://github.com/storybooks/storybook/issues/1017

2017-05-14 13:42 UTC, UsulPro commented
Thanks, @ndelangen for this rearrangement! 👍 

Some points to discuss:

- rename `decorator-centered` to `addon-centered` since this is also an addon. (We don't have special names for panels, storiesOf extensions).

- move `storyshots` to addons folder. Since we import it additionally we can call it "addon"

- changing `packages` to `lib` looks good to me, but maybe `core` also could fit?

- what is the purpose of the `app` folder? Maybe it should be located in the `examples\` folder?

2017-05-14 17:34 UTC, ndelangen commented
App folder are the what previously were @kadira/storybook and @kadira/storybook-react-native

In the future there may be other UI libraries/frameworks there too.

2017-05-14 22:40 UTC, ndelangen commented on addons/actions/README.md
> +import { storiesOf, action } from '@storybook/react'
Yup I'm correcting for that.

2017-05-15 01:09 UTC, shilman approved these changes

2017-05-15 01:10 UTC, shilman commented
I agree with @UsulPro 's comments above. Otherwise, the changes look good to me. Thanks for all your work on getting this cleaned up!!

2017-05-15 02:45 UTC, tmeasday commented
Do we want to change `storyshots` to `@storybook/storyshots`?

2017-05-15 10:01 UTC, ndelangen commented
I just want to get this finished and merged, so just shout how you want it now, or forever hold your peace 🙊

2017-05-15 10:37 UTC, aaronmcadam approved these changes

2017-05-15 10:58 UTC, ndelangen commented
I will continue work on the other branch!

2017-05-15 10:58 UTC, merged