fix(to-require-context): fixed regex to glob conversion
storybookjs/storybook pull request #10400
Opened 2020-04-13 04:05 UTC by valerybugakov

Issue: described here: https://github.com/storybookjs/storybook/issues/10322

## What I did

Fixed conversion from glob to regex. Added tests for `to-require-context` module.

## How to test

```sh
npx jest lib/core/src/server/preview/to-require-context.test.js
```

2020-04-13 04:14 UTC, valerybugakov commented
`svelte-kitchen-sink` tests are failing in CircleCI. Let me know what should be done to fix them

2020-04-13 22:19 UTC, ndelangen commented
There's something odd happening here:
https://circleci.com/gh/storybookjs/storybook/207662

This glob seems to be broken by this change:
https://github.com/storybookjs/storybook/blob/4a3d16103656a78b9fb377107bb755d2de80a7fb/examples/cra-kitchen-sink/.storybook/main.js#L18

2020-04-13 23:27 UTC, shilman requested changes
See suggestion

2020-04-13 23:27 UTC, shilman commented on lib/core/src/server/preview/to-require-context.test.js
> +    expect(isMatchedForIncorrectPaths).toBe(false);
```
> [false, true].every(x => x)
false
```

I think you want:

```js
const isMatchedForIncorrectPaths = incorrectPaths.every((path) => !regex.test(path));
...
expect(isMatchedForIncorrectPaths).toBe(true);
```
no?

2020-04-14 01:13 UTC, valerybugakov commented on lib/core/src/server/preview/to-require-context.test.js
> +    expect(isMatchedForIncorrectPaths).toBe(false);
right, thanks, that was the intention 👍

2020-04-14 13:13 UTC, valerybugakov commented
This [issue](https://github.com/micromatch/micromatch/issues/110) was [fixed](https://github.com/micromatch/nanomatch/commit/770f54c59b3a4b60a92dd1c2a396018b5596f13a) in `nanomatch`. It works correctly without any replacements using `makeRe` from `nanomatch`.

2020-04-14 17:35 UTC, ndelangen approved these changes

2020-04-14 17:35 UTC, merged