Added events addon
storybookjs/storybook pull request #1071
Opened 2017-05-19 08:50 UTC by z4o4z

Migrated from [@z4o4z/storybook-addon-events](https://github.com/z4o4z/storybook-addon-events).

2017-05-19 17:54 UTC, ndelangen approved these changes

2017-05-19 19:49 UTC, danielduan commented on addons/events/.storybook/components/Logger.js
> +    fontFamily: 'Areal, sans-serif',
Is this a typo for `Arial`? Might want to include `Helvetica` for mac users too.

2017-05-19 20:10 UTC, z4o4z commented on addons/events/.storybook/components/Logger.js
> +    fontFamily: 'Areal, sans-serif',
Yep, ofcourse. I'll fix it!

2017-05-20 06:35 UTC, shilman requested changes
@z4o4z this looks really cool, thanks for the excellent contribution!

do you mind documenting a few use cases for this in the README so it's easier to understand how best to use it?

2017-05-22 07:35 UTC, z4o4z commented on addons/events/.storybook/components/Logger.js
> +    fontFamily: 'Areal, sans-serif',
fixed

2017-05-22 22:18 UTC, ndelangen approved these changes

2017-05-22 22:22 UTC, ndelangen commented
I've invited you to the organisation @z4o4z. I hope you'll accept.

We should merge this some time after 3.0.x release, OK?
Thanks for making this awesome plugin, I think it's definitely going to come in handy for a lot of people, doing more edge-case react work.

2017-05-23 04:16 UTC, z4o4z commented
@ndelangen It is a great honor for me to join your organization. Thanks!

Of course.
> We should merge this some time after 3.0.x release, OK?

2017-05-23 10:25 UTC, ndelangen commented
After this is merged, we'll be maintaining and publishing this package from here, will you deprecate your own repo then?

2017-05-24 05:19 UTC, z4o4z commented
@ndelangen yep, I'll deprecate my own repo and add link to this repo

2017-05-25 21:18 UTC, ndelangen commented
Hey, as we discussed, what I'll do is actually import your repo into this one. That should preserve the history.

I'll close this PR, in favour of a new one, I'll push in a minute 👏

2017-05-25 21:18 UTC, closed without merging