Taimoor/added examples
storybookjs/storybook pull request #11020
Opened 2020-06-02 12:33 UTC by Taimoormk

Issue:

## What I did

I simply removed the example of `reactPakistan` and added four mores at the bottom of the list, as `reactPakistanCommons`, `reactPakistanUI`, `reactPakistanIcons` & `reactPakistanLogos`.

## How to test

Simply route to the examples page and you will see the newly added content there.

- Is this testable with Jest or Chromatic screenshots? - yes
- Does this need a new example in the kitchen sink apps? - no
- Does this need an update to the documentation? - no

If your answer is yes to any of these, please make sure to include it in your PR.

2020-06-04 15:15 UTC, ndelangen requested changes

2020-06-04 15:29 UTC, Taimoormk commented on docs/src/pages/examples/_examples.yml
> +  site: https://www.npmjs.com/package/@react-pakistan/react-logo-collection
@ndelangen Most certainly it makes sense and it's a great suggestion/feature as well. I am keen on to try it out and list that one composed library instead.

Also, perhaps you could point me in the right direction as well, I have 4 storybook libraries for mobile development too built using React Native, currently I am unable to host that library on a web based mobile emulator, do you happen to know any solution for that matter?

2020-06-05 09:23 UTC, ndelangen commented on docs/src/pages/examples/_examples.yml
> +  site: https://www.npmjs.com/package/@react-pakistan/react-logo-collection
I don't really have a good suggestion for react-native right now, sorry. Let me know if you find something?

2020-06-11 03:50 UTC, Taimoormk commented
Hi @ndelangen Yes certainly, I have setup an open source repo for this matter, https://github.com/react-pakistan/react-storybook-composed

Followed the instruction from the doc you shared above, I am able to reach to this point now.
<img width="1919" alt="Screenshot 2020-06-11 at 08 48 22" src="https://user-images.githubusercontent.com/27800340/84343002-71d3d500-abc0-11ea-98db-5567ef3d59da.png">

Already published stories aren't loading up as shown, care to have a look at this file please, https://github.com/react-pakistan/react-storybook-composed/blob/dev/.storybook/main.js

2020-06-11 03:51 UTC, Taimoormk commented on docs/src/pages/examples/_examples.yml
> +  site: https://www.npmjs.com/package/@react-pakistan/react-logo-collection
No worries, and yes sure I am passively looking for that solution, will update you and this thread, once I happen to find one.

2020-06-11 09:31 UTC, ndelangen commented
`url: 'https://taimoormk.github.io/react-logo-collection/?path=/story/logos--bitcoincolorlogos',` isn't a valid ref url, it should be `https://taimoormk.github.io/react-logo-collection`.

For larger storybooks like this you'll want to create a `stories.json` that's hosted alongside the deployed storybook.

you can use `yarn sb extract` to generate this file.

You'll want to do this for every referenced storybook. This should make the loading of refs nearly instant.

2020-06-18 09:56 UTC, Taimoormk commented
> `url: 'https://taimoormk.github.io/react-logo-collection/?path=/story/logos--bitcoincolorlogos',` isn't a valid ref url, it should be `https://taimoormk.github.io/react-logo-collection`.
> 
> For larger storybooks like this you'll want to create a `stories.json` that's hosted alongside the deployed storybook.
> 
> you can use `yarn sb extract` to generate this file.
> 
> You'll want to do this for every referenced storybook. This should make the loading of refs nearly instant.

I was trying to run `npx sb extract` but seems like `extract command is not supported by the cli yet, as shown in the screenshot below;

![Screenshot 2020-06-18 at 14 55 19](https://user-images.githubusercontent.com/27800340/85006707-e801aa00-b173-11ea-9e93-ded0c0c910c3.png)

2020-06-22 09:10 UTC, ndelangen commented
@Taimoormk our script checks if puppeteer is already installed/working on your system, if not tries to install it.

It seems installing fails on your machine because of permission issues.

2020-08-19 10:13 UTC, ndelangen commented
We removed the visual examples from the website if you'd like you can add examples here:
https://github.com/storybookjs/storybook/blob/next/docs/get-started/examples.md

2020-08-19 10:13 UTC, closed without merging