Make app/react/package.json private to not leak dependencies
storybookjs/storybook pull request #1128
Opened 2017-05-25 14:16 UTC by lifeiscontent

Issue: Previously the dependencies of the react app were leaking into my project

## What I did

set the app/react/package.json to private

## How to test

in an app that uses storybook run `yarn install` and no longer see the warning below

```
@kadira/storybook > babel-preset-react-app > babel-preset-latest@6.16.0: 💥  preset-latest accomplishes the same task as babel-preset-env. 🙏  Please install it with 'npm install babel-preset-env --save-dev'. '{ "presets": ["latest"] }' to '{ "presets": ["env"] }'. For more info, please check the docs: http://babeljs.io/docs/plugins/preset-env 👌. And let us know how you're liking Babel at @babeljs on 🐦
```

2017-05-25 14:48 UTC, ndelangen commented
Hey can you direct me to the location where this behavior is described as intended?
AFAIK this property is intended to mark a package as non-public.

2017-05-25 16:27 UTC, lifeiscontent commented
@ndelangen when you do `yarn` in a project that uses storybook you get an error as I've pasted above.

2017-05-25 19:08 UTC, lifeiscontent commented
@ndelangen this is also causing compilation errors in create-react-app 1.0 due to the leaked dependencies

2017-05-26 01:57 UTC, lifeiscontent commented
@ndelangen I figured out why storybook is breaking create react app, the reason has to do with the dependencies. all babel dependencies should be marked as dev dependencies.

2017-05-26 02:28 UTC, lifeiscontent commented
@ndelangen I've updated what I can, but if you know how to test your dependencies within your app I think you should take it further as I'm unsure how to test much future due to me not being familiar with the project structure.

2017-05-26 02:32 UTC, shilman requested changes
Hmm I think this PR might introduces a lot of version problems even if it works with your specific project config. @ndelangen can you chime in here?

2017-05-26 02:32 UTC, shilman commented on app/react/package.json
> +	"name": "@storybook/react",
Indentation = 2 spaces

2017-05-26 02:32 UTC, shilman commented on app/react-native/package.json
> +    "react-dom": "^15.5.4",
These should not be dependencies, as I understand it, so that your app can determine the proper version? @ndelangen ?

2017-05-26 02:32 UTC, shilman commented on app/react-native/package.json
> +    "@storybook/addon-actions": "^3.0.0-rc.0",
`apps` should not depend on addons

2017-05-26 05:01 UTC, lifeiscontent commented
@shilman these are in master, I'm just moving them around so they don't get polluted into my app.

2017-05-26 05:48 UTC, lifeiscontent commented
@shilman @ndelangen okay, I found the issue. It lies within the addons package, I believe you've released the addons package while not releasing the v3 of the main package. https://github.com/lifeiscontent/storybook-cra-example you can checkout the package.json

2017-05-26 06:03 UTC, lifeiscontent commented
@shilman @ndelangen Okay, I figured out it was because I was using the old version of getstorybook. Sorry for all the noise.

2017-05-26 06:03 UTC, closed without merging

2017-05-26 07:03 UTC, ndelangen commented
No problem at all! I'm glad you found the solution 👍