Add events addon
storybookjs/storybook pull request #1130
Opened 2017-05-25 21:20 UTC by ndelangen

## What I did
I added the events addon create by @z4o4z to this repository.
original repository here: https://github.com/z4o4z/storybook-addon-events

## How to test

2017-05-25 21:54 UTC, ndelangen commented
@z4o4z care to review?

2017-05-26 05:40 UTC, z4o4z approved these changes

2017-05-26 09:34 UTC, z4o4z requested changes
I'll fix it ASAP

2017-05-26 11:31 UTC, z4o4z approved these changes

2017-06-07 05:29 UTC, merged