Add/composition auto disable
storybookjs/storybook pull request #11364
Opened 2020-06-30 13:01 UTC by ndelangen

Issue: -auto refs are **always added** users might not want that-

## What I did

I added some code that would deal with:
```
module.exports = {
  refs: {
    'my-auto-loaded-ref-id': null,
  },
};
```

This would remove the ref that was auto-injected

2020-07-01 03:17 UTC, tmeasday requested changes
Let’s use `{disabled: true}` for consistency with addons and to avoid confusion with accidental falsey values (<- this is something you originally recommended with addons ;))

2020-07-01 09:52 UTC, ndelangen commented
Good call!

2020-07-02 08:25 UTC, merged

2020-07-02 21:56 UTC, tmeasday commented
Uggh sorry this should have been `disable: true`. Will fix

2020-07-03 08:13 UTC, ndelangen commented on lib/core/src/server/manager/manager-config.js
> +      if (value?.disabled) {
```
	      if (value?.disabled === true) {
```

oops

2020-10-18 14:14 UTC, hems commented
> Uggh sorry this should have been `disable: true`. Will fix

I'm using `"@storybook/react": "^6.0.26"` and when i set `disable: true` i'm getting the following error:

````bash
ERR! TypeError: Cannot read property 'replace' of undefined
ERR!     at stripTrailingSlash (.../node_modules/@storybook/core/dist/server/manager/manager-config.js:93:14)
ERR!     at .../node_modules/@storybook/core/dist/server/manager/manager-config.js:147:14
ERR!     at Array.forEach (<anonymous>)
ERR!     at getManagerWebpackConfig (.../node_modules/@storybook/core/dist/server/manager/manager-config.js:132:33)
ERR!  TypeError: Cannot read property 'replace' of undefined
ERR!     at stripTrailingSlash (.../node_modules/@storybook/core/dist/server/manager/manager-config.js:93:14)
ERR!     at .../node_modules/@storybook/core/dist/server/manager/manager-config.js:147:14
ERR!     at Array.forEach (<anonymous>)
ERR!     at getManagerWebpackConfig (/home/hz/Documents/git/aluna/aluna-next/node_modules/@storybook/core/dist/server/manager/manager-config.js:132:33)
````

this is my main.js file:

```js
module.exports = {
  stories: ['../src/**/*.stories.@(js|ts|jsx|tsx|mdx)'],
  addons: [
    '@storybook/addon-essentials',
    'storybook-addon-styled-component-theme/dist/register'
  ],
  refs: {
    '@chakra-ui/core': {
      disable: true
    } 
  }
}
````

Any ideas?