Add new options to info addon
storybookjs/storybook pull request #1157
Opened 2017-05-30 14:18 UTC by z4o4z

Issue: #1152 

## What I did
Add new options:
- maxPropsIntoLine (default is 3)
- maxPropObjectKeys (default is 3)
- maxPropArrayLength (default is 3)
- maxPropStringLength (default is 50)

## How to test

Run `npm run storybook` to see new stories and test it!

2017-05-30 19:01 UTC, ndelangen requested changes
I don't think we should use context, What problem did you have that you needed context to solve?

2017-05-30 19:01 UTC, ndelangen commented on addons/info/src/components/PropVal.js
> +    return previewProp(this.props.val, this.context);
Can we do it without `context` ?

2017-05-30 19:16 UTC, z4o4z commented
@ndelangen I'm trying to avoid pass identical and never changed props to a lot of places. Why context is  not good idea for it?

2017-05-31 17:25 UTC, z4o4z commented on addons/info/src/components/PropVal.js
> +    return previewProp(this.props.val, this.context);
@ndelangen fixed

2017-06-07 07:10 UTC, z4o4z commented
@ndelangen Hi, of course)

2017-06-07 16:19 UTC, ndelangen approved these changes

2017-06-08 13:37 UTC, merged