feat(ArgValue): pretiffy output of values in PropsTable
storybookjs/storybook pull request #11768
Opened 2020-08-03 08:50 UTC by ajkl2533

Issue: #11681

## What I did
To make values in prop table more obvious and clean, I wrapped all values in a code-like wrapper. For long enums with more than 8 values, I introduced expanding wrapper, where the first 8 values are inlined with a "Show *n* more..." button. When the button is clicked all values are expanded and each value is on its own row.

<img width="860" alt="Screenshot 2020-08-03 at 10 09 38" src="https://user-images.githubusercontent.com/18654425/89164058-daaf4c00-d576-11ea-85ef-eb10e9d5e0bb.png">
<img width="860" alt="Screenshot 2020-08-03 at 10 10 00" src="https://user-images.githubusercontent.com/18654425/89164054-d97e1f00-d576-11ea-9e20-458a079f1637.png">

## How to test

- Is this testable with Jest or Chromatic screenshots? yes, Chromatic
- Does this need a new example in the kitchen sink apps? no
- Does this need an update to the documentation? no

2020-08-03 10:59 UTC, shilman commented
This looks so good @ajkl2533 !!! @domyen can you visually review?

2020-08-03 18:26 UTC, domyen commented
This is awesome! I accepted all the updates.

One last thing, can you create a story for the expanded state where each item has its own row? 

Another contributor could accidentally change the code and break this behavior so it's good to save it as a test baseline now.

2020-08-03 18:27 UTC, domyen requested changes
This is awesome! I accepted all the updates.

Can you create a story for the expanded state where each item has its own row?Another contributor could accidentally change the code and break this behavior so it's good to save it as a test baseline now.

![image](https://user-images.githubusercontent.com/263385/89214785-70f26a80-d595-11ea-9064-da10ed73d469.png)

2020-08-04 08:30 UTC, ajkl2533 commented
@domyen Sure thing, I added new `hasExpandedArgs` prop to ArgsTable which can override the default behaviour and render all arguments and added story for this.

2020-08-04 15:39 UTC, domyen approved these changes

2020-08-04 15:39 UTC, domyen commented
lgtm! @shilman can you confirm? ready to merge from my end ✅

2020-08-04 16:19 UTC, shilman reviewed
@ajkl2533 Sorry, slow to review the code. This looks great visually and I'm super excited about the improvement. However, I'm curious what's the rationale for the `hasExpandedArgs` flag? Can we just make it always be false to simplify the code?

2020-08-04 18:15 UTC, ajkl2533 commented
So one thing is I needed somehow show the expanded state in UI tests :D the second thing is that maybe someone would want to opt-out the expanding feature, which actually would be just for those who include the ArgsTable manually. What is your opinion @shilman I personally don't have a strong opinion on this and I'm ok to remove it, but then I'm not sure how to simulate expanded state in UI tests

2020-08-05 08:20 UTC, shilman commented on lib/components/src/blocks/ArgsTable/ArgValue.tsx
> +const uniq = (arr: string[]): string[] =>
can we use `lodash/uniq`?

2020-08-05 08:35 UTC, ajkl2533 commented on lib/components/src/blocks/ArgsTable/ArgValue.tsx
> +const uniq = (arr: string[]): string[] =>
sure thing

2020-08-05 08:42 UTC, shilman approved these changes
SWEET!! 💯

2020-08-05 09:18 UTC, merged