Update storiesof api docs
storybookjs/storybook pull request #12302
Opened 2020-08-28 16:52 UTC by neilyio

Issue:
The documentation for the `storiesOf` API is missing some important points, as laid out in #12288 

## What I did
- mention of `.addDecorators` and `.addParameters` for component-level story configuration
- quick explainer of global-level parameters with links back to the main documentation.
- explanation of second argument to `storiesOf`, the `module` object.

## How to test
Take a quick look, I did my best!

2020-08-28 20:25 UTC, jonniebigodes requested changes
@neilyio @shilman @tmeasday i was checking this pull request and proposed some changes. 

Hope you're all ok with them.

Feel free to provide feedbacl

2020-08-28 20:25 UTC, jonniebigodes commented on lib/core/docs/storiesOf.md
> +
@neilyio i think we could do better and probably go with something like:

 " Parameters and decorators can also be used globally, you can define them in your `.storybook/preview.js`. Take a look [here](https://storybook.js.org/docs/react/writing-stories/parameters#global-parameters) to learn more about global parameters and [here](https://storybook.js.org/docs/react/writing-stories/decorators#global-decorators) for global decorators."

Let me know if you're ok with it

2020-08-28 20:25 UTC, jonniebigodes commented on lib/core/docs/storiesOf.md
> +
@neilyio we have a bit of room for improvement here. We could probably go with:

" The second argument of `storiesOf` is a reference to each story available. Storybook needs it to enable hot-module-replacement. If it's not included you'll need to refresh your browser with each change you make."

Let me know if you're ok with it.

2020-08-28 20:40 UTC, neilyio commented
@jonniebigodes good feedback, just made your changes.

2020-08-28 20:48 UTC, jonniebigodes commented
wow... @neilyio glad that you were ok with the proposed changes and managed to address them so soon. 

If both @tmeasday and @shilman are ok with it this will get merged.

Do you mind waiting just a bit longer while they take a look at it?

Stay safe

2020-08-28 20:53 UTC, neilyio commented
For sure! Just glad we can address this. This is my first time contributing to anything, so it's kind of exciting! Wasn't even sure how to fork/pull request before.

There are some more additions that need to be made to this file, we're discussing them in issue #12302. It needs to be clear to the user how to use `args` and `argTypes` with `storiesOf`. I'm not sure how they're supposed to work myself, so I'm refraining from adding to the docs just yet.

2020-08-29 01:07 UTC, shilman approved these changes
Looks great @neilyio 💯

2020-08-31 02:00 UTC, tmeasday approved these changes
LGTM, couple of tweaks.

2020-08-31 02:00 UTC, tmeasday commented on lib/core/docs/storiesOf.md
> +The second argument of `storiesOf` is a reference to each story available. Storybook needs it to enable hot-module-replacement. If it's not included you'll need to refresh your browser with each chan
```suggestion
The second argument of `storiesOf` is a webpack `module`, which is available on the global (per-file) scope. Storybook needs it to enable hot-module-replacement. If it's not included you'll need to refresh your browser with each change you make.
```

2020-08-31 02:00 UTC, tmeasday commented on lib/core/docs/storiesOf.md
> +We can control how the component's stories will render with parameters and decorators. You can use as many `.addDecorators` as you need, but you can only use one `.addParameters`, as you can see in t
```suggestion
We can control how the component's stories will render with parameters and decorators. You can use as many `.addDecorators` as you need (but make sure you add them all before your first story), but you can only use one `.addParameters`, as you can see in the example below:
```

2020-09-16 20:37 UTC, jonniebigodes commented
@neilyio @tmeasday sorry for not getting back to this, but i had to shift my attention elsewhere. I wanted to know what's the status of this? Is it good to go, or will it need some additional attention?

Let me know 

Stay safe.

2020-09-17 00:21 UTC, tmeasday commented
Ready to go from my perspective.

2020-09-21 16:32 UTC, jonniebigodes commented
@neilyio going to merge this, should any additional work needs to be implemented we can do a follow up pull request and address it.

Sounds good?

2020-09-21 16:32 UTC, merged

2020-09-21 16:33 UTC, neilyio commented
Sounds great, thanks for looking it over!

2020-09-21 16:56 UTC, jonniebigodes commented
@neilyio no problem and thank you for making the contribution.