Add inline rendering support for svelte components.
storybookjs/storybook pull request #12313
Opened 2020-08-29 17:53 UTC by BlackFenix2

Issue:

## What I did
i added inline rendering support for svelte components, i used a HOC.svelte file to mount the components passed into StoryFn() on the app. 
## How to test

run storybook on svelte-kitchen-sink to see the inline components.

If your answer is yes to any of these, please make sure to include it in your PR.

2020-08-30 05:56 UTC, shilman commented
@BlackFenix2 Hey, just got a chance to test this out and it's working well!

Can you clean up the PR a bit? Specifically:
- Remove all the auto-argtype stuff for a separate PR
- Go through the changes tab here and remove anything not related to inline rendering support?

Looking forward to merging this & releasing in 6.1-alpha!

2020-08-30 06:03 UTC, BlackFenix2 commented
ok, i deleted the unneeded files. everything in this pr is just for inline rendering support now.

2020-08-30 06:08 UTC, shilman requested changes
more cleaning

2020-08-30 06:08 UTC, shilman commented on addons/docs/src/frameworks/svelte/config.ts
> +    // extractArgTypes,
```suggestion
```

2020-08-30 06:08 UTC, shilman commented on addons/docs/src/frameworks/svelte/config.ts
> +    // extractComponentDescription,
```suggestion
```

2020-08-30 06:08 UTC, shilman commented on addons/docs/src/frameworks/svelte/config.ts
> +import { extractArgTypes } from './extractArgTypes';
```suggestion
```

2020-08-30 06:08 UTC, shilman commented on addons/docs/src/frameworks/svelte/HOC.svelte
> +  let greeting = 'Svelte HOC';
```suggestion
```

2020-08-30 06:08 UTC, shilman commented on addons/docs/src/frameworks/svelte/config.ts
> +    // extractComponentDescription,
```suggestion
```

2020-08-30 06:15 UTC, BlackFenix2 reviewed
I finished cleaning up the requested files.

2020-08-30 06:26 UTC, shilman approved these changes
💥 boom! looking great.

2020-08-30 06:27 UTC, shilman commented
I'll merge once we start 6.1, maybe later today or tomorrow.

2020-08-31 12:25 UTC, merged

2020-08-31 16:11 UTC, autoferrit commented
Being new to storybook, is there a place that describes how to use this?

2020-08-31 18:19 UTC, shilman commented
@autoferrit here's the introduction. unfortunately we're missing svelte code snippets

https://storybook.js.org/docs/svelte/writing-docs/introduction

@BlackFenix2 's inline rendering change should be applied automatically in 6.1 without any user intervention required