WIP: revamp addon backgrounds
storybookjs/storybook pull request #12368
Opened 2020-09-03 09:23 UTC by yannbf

Description to be updated later.

Issue:

## What I did

## How to test

- Is this testable with Jest or Chromatic screenshots?
- Does this need a new example in the kitchen sink apps?
- Does this need an update to the documentation?

2020-09-10 13:49 UTC, shilman commented
@yannbf amazing PR! 🙌  any idea what's going on with CI?

2020-09-10 13:51 UTC, yannbf commented
> @yannbf amazing PR! 🙌 any idea what's going on with CI?

Yes, I need to update a few things related to the api given that there's a ViewMode in the story context type and I forgot to do that 🤦‍♀️  I'll do it soon!

2020-09-13 15:05 UTC, yannbf commented on lib/client-api/src/story_store.ts
> +        viewMode: this._selection?.viewMode,
I might be overlooking possible scenarios here.
@ndelangen could you please give a small hand here? I'm not sure if it's ok to just get the value from `this._selection` here. It doesn't seem to be available at all times when this runs. Should it be?

2020-09-19 14:22 UTC, shilman commented
@yannbf what's going on with the DocsPage diffs e.g.

https://www.chromatic.com/snapshot?appId=5a375b97f4b14f0020b0cda3&id=5f6273905740f4002245a96b

2020-09-22 09:49 UTC, yannbf commented
> @yannbf what's going on with the DocsPage diffs e.g.
> 
> https://www.chromatic.com/snapshot?appId=5a375b97f4b14f0020b0cda3&id=5f6273905740f4002245a96b

Hey @shilman I made two changes in docs elements:
1 - [added a "docs-story" class](https://github.com/storybookjs/storybook/pull/12368/files#diff-51c206d10d8a7ed42d2b8f5906eee986R216) so that the element can be selected to apply the background
2 - [added minHeight of 100vh](https://github.com/storybookjs/storybook/pull/12368/files#diff-7a39172dcafc6c48bb12db3174fbb86eR53) so that the docs page always take full height.

The reason for number 2 is that the docs page never took full height but we didn't notice because the background of the iframe was white, but if there's any rule that sets the background to the iframe or the body, then you will have results like this:
![image](https://user-images.githubusercontent.com/1671563/93867077-d7a82080-fcc8-11ea-9250-32a3750fadba.png)

As this PR keeps the style in the body so that when you switch from docs to canvas, the background is already there and there's no flashing, by not having the docs page take full height you can have that result.

But anyway we can check if this is the proper way to fix this and I can rework on whatever is necessary!

2020-09-24 10:43 UTC, shilman requested changes
Finally had a chance to review this PR, and it's really great work. 👏 👏 👏 

I think there are three sets of changes here:
- A bunch of different backgrounds changes
- Making viewMode available in the StoryContext
- The e2e test-clearing code

Ideally this would be three different PRs, or even more because there are so many background changes.

I think splitting out the test-clearing stuff is not necessary, so I'd only like you to split out the viewMode change into its own PR so:
- It can be easily referenced later if there are problems later
- It can be marked as a `feature` not a bug

Aside from that I think it's ready to merge unless anybody else has objections. Thanks for your patience on the review!

2020-09-25 09:05 UTC, shilman approved these changes
🎉 🎉 🎉

2020-09-25 09:05 UTC, merged

2020-09-30 20:39 UTC, sam-m-m commented
Is there documentation on how to change the canvas background color with a toolbar theme control button?

I've looked at the [theming docs](https://storybook.js.org/docs/react/configure/theming), browsed through some of the github issues without much luck.

Do you have to write a custom hook like how this [stackoverflow answer](https://stackoverflow.com/a/63089282) does?

I'm talking about just this part:
![Sep-30-2020 13-38-47](https://user-images.githubusercontent.com/68707128/94737223-541ead00-0322-11eb-808c-0f5f610aed12.gif)

2020-10-01 05:46 UTC, tmeasday commented
@jonniebigodes ☝️ I've seen @sam-m-m's request here a couple times so if we could figure out the current best practice we should document it (also thinking about a way of supporting it "natively" without breaking the global's model too mich).

2020-10-01 19:08 UTC, sam-m-m commented
@jonniebigodes A recipe and native support both sound like great ideas. Allowing options to change theming for the canvas, docs or the main sb would also be nice. So that you can do something like this or just update the theme in the canvas | docs | main sb:

![pi](https://user-images.githubusercontent.com/68707128/94846823-9ef9fc80-03d6-11eb-82d1-70b41acd8867.gif)

Note: For anyone who wants to get this to work now, here's an [example repo](https://github.com/mrinalini-m/storybook-test-theming/blob/master/.storybook/preview.tsx) that uses the [storybook-dark-mode package](https://github.com/hipstersmoothie/storybook-dark-mode).

2020-10-01 22:22 UTC, jonniebigodes commented
@sam-m-m wow...i can't express enough thanks for you to share a reproduction. I'll take a look at it during the weekend in conjunction to a good place for the recipes, if you don't mind. And we can go from there. If you're willing to contribute to the recipes with this one i would gladly review it and merge it. 

Do you mind waiting a bit longer?

2020-10-02 20:01 UTC, sam-m-m commented
@jonniebigodes I was able to figure it using [storybook/examples/official-storybook/preview.js](https://github.com/storybookjs/storybook/blob/next/examples/official-storybook/preview.js) as a reference. I haven't updated the example repo yet. I'll try to do it this evening. 

I'd love to contribute to the recipes!

2020-10-02 20:04 UTC, jonniebigodes commented
And we'd love for the contribution. Once it's setup and everything is working i'll let you know and we can go from there. Don't worry about including it in your repo. We still have time :)