Addon-docs: Apply transformSource to any SourceType if it is specified
storybookjs/storybook pull request #12375
Opened 2020-09-03 19:27 UTC by phated

Issue: N/A

## What I did

I made the `transformSource` function (if specified) apply to all `SourceType` snippets.

While trying to modify the snippets produced for `SourceType.DYNAMIC`, I noticed that the `transformSource` option was only being applied to `SourceType.CODE` snippets. This seems to be due to it being called inside `enhanceSource`, but the `SourceType` refactoring came after, so I think it got missed in the shuffle.

## How to test

- Is this testable with Jest or Chromatic screenshots? I don't think so, I see some other refactors that can happen with enhanceSource and then things can be tested together.
- Does this need a new example in the kitchen sink apps? I believe the kitchen sink app will get these through it's `transformSource` config.
- Does this need an update to the documentation? Nope, the recipe actually makes it sound like this is globally called already.

If your answer is yes to any of these, please make sure to include it in your PR.

2020-09-09 23:22 UTC, shilman requested changes
Looks great! Can you add an `official-storybook` example in `Addons/Docs` to demo this?

2020-09-09 23:23 UTC, phated commented
Yep! I'll put one together now 😄

2020-09-10 00:49 UTC, phated commented
Here's a screenshot of what this looks like in the `official-storybook`!
<img width="634" alt="Screen Shot 2020-09-09 at 5 49 15 PM" src="https://user-images.githubusercontent.com/992373/92668874-d76d5580-f2c4-11ea-8179-7440b17f28cf.png">

2020-09-10 01:46 UTC, shilman requested changes
the string values are not capitalized 😭

2020-09-10 01:46 UTC, shilman commented on examples/official-storybook/stories/addon-docs/transform-source.stories.js
> +  docs: { source: { type: 'CODE' } },
```suggestion
  docs: { source: { type: 'code' } },
```

2020-09-10 01:46 UTC, shilman commented on examples/official-storybook/stories/addon-docs/transform-source.stories.js
> +  docs: { source: { type: 'DYMANIC' } },
```suggestion
  docs: { source: { type: 'dynamic' } },
```

2020-09-10 01:46 UTC, shilman commented on examples/official-storybook/stories/addon-docs/transform-source.stories.js
> +  docs: { source: { type: 'AUTO' } },
```suggestion
  docs: { source: { type: 'auto' } },
```

2020-09-10 01:55 UTC, phated commented
Whoops, sorry about that. I've applied your suggestions!

2020-09-10 14:24 UTC, shilman approved these changes
🙌

2020-09-10 14:25 UTC, merged