Fix typescript codemod storiesof to csf
storybookjs/storybook pull request #12453
Opened 2020-09-11 09:58 UTC by remorses

Issue: #9669

## What I did

- fix prettier parser to use the correct parser name
- use `StringLiteral` ast name instead of `Literal` when using typescript
- use project prettier config to format

2020-09-11 15:27 UTC, shilman requested changes
Hey @remorses, thanks so much for fixing this! 😍 

The change seems to be messing up the snapshot tests. I dug in for a minute but wasn't obvious to me why... do you have any ideas?

2020-09-11 16:42 UTC, ndelangen commented
Seems like all changes are just quotes..

Is there some prettier config we need to pass in?

2020-09-11 16:49 UTC, shilman commented
I put some logging in earlier and the project prettier config which is supposed to be respected (awesome!) seems to have single quotes, but the output has double quotes.

2020-09-12 13:08 UTC, remorses commented
Fixed, now it is using the correct prettier config

2020-09-12 17:25 UTC, shilman approved these changes
🙌

2020-09-12 17:25 UTC, merged