Web Components: Add script tag support
storybookjs/storybook pull request #12509
Opened 2020-09-17 20:55 UTC by zolk

Following the example of #12089 for HTML, this adds `<script>` tag support for Web Components.

Not sure if we want to move `simulate-pageload.ts` into a shared location rather including a separate copy with each app?

## How to test

Example stories have been added to `web-components-kitchen-sink` in  `script.stories.js`, one rendered with `lit-html` and another as a basic string.

2020-09-20 01:01 UTC, jonspalmer commented
I extracted the simulate-pageload to client-api in #12522. Would be great to take advantage of that for this PR.

2020-09-20 16:00 UTC, shilman requested changes
Thanks @zolk, looks great!! Can you please update to take advantage of @jonspalmer 's refactor? 🙏

2020-09-20 19:35 UTC, zolk commented
> Thanks @zolk, looks great!! Can you please update to take advantage of @jonspalmer 's refactor? 🙏

Updated!

2020-09-21 02:10 UTC, shilman approved these changes
Super! 💯

2020-09-21 02:10 UTC, merged