ADD async render support
storybookjs/storybook pull request #1253
Opened 2017-06-11 13:54 UTC by ndelangen

Issue: -add is sync but sometimes we want to do some async setup on first render-

## What I did
Add support for a function in `.add()` that returns a Promise

## Todo
- [ ] Add this to docs

## How to test
Should add something to the kitchen sink probably.

2017-06-12 09:37 UTC, shilman requested changes
Looks pretty straightforward. But needs:
 - [ ] docs including a motivating example
 - [ ] test case

2017-07-01 02:04 UTC, danielduan approved these changes

2017-07-01 02:05 UTC, danielduan commented on app/react/src/client/preview/render.js
> +  return Promise.resolve(story(context)).then(element => {
I think it'd be nice to have an example usage of this somewhere.

2017-07-05 09:27 UTC, ndelangen commented on app/react/src/client/preview/render.js
> +  return Promise.resolve(story(context)).then(element => {
Good point!

2017-07-28 13:47 UTC, ndelangen commented
I'm dropping this for now, and will revisit this at a later stage.
#1209

2017-07-28 13:47 UTC, closed without merging

2017-07-28 13:48 UTC, ndelangen commented
Please do **NOT** remove remote branch

2018-02-28 05:07 UTC, swillis12 commented
Any plans to pick this back up? Looks like branch was deleted.