fix(addons/info): Cannot read property 'props' of undefined
storybookjs/storybook pull request #1258
Opened 2017-06-12 03:03 UTC by evenchange4

Issue:

![2017-06-12 11 02 52](https://user-images.githubusercontent.com/1527371/27017902-b56061ba-4f5e-11e7-9bea-7612d71751dc.png)

## What I did

fix(addons/info): Cannot read property 'props' of undefined

## How to test

2017-06-12 06:24 UTC, shilman commented
@evenchange4 Thanks for the contribution! Can you explain how to reproduce the problem and test the change? Thanks!

2017-06-12 07:30 UTC, evenchange4 commented
@shilman Sure, I have updated my description above.

2017-06-12 07:57 UTC, shilman commented
Thanks! Confirmed the problem and added a test in https://github.com/storybooks/storybook/pull/1259

2017-06-12 07:59 UTC, shilman commented
Thanks, reproduced it and added test case to: https://github.com/storybooks/storybook/pull/1259

2017-06-12 08:02 UTC, shilman requested changes
Requested a small change. what do you think?

2017-06-12 08:02 UTC, shilman commented on addons/info/src/components/markdown/text.js
> +  return <a href={props.href} style={style}>{props.children}</a>;
Suggestion: add `target="_blank" rel="noopener noreferrer"`

2017-06-12 08:40 UTC, evenchange4 commented on addons/info/src/components/markdown/text.js
> +  return <a href={props.href} style={style}>{props.children}</a>;
Agree, I always put external links here, and there is already `@storybook/addon-links` solution for linking between stories at same site.

2017-06-12 08:45 UTC, shilman approved these changes

2017-06-12 09:13 UTC, merged

2017-06-15 12:18 UTC, shilman commented
released https://github.com/storybooks/storybook/releases/tag/v3.1.4

thanks @evenchange4 !