fix(react/jsxDecorator): displayName works for exotic components
storybookjs/storybook pull request #12638
Opened 2020-10-01 06:24 UTC by andezzat

## The Problem

React Memo & ForwardRef exotic components would show up in the code snippet of storybook as `<[object Object]>` because it didn't know where to lookup the inner render function's name.

https://github.com/algolia/react-element-to-jsx-string/issues/352

## What I did

I stole the default `displayNameFn` from the original library [here](https://github.com/algolia/react-element-to-jsx-string/blob/4974512273c86c72415376fea89f9d6e07e2b2e5/src/parser/parseReactElement.js#L15) 
And added what it needed to fetch Memo & ForwardRef component's names.

## How to test

- Is this testable with Jest or Chromatic screenshots?
Maybe? I have no idea
- Does this need a new example in the kitchen sink apps?
No
- Does this need an update to the documentation?
No

If your answer is yes to any of these, please make sure to include it in your PR.

2020-10-01 09:07 UTC, ndelangen approved these changes

2020-10-01 23:16 UTC, andezzat commented on addons/docs/src/frameworks/react/jsxDecorator.test.tsx
> +       />
😂 
For some reason linter worked first time, but not when I forked 🤷 
Sorry!

2020-10-03 06:36 UTC, shilman requested changes
Hey @andezzat !! Thanks so much for putting this together -- will make a ton of people happy. Unfortunately, I added a test case to `official-storybook` and it doesn't seem to be working end-to-end. You can find that in the latest commit on this branch.

Would you mind:
- looking into this specific case
- adding more test cases to official-storybook
- reconciling the official-storybook behavior and the jest test cases (look great, but somehow don't line up)

2020-10-05 04:26 UTC, shilman commented on examples/official-storybook/stories/addon-docs/react-forward-ref.stories.js
> +export default {
can we delete this file now?

2020-10-05 04:27 UTC, shilman approved these changes
LGTM! 💯 💯 💯

2020-10-05 04:28 UTC, andezzat commented on examples/official-storybook/stories/addon-docs/react-forward-ref.stories.js
> +export default {
Woopsie! 😅

2020-10-05 05:04 UTC, merged

2020-10-09 12:06 UTC, ghengeveld commented
This appears to be broken:

<img width="502" alt="Screenshot 2020-10-09 at 14 05 32" src="https://user-images.githubusercontent.com/321738/95581002-8920b300-0a38-11eb-9d40-efff975c3111.png">

It seems to originate from `ForwardRefButtonInnerPropTypes` which wraps a button component directly in `forwardRef`, which is not allowed.

2020-10-09 12:19 UTC, shilman commented
cc @andezzat can you take a look ☝️ \

2020-10-10 23:45 UTC, andezzat commented
Ah yes, I should've made a new component w/ proper `forwardRef` fn args than passing `BaseButton` as-is 😂
PR: #12733