Core: Add highlight.js to es6 transpiled modules
storybookjs/storybook pull request #12811
Opened 2020-10-18 13:54 UTC by tooppaaa

Issue: IE 11

## What I did

Transpile highlight.js

## How to test

- Be bold and launch IE 11

2020-10-18 15:33 UTC, tooppaaa commented
@gaetanmaisse any idea on fixing yarn 2 while keeping the highlight.js transpilation ?

2020-10-18 15:47 UTC, shilman requested changes
Small tweak?

2020-10-18 15:47 UTC, shilman commented on lib/core/src/server/common/es6Transpiler.js
> +  const include = /[\\/]node_modules[\\/](@storybook\/node-logger|are-you-es5|better-opn|boxen|chalk|commander|find-cache-dir|find-up|fs-extra|highlight.js|json5|node-fetch|pkg-dir|resolve-from|semve
`highlight\.js`?

2020-10-19 07:56 UTC, tooppaaa commented on lib/core/src/server/common/es6Transpiler.js
> +  const include = /[\\/]node_modules[\\/](@storybook\/node-logger|are-you-es5|better-opn|boxen|chalk|commander|find-cache-dir|find-up|fs-extra|highlight.js|json5|node-fetch|pkg-dir|resolve-from|semve
Done but still not working in yarn 2 :(

2020-10-19 19:13 UTC, gaetanmaisse commented
@tooppaaa I discussed a bit about that with @yannbf and we have some options in mind. Let's talk in the next few days.

2020-10-24 18:14 UTC, yannbf commented
LGTM! I'm not sure if there are possible side effects to this but seems solid. Of course there has to be some documentation as well, maybe on FAQ?

2020-10-24 18:41 UTC, tooppaaa commented
Just waiting to be sure we want to go to the path of adding options like this in main.js @shilman @tmeasday @ndelangen ?

I'm sure @jonniebigodes will be able to point me the right direction for documenting this after :D

2020-10-26 10:38 UTC, ndelangen commented
I thought we used prism for code highlighting rather than highlight?

where are we using highlight?

2020-10-26 22:25 UTC, jonniebigodes commented
@tooppaaa let me know when you have something created and we can go from there. Sounds good?

2020-10-28 21:47 UTC, tooppaaa commented
> where are we using highlight?

Don't know but it's definitely present in the bundles.

2020-11-10 06:36 UTC, shilman commented
I think this is no longer needed because of #12948. @tooppaaa WDYT?

2020-11-10 21:38 UTC, tooppaaa commented
IE 11 is working ! not needed !

2020-11-10 21:38 UTC, closed without merging