Update extractArgTypes.ts
storybookjs/storybook pull request #13127
Opened 2020-11-16 07:18 UTC by hmleo

Issue: Methods not shown use ArgsTable with vue framework( https://github.com/storybookjs/storybook/issues/13105)

## add SECTION Methods

## test in node_modules: change file content as same as in PR（node_modules\@storybook\addon-docs\dist\frameworks\vue\extractArgTypes.js），and it worked in my project

- Is this testable with Jest or Chromatic screenshots?
- Does this need a new example in the kitchen sink apps?
- Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

2020-11-16 08:35 UTC, shilman requested changes
Looks good @hmleo, thanks for adding. can you add an example to `examples/vue-kitchen-sink` so we have a test case in the repo?

2020-12-01 09:50 UTC, shilman commented
@hmleo any chance you can add an example to `examples/vue-kitchen-sink`? would love to merge but can't merge unless we have an example demonstrating that nothing breaks. thanks!

2021-02-20 23:47 UTC, HIMISOCOOL commented
@hmleo do you have any time to update the examples/vue-kitchen-sink and add a few methods with the jsdoc fields? It would be awesome to have this.

2021-11-25 15:02 UTC, Nisgrak commented
Any updates on this?

2022-06-30 14:05 UTC, ndelangen commented
The repository where this PR originates from is removed, I made a replacement PR here: https://github.com/storybookjs/storybook/pull/18609

2022-06-30 14:05 UTC, closed without merging