Core: Add `prefix` customization for navigation items
storybookjs/storybook pull request #13121
Opened 2020-11-15 13:30 UTC by tooppaaa

Issue: Lack of capability to add elements to

(Updated after @ghengeveld work)

sidebar subheadings (most important one in my opinion)
sidebar items
folder
component
story
This PR aims as a proposal for this and basis of discussions

![image](https://user-images.githubusercontent.com/599163/99186191-fff34f00-274e-11eb-81aa-cfd33ba8a9bd.png)

Should we keep double icons when prefix is set ?
Should it be called prefix ?

2021-01-06 08:13 UTC, shilman commented
cc @domyen @ghengeveld let's see what we can do to get this over the line

2021-01-06 09:01 UTC, wKich commented
Yeah. It would be great to add prefix for items.

2021-01-11 09:43 UTC, saulmases commented
I comment here because there is also interest in being able to customise storybook sidebar, like adding a prefix before the items so we can add there things like component status in the sidebar.

2021-01-13 05:29 UTC, wKich commented
@tooppaaa, @shilman, can we also add a method to the client API that allows changing prefixes from code?

2021-01-13 07:55 UTC, tooppaaa commented
@wKich, that can be an interesting feature. I'd like to get this one merged before bringing more changes

2021-01-13 21:38 UTC, tooppaaa commented
@shilman merged next into this one.

2021-01-18 21:00 UTC, tooppaaa commented
@ghengeveld any update ?

2021-02-01 11:15 UTC, ghengeveld commented
Hey, I would like to propose the following:

- We rename `storyPrefix` to `sidebar` in the config.
- This accepts an object, with a `storyLabel` property (and potentially other sidebar config options, later down the road).
- `storyLabel` is a function, which takes an Item (`Root | Group | Story`) and should return a string or ReactNode.
- The default implementation would be `item => item.name`.

This would allow much more flexibility in terms of how the label is rendered in the sidebar.

2021-02-01 21:38 UTC, tooppaaa commented
Done

2021-02-21 19:43 UTC, tooppaaa commented on lib/ui/src/components/sidebar/Tree.tsx
> +          {item.storyLabel || item.name}
The user interface for this is a function: ```storyLabel: ({ id, name }) => {}```, internally, it's a react node

2021-02-24 20:23 UTC, tooppaaa commented
@ghengeveld, I can't be keeping up to date with PR's that are open for that long time. Can we either get it moving or declined ?

2021-02-25 12:28 UTC, shilman commented on lib/ui/src/components/sidebar/Tree.stories.tsx
> +    storyLabel: <span>🔥 Single</span>,
No, I think this is the output of the label function (e.g. the values in the map that he defines in his example)

2021-02-25 12:35 UTC, shilman requested changes
@ghengeveld This all looks good to me. The only thing that's weird about it is that the user specifies the `sideBar.storyLabel` function, and the result of that function is a react node called `storyLabel`, which is confusing. I think the function should be called `createStoryLabel` or something more explicit.

Also I thought about the portability of this feature and I think it's probably fine, so long as the user doesn't depend on the `storyLabel` for anything. If we consider it like "visual enhancement" to the underlying data, then other ecosystem tools can just ignore this configuration and provide a downgraded experience which should be fine.

2021-02-26 16:41 UTC, ghengeveld commented
I brought this up-to-date with `next`, as well as upcoming changes from `sidebar-config`, so this now telescopes on `sidebar-config`.

Along with the merge I made some API changes and updated the docs:
- The config option is now `sidebar.renderLabel` which accepts a function `(item: Root | Group | Story) => ReactNode`
- Root, Group and Story now have a `label` property which contains the result of invoking `renderLabel`.

That should avoid any confusion over `storyLabel`.

2021-03-01 14:43 UTC, shilman approved these changes
Looking great @ghengeveld @tooppaaa 💯

2021-03-01 14:44 UTC, merged