Chore: How to add to Storybook addon catalog documentation.
storybookjs/storybook pull request #13438
Opened 2020-12-12 00:36 UTC by jonniebigodes

With this pull request the addon documentation is updated to include information on how to add to the addon catalog.

What was done:
- Created the documentation
- Updated the toc file
- Included assets

Feel free to provide feedback

2020-12-12 03:22 UTC, shilman requested changes
LGTM @jonniebigodes with small changes

2020-12-12 03:22 UTC, shilman commented on docs/addons/addon-catalog.md
> +| name        | Addon display name                     | My-addon                                                              |
```suggestion
| name        | Addon package name                     | my-addon                                                             |
```

2020-12-12 03:22 UTC, shilman commented on docs/addons/addon-catalog.md
> +| displayName           | Addon display name             | My-addon          |
```suggestion
| displayName           | Addon display name             | My Addon          |
```

2020-12-12 03:22 UTC, shilman commented on docs/addons/addon-catalog.md
> +    "displayName": "My-addon",
```suggestion
    "displayName": "My Addon",
```

2020-12-12 17:28 UTC, winkerVSbecks approved these changes

2020-12-12 17:48 UTC, domyen commented
I updated the PR for accuracy and clarity. Please review.

2020-12-12 17:48 UTC, domyen approved these changes

2020-12-14 17:26 UTC, jonniebigodes commented
Self merging this.

2020-12-14 17:26 UTC, merged