Release process
storybookjs/storybook pull request #1348
Opened 2017-06-23 04:01 UTC by shilman

Issue: N/A

## What I did

Document our release/decision-making process initially for discussion purposes, and finally as a reference so we have some standards about this for our releases.

- Gathered/incorporated some feedback from this gist: https://gist.github.com/shilman/7993bc0c74974ef1ace7c4f96900554c
- Extended it to incorporate the concept of blocking bugs as discussed with @tmeasday 

## How to test

N/A

2017-06-23 04:05 UTC, tmeasday requested changes

2017-06-23 04:05 UTC, tmeasday commented on RELEASES.md
> +addressed before a release can go out by adding them to the milestone. For example, here's a list of blocking bugs [for the 3.2 milestone](https://github.com/storybooks/storybook/milestone/3).
Is this link broken?

2017-06-23 04:05 UTC, tmeasday commented on RELEASES.md
> +search](https://github.com/storybooks/storybook/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).
Can we change this link to filter out non-`bug`s, `fixed` bugs, bugs with a milestone, etc

2017-06-23 04:05 UTC, tmeasday commented on RELEASES.md
> +    -   Once it's implemented, the discussion may be occur on the PR (ex: <https://github.com/storybooks/storybook/issues/151>)
Should this be a PR link?

2017-06-23 04:23 UTC, shilman commented
@tmeasday thanks for catching the typos. added a `bug` filter to the issue search, but did not filter out issues that have a milestone because it's useful to see when things are scheduled among the results. can filter more later if things get too out of control.

2017-06-23 04:26 UTC, tmeasday approved these changes

2017-06-23 04:26 UTC, tmeasday commented
LGTM! Might want to wait for a couple more approvals to this process change.

2017-06-23 06:55 UTC, shilman commented on RELEASES.md
> +addressed before a release can go out by adding them to the milestone. For example, here's a list of blocking bugs [for the 3.2 milestone](https://github.com/storybooks/storybook/milestone/3).
It's all open issues in the 3.2 milestone, but I think that's OK?

2017-06-23 06:57 UTC, tmeasday commented on RELEASES.md
> +addressed before a release can go out by adding them to the milestone. For example, here's a list of blocking bugs [for the 3.2 milestone](https://github.com/storybooks/storybook/milestone/3).
Yeah I was wrong, I just eyeballed and though it was supposed to say `..../3.2`

2017-06-23 07:39 UTC, igor-dv approved these changes
LGTM

2017-06-23 08:27 UTC, alexandrebodin commented on RELEASES.md
> +1\. merge bugfix PRs directly into master automatically release (~daily)
I would end the lines here for clarity

2017-06-23 08:55 UTC, shilman commented on RELEASES.md
> +1\. merge bugfix PRs directly into master automatically release (~daily)
@alexandrebodin thanks. some weird linting auto-fix 😄

2017-06-27 06:56 UTC, usulpro approved these changes

2017-06-28 09:30 UTC, ndelangen approved these changes

2017-06-28 09:30 UTC, ndelangen commented
Looks good to me!

2017-06-28 12:03 UTC, merged