Improve docs for loading fonts locally
storybookjs/storybook pull request #13488
Opened 2020-12-19 15:53 UTC by domyen

Issue: na

## What I did
Improve docs for loading fonts from a static directory. This was a stumbling block for a [user in Discord](https://discord.com/channels/486522875931656193/501692020226654208/789646850008285195). 

## How to test

- Is this testable with Jest or Chromatic screenshots? no
- Does this need a new example in the kitchen sink apps? no
- Does this need an update to the documentation? no

2020-12-19 17:16 UTC, jonniebigodes requested changes
@domyen one small adjustment and this should be good to go.

2020-12-19 17:16 UTC, jonniebigodes commented on docs/get-started/setup.md
> +If you want to [link to static files](../configure/images-and-assets) in your project or stories (e.g. `/fonts/XYZ.woff`), use the `-s path/to/folder` to specify a static folder to serve from when yo
@domyen adjust this "../configure/images-and-assets " to "../configure/images-and-assets.md"

2020-12-19 17:54 UTC, domyen commented on docs/get-started/setup.md
> +If you want to [link to static files](../configure/images-and-assets) in your project or stories (e.g. `/fonts/XYZ.woff`), use the `-s path/to/folder` to specify a static folder to serve from when yo
```suggestion
If you want to [link to static files](../configure/images-and-assets.md) in your project or stories (e.g. `/fonts/XYZ.woff`), use the `-s path/to/folder` to specify a static folder to serve from when you start up Storybook. To do so, edit the `storybook` and `build-storybook` scripts in `package.json`.
```

2020-12-19 17:55 UTC, domyen commented
ty - made the change @jonniebigodes

2020-12-20 09:37 UTC, shilman approved these changes

2020-12-20 09:37 UTC, shilman commented on docs/configure/images-and-assets.md
> +We recommend serving static files via Storybook to ensure that your components always have the assets they need to load. This technique is recommended for assets that your component's often use like
```suggestion
We recommend serving static files via Storybook to ensure that your components always have the assets they need to load. This technique is recommended for assets that your components often use like logos, fonts, and icons.
```

2020-12-20 09:38 UTC, merged