Addon: infer jest parameter from story file name if not provided
storybookjs/storybook pull request #13535
Opened 2020-12-29 16:19 UTC by dominictwlee

Issue: #12084

## What I did
Added functionality to infer jest parameter from file name if not provided explicitly.

## How to test

- Is this testable with Jest or Chromatic screenshots? yes
- Does this need a new example in the kitchen sink apps? yes
- Does this need an update to the documentation? yes

If your answer is yes to any of these, please make sure to include it in your PR.

2020-12-30 03:12 UTC, shilman requested changes
Thanks for building this feature @dominictwlee !

Unfortunately, it does not seem to be working in the static build of Storybook:

<img width="1264" alt="Addons___Jest_-_With_Inferred_Tests_⋅_Storybook" src="https://user-images.githubusercontent.com/488689/103327438-8a89d680-4a8f-11eb-8969-dcafe02e3dff.png">

The issue is that the file path is not available in the static build. We can try to fix that underlying issue, which I suspect is hard, although I don't know the full background. More likely, we should fix the bug in the current code and add documentation that this doesn't work in production builds.

WDYT?

2020-12-30 12:01 UTC, dominictwlee commented
> Thanks for building this feature @dominictwlee !
> 
> Unfortunately, it does not seem to be working in the static build of Storybook:
> 
> <img alt="Addons___Jest_-_With_Inferred_Tests_⋅_Storybook" width="1264" src="https://user-images.githubusercontent.com/488689/103327438-8a89d680-4a8f-11eb-8969-dcafe02e3dff.png">
> 
> The issue is that the file path is not available in the static build. We can try to fix that underlying issue, which I suspect is hard, although I don't know the full background. More likely, we should fix the bug in the current code and add documentation that this doesn't work in production builds.
> 
> WDYT?

Oh odd, thought the falsy check would fix that.

I had a closer look and it seems that the `fileName` property ends up being a number, something like `1264`.
I'll do the extra check for that. Would you also like me to update the interface for Parameter? (currently it's defined as `fileName?: string`)

2020-12-30 14:48 UTC, dominictwlee commented
I'll maybe leave the Parameter type for a separate PR (if needed), since it could potentially break anything else that relies on it.

2020-12-31 09:35 UTC, shilman approved these changes
Excellent! 💯

2020-12-31 09:35 UTC, merged