fix: allow multiple assets with different types
storybookjs/storybook pull request #1363
Opened 2017-06-27 00:49 UTC by joscha

Issue:

## What I did

Upgraded from `@kadira/storybook@1.x` and had the [`extract-text-webpack-plugin`](https://github.com/webpack-contrib/extract-text-webpack-plugin/) enabled.

Unfortunately my CSS didn't load, encountering the same issue as described in #1104 and most likely #388 and #708.

Using the `extract-text-webpack-plugin` creates a new entry point however, making the asset list look something like this:
```json
{ manager: 'static/manager.02f732c9002a59214667.bundle.js',
  preview:
   [ 'static/preview.352040d027a7c22331ae.bundle.js',
     'static/preview.1f62768c19a65e75e4259a4c418d292d.css',
     'static/preview.1f62768c19a65e75e4259a4c418d292d.css.map' ] }
```
and due to https://github.com/storybooks/storybook/blob/34b96aae764a386c35d4db2a057e85236bd8ddfe/app/react/src/server/iframe.html.js#L33 only ever taking the very first asset, the CSS never makes it into `iframe.html`.

## How to test

I added new tests :)

fixes #1104, #388, #708

2017-06-27 10:56 UTC, joscha commented
@shilman I assigned you, as you seem to be quite active these days :-) Let me know if anything is unclear! Hoping to get the fix for this regression in asap to de-confuse our `extract-text-webpack-plugin`-users :)

2017-06-28 10:16 UTC, joscha commented
@UsulPro I saw you were last active, would you mind having a look? I am blocked by this, but need a second pair of eyes on it :)

2017-06-28 10:55 UTC, shilman requested changes

2017-06-28 10:55 UTC, shilman commented on app/react/src/server/iframe.html.js
> +export const urlsFromAssets = assets => {
who uses this? does it need to be exported?

2017-06-28 10:55 UTC, shilman commented on app/react/src/server/iframe.html.js
> +      assetList.filter(u => re.exec(u)[1] !== 'map').forEach(u => {
u => url?

2017-06-28 11:04 UTC, joscha commented on app/react/src/server/iframe.html.js
> +export const urlsFromAssets = assets => {
Only the tests, but for those it needs to be exported, yes.

2017-06-28 11:06 UTC, joscha commented on app/react/src/server/iframe.html.js
> +      assetList.filter(u => re.exec(u)[1] !== 'map').forEach(u => {
done in f33b05a6ccb74cae1d681fc3ab7b3ea7

2017-06-28 11:10 UTC, shilman approved these changes

2017-06-28 11:55 UTC, merged

2017-06-28 13:01 UTC, joscha commented
Tested in `3.1.7`, works as expected:

```
➜  web git:(joscha/unfork-storybook) yarn build-storybook
yarn build-storybook v0.24.6
@storybook/react v3.1.7

=> Loading custom addons config.
=> Loading custom webpack config (extending mode).
Building storybook ...
ts-loader: Using typescript@2.3.4 and /Users/joscha/Development/canva/web/tsconfig.ts-loader.json
✨  Done in 382.09s.
➜  web git:(joscha/unfork-storybook) ✗ cat target/storybook/iframe.html | grep link
        <link rel='stylesheet' type='text/css' href='preview.89d82dfdc51e6aeaba00b6d8a4785cf3.css'>
```

2017-06-29 16:26 UTC, danielmcgrath commented
@joscha do you happen to have a sample project you could point to? I'm on 3.1.7 and can't for the life of me get webpack to actually generate the CSS file. We haven't hit any issues with extract-text-plugin in other projects so I'm wondering if there's a storybook-specific step I'm missing here.

2017-06-29 21:20 UTC, joscha commented
@danielmcgrath we use extension mode (e.g. we have an additional `webpack.config.js` in the `conf/` folder and then we do:


```
  const extractCSS = new ExtractTextPlugin({
    // The filename does not contain a hash in dev and local such that conf/head.html used by
    // Storybook can refer directly to the static filename in Storybook.
    filename: options.hashOutputFileNames ? '[name].[contenthash].css' : '[name].css',
    allChunks: true,
    ignoreOrder: true,
  });

// ...
plugins: [
  extractCSS
]
```
that's all that is needed for a `preview.c0ffee.css` to be generated and picked up in the HTML.

2017-06-30 11:26 UTC, WellerQu commented
Hi, @joscha , We very love storybook. But we got the error:

```
ERROR in ./src/core/view/style.sass
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (/Users/qiuwei/Workspace/rongcaptial-ui/node_modules/extract-text-webpack-plugin/loader.js:25:9)
 @ ./src/core/view/index.js 33:13-36
 @ ./src/core/index.js
 @ ./stories/view.story.js
 @ ./build/config.js
 @ multi ./~/@storybook/react/dist/server/config/polyfills.js ./~/@storybook/react/dist/server/config/globals.js ./~/webpack-hot-middleware/client.js?reload=true ./build/config.js
```

My custorm webconfig is:

```javascript
rules: [
            {
                // use sass-loader for *.sass files
                test: /\.sass/i,
                use: ExtractTextPlugin.extract({ 
                    fallback: 'style-loader',
                    use: [
                        { 
                            loader: `css-loader?modules&localIdentName=${ __DEV__ ? '[path][name]__[local]--[hash:base64:5]' : '[hash:base64]' }`,
                        },
                        {
                            loader: 'postcss-loader',
                            options: {
                                plugins: [
                                    precss,
                                    autoprefixer
                                ]
                            }
                        },
                        {
                            loader: "sass-loader",
                        },
                    ],
                }),
                exclude: /node_modules/
            },
]
```

    "@storybook/react": "^3.1.7", from [here](https://storybook.js.org/basics/slow-start-guide/)
    "webpack": "2.2.0",
    "webpack-merge": "^4.1.0",



Any ideas, please

2017-07-01 00:30 UTC, joscha commented
You need to add it to the `plugins` array as well.

On 30 Jun. 2017 13:26, "Nixon" <notifications@github.com> wrote:

> Hi, @joscha <https://github.com/joscha> , We very love storybook. But we
> got the error:
>
> ERROR in ./src/core/view/style.sass
> Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
>     at Object.module.exports.pitch (/Users/qiuwei/Workspace/rongcaptial-ui/node_modules/extract-text-webpack-plugin/loader.js:25:9)
>  @ ./src/core/view/index.js 33:13-36
>  @ ./src/core/index.js
>  @ ./stories/view.story.js
>  @ ./build/config.js
>  @ multi ./~/@storybook/react/dist/server/config/polyfills.js ./~/@storybook/react/dist/server/config/globals.js ./~/webpack-hot-middleware/client.js?reload=true ./build/config.js
>
> My custorm webconfig is:
>
> rules: [
>             {
>                 // use sass-loader for *.sass files
>                 test: /\.sass/i,
>                 use: ExtractTextPlugin.extract({
>                     fallback: 'style-loader',
>                     use: [
>                         {
>                             loader: `css-loader?modules&localIdentName=${ __DEV__ ? '[path][name]__[local]--[hash:base64:5]' : '[hash:base64]' }`,
>                         },
>                         {
>                             loader: 'postcss-loader',
>                             options: {
>                                 plugins: [
>                                     precss,
>                                     autoprefixer
>                                 ]
>                             }
>                         },
>                         {
>                             loader: "sass-loader",
>                         },
>                     ],
>                 }),
>                 exclude: /node_modules/
>             },
> ]
>
> "@storybook/react": "^3.1.7", from [here](https://storybook.js.org/basics/slow-start-guide/)
> "webpack": "2.2.0",
> "webpack-merge": "^4.1.0",
>
> Any ideas, please
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/storybooks/storybook/pull/1363#issuecomment-312243581>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AALehr8UKS_TD8U5gIak-roW0lkufxcNks5sJNuAgaJpZM4OGBWL>
> .
>

2017-07-03 07:11 UTC, WellerQu commented
@joscha Yes, you are right. I forgot it. It works now. Thanks.

2017-09-28 07:57 UTC, janusch commented
@joscha I somehow cannot get extract styles to work with extending the config based on your example above. Could you expand on your example, or show a whole webpack config.? How do you get the env check into the webpack config when in "extending mode"?
when i run `build-storybook` there are no stylesheets in the output dir, nor is it added to index.html or iframe.html. 
Can you see any oddities or tell me what I am missing? 

 
```
const path = require('path');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

const extractCSS = new ExtractTextPlugin({
  filename: '../build/static/[name].css',
  allChunks: true,
  ignoreOrder: true,
});

module.exports = {
  module: {
    rules: [
      {
        test: /\.md$/,
        use: 'raw-loader',
      },
      {
        test: /\.(jpg|png)$/,
        use: "file-loader"
      },
      {
        test: /\.css$/,
        include: path.resolve(__dirname, '../src/'),
        exclude: path.resolve(__dirname, '../node_modules/'),
        use: extractCSS.extract({
          fallback: 'style-loader',
          use: [
            {
              loader: 'css-loader',
              options: {
                importLoaders: 1,
                modules: true
              },
            },
            {
              loader: 'postcss-loader',
              options: {
                plugins: function(loader) {
                  return [require('autoprefixer')];
                },
              },
            },
          ],
        }),
      },
    ],
  },
  plugins: [
    extractCSS
  ],
};
```

2017-09-28 12:44 UTC, ndelangen commented
@janusch Would you be able to try the 3.3 alpha release?

We have changed the way entry points are added there, and the issue you're having should be resolved. could you check it out?

2017-09-29 08:49 UTC, janusch commented
@ndelangen Hey, thank you for getting back to me that quickly!
I have just run `build-storybook` with `extract-text-webpack-plugin` and it does now successfully create, copy and include the `preview.css` file.

However, there is another error related to webpack now. Maybe that is due to some other breaking change? It was the first issue in storybook that refers to the same error: https://github.com/storybook-eol/storybook-addons/issues/1 `TypeError: Cannot read property 'emit' of null
    at emitAddReadme` 
I am using the `storybook-readme` addon.

One more little thing is that as soon as I am wrapping the webpack config object in a function returning the object, to get the `env` var, storybook is changing from extended mode to full-control mode. Is there another way to work with an extended config and still make use of `env` for `production` `development`, etc. differentiation?

Thank you for working so hard on storybook, it is really becoming a complex product, with a lot of great features!

2017-09-29 12:40 UTC, janusch commented
> One more little thing is that as soon as I am wrapping the webpack config object in a function returning the object, to get the env var, storybook is changing from extended mode to full-control mode. Is there another way to work with an extended config and still make use of env for production development, etc. differentiation?

this one I got resolved!

I am still having the 'emit' error described above. I am running the latest version of the package. `storybook-readme@3.0.6`

Please let me know, if I should test something else, looking forward to get the latest alpha into a stable build asap.

2017-09-29 12:53 UTC, janusch commented
I got the remaining issues fixed. Just had to upgrade everything else to 3.3.0-alpha.0 as well.

Thank you for the help, storybook rocks!

2017-10-03 18:51 UTC, bsr203 commented
sorry I am bit lost as first time using storybook. Do I need a custom webpack conf to load `css`. I have an app based on CRA, and in `stories/index.js`, I am importing the main css file as `import '../index.css';`. I don't see any style applied. 

Uses "@storybook/react": "^3.2.12".

Do I need to use `3.3.0-alpha.0`? I could not see any html file where I can load css. I saw in some older code there was a header html file for customization, but didn't create any with my CRA based app.

thanks for any help.

2017-10-05 15:51 UTC, shahankit commented
@shilman  Same issue as @bsr203. I'm using full control mode and I could not find any plugin in default config passed so I added new config using `config.plugins.push(new ExtractTextPlugin('component-styles.[contenthash].css'));` and also update `/\.css$/` to `ExtractTextPlugin.extract`.