Svelte examples in the documentation
storybookjs/storybook pull request #13664
Opened 2021-01-17 13:35 UTC by j3rem1e

Issue:

## What I did

Updated the documentation to includes Svelte snippets

## How to test

- Is this testable with Jest or Chromatic screenshots?
- Does this need a new example in the kitchen sink apps?
- Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

2021-01-17 16:56 UTC, jonniebigodes commented
@j3rem1e thank you very much for the time and effort you put into this and get the Svelte examples included in the documentation. Let me take a look and see if everything is ok and we'll get this merged. Do you mind waiting a bit? 


Stay safe

2021-01-21 16:50 UTC, jonniebigodes requested changes
@j3rem1e first and foremost thank you for the time and effort you put into the pull request. This is really great. I left some items that require attention and once you've addressed this we should be able to merge this and get svelte snippets into the documentation. 

Let me know.

Stay safe

2021-01-21 17:26 UTC, j3rem1e commented on docs/writing-docs/doc-blocks.md
> +    'svelte/button-component-with-proptypes.js.mdx',
oh my bad. I had rebased my PR but failed to merge it apparently.. I will fix it

2021-01-21 18:21 UTC, j3rem1e commented on docs/snippets/svelte/button-group-story.js.mdx
> +  orientation: 'horizontal',
what do you mean by 'there is an error in the console ?' I don't know where to look at :)

This code come from the react example, but you're right, it's not good.

2021-01-22 03:42 UTC, shilman approved these changes
❤️ thank you @j3rem1e !

2021-01-22 03:44 UTC, merged