fix: Fail on transpilation errors
storybookjs/storybook pull request #1372
Opened 2017-06-28 10:57 UTC by joscha

Currently, storybook does not exit non-zero when there are errors in the pipeline, e.g. we are using TypeScript with `ts-loader` and a type error that fails tsc does not make storybook exit non-zero even though the transpilation failed.

Issue:

## What I did

## How to test

2017-06-28 11:03 UTC, shilman requested changes

2017-06-28 11:03 UTC, shilman commented on app/react/src/server/build.js
> +  if (err || stats.hasErrors()) {
```
if(err || stats.hasErrors()) {
  const errors = err ? [err] : stats.toJson().errors
  errors.forEach(...)
  process.exit(1)
}
```

2017-06-28 11:08 UTC, joscha commented on app/react/src/server/build.js
> +  if (err || stats.hasErrors()) {
that would not print the stats errors if there is a "normal" error - is that deliberate?

2017-06-28 11:11 UTC, shilman commented on app/react/src/server/build.js
> +  if (err || stats.hasErrors()) {
sorry, main point is that i think it should just be a single if statement

2017-06-28 11:19 UTC, joscha commented on app/react/src/server/build.js
> +  if (err || stats.hasErrors()) {
got it, changes in 9c57ae0

2017-06-28 11:26 UTC, shilman approved these changes

2017-06-28 11:55 UTC, merged

2017-06-28 12:54 UTC, joscha commented
Just tested `3.1.7`, works like a charm:

```
@storybook/react v3.1.7

=> Loading custom addons config.
=> Loading custom webpack config (extending mode).
Building storybook ...
ts-loader: Using typescript@2.3.4 and /Users/joscha/Development/canva/web/tsconfig.ts-loader.json
Failed to build the storybook
./src/pages/editor/publish/website/website_form_ui.tsx
(20,2): error TS2345: Argument of type 'typeof WebsiteFormUI' is not assignable to parameter of type 'string[]'.
  Property 'find' is missing in type 'typeof WebsiteFormUI'.
./src/pages/editor/publish/website/stories/website_form_ui.stories.tsx
(10,7): error TS2605: JSX element type 'WebsiteFormUI' is not a constructor function for JSX elements.
  Types of property 'setState' are incompatible.
    Type '{ <K extends never>(f: (prevState: void, props: WebsiteFormUIProps) => Pick<void, K>, callback?: (() => any) | undefined): void; <K extends never>(state: Pick<void, K>, callback?: (() => any) | undefined): void; }' is not assignable to type '{ <K extends never>(f: (prevState: {}, props: any) => Pick<{}, K>, callback?: (() => any) | undefined): void; <K extends never>(state: Pick<{}, K>, callback?: (() => any) | undefined): void; }'.
      Types of parameters 'f' and 'f' are incompatible.
        Type '(prevState: {}, props: any) => Pick<{}, any>' is not assignable to type '(prevState: void, props: WebsiteFormUIProps) => Pick<void, any>'.
          Types of parameters 'prevState' and 'prevState' are incompatible.
            Type 'void' is not assignable to type '{}'.
./src/pages/editor/publish/website/stories/website_form_ui.stories.tsx
(13,7): error TS2605: JSX element type 'WebsiteFormUI' is not a constructor function for JSX elements.
./src/pages/editor/publish/website/stories/website_form_ui.stories.tsx
(16,7): error TS2605: JSX element type 'WebsiteFormUI' is not a constructor function for JSX elements.
error Command failed with exit code 1.
```

2017-07-25 12:54 UTC, mrmartineau commented
@joscha @shilman I'm not sure, but does this change affect #1402? `storybook-build` does not work for quite a few people since version 3.1.7. Any thoughts?

2017-07-25 13:20 UTC, joscha commented
@mrmartineau it could have been a hidden issue before, if the error was swallowed and never printed and also not changed the exit code. The changes in this PR would pick up such a hidden problem.