Fix for #1305. Updated PropVal.js to pass its props to child elements in case of arrays and objects.
storybookjs/storybook pull request #1374
Opened 2017-06-28 12:37 UTC by Li0liQ

Issue: https://github.com/storybooks/storybook/issues/1305

## What I did

Updated PropVal.js to pass its props to child elements in case of arrays and objects.

## How to test

Render a story using `addWithInfo` with a component that receives an array or an object as a prop. Open console to verify you no longer receive errors due to properties validation for PropVal component.

2017-06-28 14:13 UTC, Li0liQ commented
Making eslint happy makes codebeat unhappy.
Should we say that `previewArray` and `previewObject` are functional react components, add prop types  validation for them and start passing all the arguments as a single `props` argument?

2017-08-25 22:09 UTC, ndelangen reviewed
@shilman @UsulPro Can you verify this PR is still valid considering #1501 ?

2017-08-26 15:31 UTC, UsulPro commented
I'd prefer to completely change our approach for source generation.
We discuss possible solution in #1602

2017-10-30 15:26 UTC, danielduan commented
This seems like a good bug fix that we should be merging into master? Doesn't seem like our Info refactor is gonna happen for 3.3.

2017-10-30 15:26 UTC, danielduan approved these changes

2017-11-15 01:18 UTC, Hypnosphi requested changes

2017-11-15 01:18 UTC, Hypnosphi commented on addons/info/src/components/PropVal.js
> +previewArray.propTypes = {
`previewArray` is never rendered as a component, it's only called as a function. So looks like those propTypes aren't really checked at any point. You should either remove them, or capitalize the name (`PreviewArray`) and replace `previewArray(props)` below with `<PreviewArray {...props} />`.

If you decide to do the latter, please note that `val` should rather be `PropTypes.array`, and don't disable all of the eslint rules — only the particular ones (`// eslint-disable react/forbid-prop-types`)

2017-12-08 16:12 UTC, danielduan commented
Gonna close this PR due to inactivity. Feel free to ping us if you'd like to keep working on it.

2017-12-08 16:13 UTC, closed without merging