Allow falsey default args
storybookjs/storybook pull request #13911
Opened 2021-02-15 05:14 UTC by tmeasday

Issue: #12767

## What I did

Check if default value is `undefined`, rather than falsey before excluding it.

## How to test

- Is this testable with Jest or Chromatic screenshots?

Yes, see test

- Does this need a new example in the kitchen sink apps? 

I think probably not. I don't think these things are picked up by chromatic anyway so don't end up being very useful to have edge cases, unless they are hard to reproduce.

2021-02-15 06:17 UTC, shilman approved these changes
💯

2021-02-15 06:23 UTC, shilman requested changes
@tmeasday can you take a look at the chromatic changes? probably ok but i'd like a second opinion

2021-02-15 23:44 UTC, tmeasday commented
@shilman -- I approved the first two changes -- this example was a component with a `children` prop with default value `null`. I think given current semantics it is correct that that prop should get passed to the component with `null` value [1]

I'm not sure about the other 8 changes -- are they present on `next`?


[1] Arguably we shouldn't be setting args to the default value from the component? That might be a discussion for another time.

2021-02-16 00:22 UTC, shilman commented
@tmeasday I accepted a few more changes (zoom changes are test flake, parameters change is from another PR that slipped in). The remaining ones are all due to this PR I think.

2021-02-17 09:12 UTC, tmeasday commented
@shilman OK those stories highlighted a bug that was being generated here, I think the examples I added in the other PR (https://github.com/storybookjs/storybook/pull/13919) would have made that more obvious.

2021-02-18 04:48 UTC, tmeasday commented
@shilman I am going to merge this into https://github.com/storybookjs/storybook/pull/13919

There's too many overlapping concerns, it's silly to resolve them separately

2021-02-18 05:12 UTC, closed without merging