CLI: Don't allow root directory as static dir
storybookjs/storybook pull request #14068
Opened 2021-02-26 15:58 UTC by oscard0m

Issue: https://github.com/storybookjs/storybook/issues/13860

## Context
When a user builds `storybook` in `standalone` mode, exists the possibility to provide the root directory (`/`) as one of the static directories to copy from (probably by mistake). This ends up trying to copy the whole root directory which is an unexpected behavior.

## What I did
- When building statics standalone throws an error if the `staticDir` option provided contains the root directory: `/`.
- Added test coverage for invalid `staticDir` value
	- when it's root directory `/`

## How to test

- Is this testable with Jest or Chromatic screenshots? ✅

- Does this need a new example in the kitchen sink apps? I don't think so but since I'm lacking context on what's the scope of the examples I would like the feedback from a maintainer here.

- Does this need an update to the documentation? Checking existing `standalone.md` I don't think so but if you think this is an opportunity to add a disclaimer there, this PR can be used for it 😄

2021-02-26 21:10 UTC, shilman requested changes
minor changes, otherwise LGTM!

2021-02-26 21:10 UTC, shilman commented on lib/core-server/src/core-presets.test.ts
> +    beforeEach(() => {
do we need these? it's already happening in the outer describe. also can remove from the above tests

2021-03-02 09:52 UTC, ghengeveld commented
Let's also disallow `''` as static dir while we're at it.

2021-03-16 01:29 UTC, oscard0m commented
Applied minor changes @shilman

2021-03-18 10:27 UTC, shilman approved these changes
Looking good. I think this variable should probably be renamed from `staticDir` to `staticDirs` because it's an array, but that's probably better for another PR. Thanks for fixing this!

2021-03-18 10:27 UTC, merged

2021-05-05 18:49 UTC, oscard0m commented
> Looking good. I think this variable should probably be renamed from `staticDir` to `staticDirs` because it's an array, but that's probably better for another PR. Thanks for fixing this!

@shilman I owed you this https://github.com/storybookjs/storybook/pull/14819#issue-630821354 😃