dont set z-index on "Show code" button
storybookjs/storybook pull request #14074
Opened 2021-02-26 20:57 UTC by kylemh

Issue:

## What I did

Removed set z-index from the div that wraps the "Show code" button in a story preview block. I don't wanna get into a fight with z-indeces anywhere - least of all within Storybook. My modals are rendered via portals which should be last in the DOM beating any z indeces; however, in Storybook, those portals are rendered within the preview block's iFrame, meaning they aren't rendered last.

### Before

![Screen Shot 2021-02-26 at 12 55 44 PM](https://user-images.githubusercontent.com/9523719/109354027-07d48c00-7832-11eb-82d3-81262bff057b.png)

### After

![Screen Shot 2021-02-26 at 12 55 32 PM](https://user-images.githubusercontent.com/9523719/109354050-0f943080-7832-11eb-9300-cc1bf0015c8e.png)

2021-02-27 12:42 UTC, shilman requested changes
Looks like zIndex was added for this:

https://github.com/storybookjs/storybook/pull/11502#issuecomment-663774680

Can you investigate?

2021-02-27 16:23 UTC, kylemh commented
@domyen that video is 404ing from Loom. Do you remember the problem?

2021-02-27 16:25 UTC, kylemh commented
@ndelangen so I am using portals, but they render at the bottom of the body within the iFrame, meaning the "Show code" button appears after it in the page's DOM, so that's not a solution.

2021-07-07 23:08 UTC, MichaelArestad commented
Right. I did a few tests and I can confirm that the actions can't be used in some scenarios without the add `z-index: 1`. It looks like there is a `div` with the class`os-padding` that has a `z-index: 1` which makes those actions inaccessible when their `z-index` is removed.

I tried changing the `os-padding` `z-index` to `0` and that seemed to work, but may break something else. I'm not familiar with what is adding those styles, but I think it has something to do with scrollbars. @kylemh perhaps investigating that route further could prove fruitful?

2021-07-08 00:39 UTC, kylemh commented
@MichaelArestad zIndex 0 solved my issue. Committed here so you can see the result in terms of Storybook (rather than just my Storybook usage).

2021-07-08 20:47 UTC, MichaelArestad commented
@kylemh Right. I tried that yesterday. You can see [on the Docs/DocsPage story in the published storybook](https://5a375b97f4b14f0020b0cda3-tqlmlclwkk.chromatic.com/?path=/story/docs-docspage--with-subtitle) that the "Code" button is no longer clickable.

2021-08-16 19:13 UTC, MichaelArestad commented
Because this is breaking functionality and seems to be inactive, I'm going to close this PR. If you would like to try another iteration, I would be happy to reopen it. Thank you for contributing.

2021-08-16 19:13 UTC, closed without merging