Implement filtering on story-level
storybookjs/storybook pull request #1432
Opened 2017-07-08 07:19 UTC by jhurley23

Issue:
https://github.com/storybooks/storybook/issues/109

## What I did
I edited the `storyFilter()` function to enable filtering on the story-level.
If the "fuzzysearch" matches a storiesOf() level story it will return all stories that are matched.

If the fuzzysearch matches an individual story, it will just return that story.

It will leave the currently active story unfiltered

## How to test

See the additions to `filters.test.js` for examples of it in action.

2017-07-08 07:22 UTC, shilman commented
Nice tests--great work!!!

2017-07-08 07:49 UTC, igor-dv commented on lib/ui/src/modules/ui/libs/filters.js
> +    const matchedStories = kindInfo.stories.filter(story => fuzzysearch(needle, story));
IMO you should add the lowercasing here (like for the `kind` check, looks like `fuzzysearch` already do `===`, so it maybe redundant) And add tests for this usecase.

2017-07-08 07:59 UTC, igor-dv requested changes
Just checked the fork and now I'm confident that without lowercasing it won't actually work.

2017-07-08 08:51 UTC, ndelangen commented
@shilman did you rebase this on the release branch? I tested this but it's not working as expected I think.

2017-07-08 09:09 UTC, ndelangen commented on lib/ui/src/modules/ui/libs/filters.js
> +    const matchedStories = kindInfo.stories.filter(story => fuzzysearch(needle, story));
Fuzzy search takes care of that

2017-07-08 09:18 UTC, igor-dv commented on lib/ui/src/modules/ui/libs/filters.js
> +    const matchedStories = kindInfo.stories.filter(story => fuzzysearch(needle, story));
doesn't look so - https://github.com/bevacqua/fuzzysearch/blob/master/index.js

2017-07-08 11:11 UTC, jhurley23 commented
@ndelangen I can confirm that @igor-dv is correct on the case issue.  When filtering at individual story level converting to lower case is required.  Its not covered by fuzzysearch.

As mentioned by some users this fork does not seem be working correctly.  Any advice on how to get this working is greatly appreciated. 

I have it working on local after `npm link`ing a local copy of the repo.
I've attached a GIF demo below:

![filteringexample](https://user-images.githubusercontent.com/11878516/27984791-e94c4584-6421-11e7-8325-0a7428ea3d26.gif)

2017-07-08 11:30 UTC, igor-dv approved these changes
Cool.

2017-07-08 11:33 UTC, igor-dv commented
Checked it in `lib/ui/example`. There is indeed some problem with `cra-kitchen-sink` linking.. 
Can it be related to the `*.alpha` things ?

2017-07-08 13:22 UTC, jhurley23 commented
This may need some further work before it's ready.  My feeling is that it would be better if the directories expanded to show remaining stories after filtering.  Currently it seems hard to predict if react-treebeard will display a result as expanded or not after filtering.  I'll look into it further.

2017-07-08 15:01 UTC, shilman commented
@jhurley23 @igor-dv @ndelangen can confirm that the reason it's working with manual linking but not with `bootstrap` is due to a versioning problem. I've documented that in an issue.

https://github.com/storybooks/storybook/issues/1433

If you update the `package.json` with the following versions and re-run bootstrap, then @jhurley23 's changes show up in `cra-kitchen-sink`. I'm updating the `release/3.2` branch now.

```
  "devDependencies": {
    "@storybook/addon-actions": "^3.0.0",
    "@storybook/addon-centered": "^3.0.0",
    "@storybook/addon-events": "^3.0.0",
    "@storybook/addon-knobs": "3.2.0-alpha.7",
    "@storybook/addon-info": "^3.0.0",
    "@storybook/addon-links": "3.2.0-alpha.5",
    "@storybook/addon-notes": "3.2.0-alpha.5",
    "@storybook/addon-options": "3.2.0-alpha.5",
    "@storybook/addon-storyshots": "3.2.0-alpha",
    "@storybook/addons": "^3.0.0",
    "@storybook/react": "3.2.0-alpha.7",
    "react-scripts": "1.0.1"
  },
```

2017-07-08 18:13 UTC, shilman commented
@jhurley23 agree with you on the expansion behavior. may take some work to get this right!

2017-07-08 21:15 UTC, ndelangen commented
My patch on lerna would fix that 😭

2017-07-15 20:02 UTC, shilman commented
@jhurley23 @igor-dv would love to get this in for 3.2. Should I merge as is and we handle the hierarchy expansion behavior in a separate PR (preferably on a branch inside this repo?) Or do you want to try to add that before I merge?

2017-07-16 05:42 UTC, igor-dv commented
Let's think if it's a blocker ? I prefer to merge this one, and to implement the expansion in separate PR. 
@jhurley23 , did you already start working on it ?

2017-07-16 15:18 UTC, merged

2017-07-16 15:19 UTC, shilman commented
@jhurley23 @igor-dv OK i've merged this one in. I don't think this is a blocker, but it would be really awesome to get it fixed fully as part of the 3.2 release!