feat: adding transparency support
storybookjs/storybook pull request #14439
Opened 2021-04-01 13:39 UTC by bart-krakowski

## What I did
I added a transparency grid (https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjwfs5goq3Bgox6EKk4LNxHLAyHKixVyN8pQ&usqp=CAU) to the ColorItem component.
I think the display of semi-transparent colors will be easier to read from now on:
![Screenshot 2021-04-01 at 15 38 43](https://user-images.githubusercontent.com/48633090/113302448-5927dd80-9300-11eb-8ec7-c4c278c4b302.png)

## How to test

- Is this testable with Jest or Chromatic screenshots?
- Does this need a new example in the kitchen sink apps?
- Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

2021-07-05 11:43 UTC, ndelangen commented
I really like this! @MichaelArestad WDYT?

2021-07-07 22:49 UTC, MichaelArestad commented
This is a cool idea! Nice work @bart-krakowski 

1. Should this be optional?
2. I would apply it to the container wrapping all of the color swatches so the pattern is seamless between colors. There is a transparent border on this container, but I think it would be a good idea to make this border a solid color.
3. I find the checker pattern nice, but a bit heavy. Perhaps something with a less grey would be better to make it easier to see the unaltered color. I tried the following:

```css
background-image: repeating-linear-gradient(-45deg, #ccc, #ccc 1px, #fff 1px, #fff 16px)
```

Which looks like this:
<img width="598" alt="image" src="https://user-images.githubusercontent.com/1123119/124837942-13a02f80-df43-11eb-8d41-05a4f4281c81.png">


What do you think?

2021-07-08 09:50 UTC, ndelangen commented
@bart-krakowski do you think you could make this adjustment?

2021-07-08 10:11 UTC, bart-krakowski commented
@ndelangen, yes, I will introduce it soon.

2021-07-08 16:19 UTC, shilman commented
@bart-krakowski this is awesome!! however, there is some weirdness in the chromatic build. can you please take a look? https://www.chromatic.com/build?appId=5a375b97f4b14f0020b0cda3&number=22752

2021-07-08 17:41 UTC, bart-krakowski commented
@shilman, I see it works better now :) 
https://www.chromatic.com/build?appId=5a375b97f4b14f0020b0cda3&number=22755

2021-07-12 15:42 UTC, shilman approved these changes
Great job @bart-krakowski @MichaelArestad 💯

2021-07-12 15:43 UTC, shilman requested changes
Hmm @bart-krakowski is there any way to achieve this without needing to add an extra prop? 🤔

2021-07-12 18:36 UTC, bart-krakowski commented
> Hmm @bart-krakowski can we add this without adding an extra prop? 🤔



> Hmm @bart-krakowski is there any way to achieve this without needing to add an extra prop? 🤔

2021-07-12 18:37 UTC, bart-krakowski commented
> Hmm @bart-krakowski is there any way to achieve this without needing to add an extra prop? 🤔

OK, I have removed the `isTransparent` prop.

2021-07-13 20:19 UTC, MichaelArestad requested changes

2021-07-13 20:19 UTC, MichaelArestad commented on lib/components/src/blocks/ColorPalette.tsx
>  }));
I would also add `background-clip: padding-box;` to prevent the background from showing under the transparent border.

2021-07-14 04:11 UTC, shilman approved these changes
This is so awesome. Thanks for all the fixes @bart-krakowski 💯

2021-07-14 04:11 UTC, merged