feat(12307): add full reload listening to server-side-events
storybookjs/storybook pull request #14445
Opened 2021-04-01 19:50 UTC by brion-fuller

Issue:

Web components cannot be hot reloaded as customElement.define can only be called once per page with an unique string. This has been on the users to add to their config file. Now this is available for free.

What I did
I hooked into server-sent events for webpack HMR and listen for the built event in which I trigger a page reload.

How to test
Is this testable with Jest or Chromatic screenshots? no
Does this need a new example in the kitchen sink apps? no
Does this need an update to the documentation? yes

2021-04-08 14:38 UTC, shilman requested changes

2021-04-08 14:38 UTC, shilman commented on examples/web-components-kitchen-sink/.storybook/main.js
> +    builder: 'webpack5',
AFAIK we can't use this in the monorepo

2021-04-08 14:44 UTC, shilman commented on examples/web-components-kitchen-sink/.storybook/main.js
> +    builder: 'webpack5',
```suggestion
    builder: 'webpack4',
```

2021-04-09 01:46 UTC, shilman approved these changes
LGTM, thanks @brion-fuller!! @gaetanmaisse the CI results looks like an intermittent NPM failure so I'm merging anyway.

2021-04-09 01:47 UTC, merged

2021-05-07 23:25 UTC, steveblue commented
Thank you @brion-fuller confirmed this works with vanilla custom elements.