Refactoring of `addon-info`
storybookjs/storybook pull request #1452
Opened 2017-07-11 21:40 UTC by UsulPro

Issue: https://github.com/storybooks/storybook/issues/1147#issuecomment-306409320

since we're slowly moving from .addWithX addons to more wise solutions, we need an appropriate version of the addon

## What I did

1. Added `withInfo()` function.

accessible via:
```js
import { withInfo } from '@storybook/addon-info';
```

API:

```js
infoFn(context => { /* return <Story /> */ }) = withInfo(storyInfo, options)
```

Example:

```js
.add('with new info', withInfo('info addon')(context =>
      <div>
        click the <InfoButton /> label in top right for info about "{context.story}"
      </div>
))
```

2 Added deprecation warning to `.addWithInfo`

3 Added examples to cra-kitchen-sink:

- new `withInfo()` API

- `withInfo()` and `addonNotes()` composition

## How to test

- run cra-kitchen-sink 

- run tests

2017-07-12 14:17 UTC, shilman requested changes
Thanks so much for doing this. I think it will help Storybook's addon ecosystem a lot!

I requested some changes around deprecation.

I also have a question. Is the `context` argument to stories a convention in Storybook that `addon-info` was stripping out? Or is it something that we are adding recently?

2017-07-12 14:17 UTC, shilman commented on addons/info/src/index.js
> +    return this.add(storyName, warning(withInfo(info, _options)(storyFn)));
Let's just deprecate `addWithInfo`?

2017-07-12 14:22 UTC, shilman commented
@alexandrebodin @ndelangen @tmeasday mind reviewing this? it's a huge step towards cleaning up the addon ecosystem, but let's make sure we all agree on the specifics before we charge ahead!

2017-07-12 17:26 UTC, UsulPro commented
@shilman Yes, passing `context` to `storyFn()` (and therefore to `decoratorFn()`) is existing API, it was introduced already in v1.31.0. So I made a `withInfo()` with a support of this API as well.

I tried to use `util-deprecate` it's convenient but I could not get it to behave as I need for several reasons (not critical in general):

- It does not support passing arguments into warning messages while I wanted to show the specified story and storyKind in the notification

- If I wrap `addWithInfo` with `util-deprecate` it'll change the name of the function so it will not be available as `storiesOf().addWithInfo` (possible could be a workaround for that though). And I wanted the warning to be shown only when you select the story, not in the beginning.

Do you think that we should intend to use `util-deprecate` in all cases?

2017-07-12 17:26 UTC, UsulPro commented on addons/info/src/index.js
> +const showWaring = deprecate();
OH! Sure!!!

2017-07-12 17:28 UTC, UsulPro commented on addons/info/src/index.js
> +    return this.add(storyName, warning(withInfo(info, _options)(storyFn)));
see my answer in a comment below, please!

2017-07-12 18:53 UTC, shilman commented
@UsulPro personal preference would be to just use `util-deprecate` across the board and keep the code size down, although you won't be able to access the arguments in the message.

As for changing the name of the function, it shouldn't be a problem:
```
export default {
  addWithInfo: deprecate(deprecatedAddWtihInfo, message),
  ...
}
```

2017-07-13 04:11 UTC, tmeasday commented
Looks great @UsulPro, great work!

@shilman what specifics about the addon ecosystem were you concerned about?

I think exporting a "decorator" like this `withInfo` is the best way forward that fits with the current design. One minor thing: should we use [recompose's](https://github.com/acdlite/recompose) `compose` for combining decorators in our examples? It might be slightly simpler and easier to follow?

Also I noticed that the knobs example isn't working on this branch. Is this a known problem?

2017-07-13 04:11 UTC, tmeasday approved these changes

2017-07-13 04:30 UTC, shilman commented
@tmeasday I'm only concerned insofar as changes to the API are expensive and I want to make sure we're all bought in. I think we're in total agreement that `withX` decorators is the way to go, but I just want to make sure.

2017-07-13 17:38 UTC, shilman approved these changes

2017-07-13 17:40 UTC, shilman commented
@tmeasday Good catch on the knobs. Tracking here: https://github.com/storybooks/storybook/issues/1464

2017-07-13 17:41 UTC, shilman commented
@UsulPro does the change to the default props change behavior in meaningful ways that could break things for existing users?

2017-07-13 17:56 UTC, shilman commented
@UsulPro CI is breaking. do you mind fixing this and then I'll merge:
```
Summary of all failing tests
 FAIL  addons/info/src/index.test.js
  ● addon Info › should render with missed info
    No story defining function has been specified
      
      at addInfo (addons/info/src/index.js:98:91)
      at Object.<anonymous> (addons/info/src/index.test.js:53:19)
          at Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)
```

2017-07-13 19:01 UTC, shilman requested changes

2017-07-13 19:01 UTC, shilman commented on addons/info/src/components/PropVal.js
> +  maxPropObjectKeys: 3,
Default values should be "show everything"

2017-07-13 19:52 UTC, shilman approved these changes

2017-07-13 19:52 UTC, merged