Fix: only show addons in mobile menu if docsOnly is false
storybookjs/storybook pull request #14810
Opened 2021-05-05 01:06 UTC by Tomastomaslol

Issue: https://github.com/storybookjs/storybook/issues/13547

## What I did
* Added prop `docsOnly` to  `Mobile` component
* Only render menu option `Addons` if `docsOnly` is `false`

## How to test
https://user-images.githubusercontent.com/1872246/117087024-a4b32880-ad91-11eb-9d90-3f71bee18597.mp4

2021-05-06 09:59 UTC, ndelangen requested changes
Really great improvement, would just request 1 addition to this:
Can you add a story for the Mobile layout demonstrating this capability?

2021-05-06 09:59 UTC, ndelangen commented on lib/ui/src/components/layout/mobile.tsx
> +          {viewMode && !docsOnly ? (
This new variant, should get a story

2021-05-11 00:53 UTC, Tomastomaslol commented
Hi @ndelangen! I added a new story for the docs only scenario. Please let me know if there is something I can do for you.

2021-05-11 07:25 UTC, ndelangen approved these changes

2021-05-11 07:26 UTC, merged