Storyshots: framework option should override package dependency check
storybookjs/storybook pull request #1482
Opened 2017-07-18 12:13 UTC by ktj

Issue:
https://github.com/elderfo/react-native-storybook-loader/issues/26
## What I did
In storyshots addon I modified the framework check to make sure framework option overrides dependency check.

## How to test
Reproduction project: https://github.com/ktj/storyshots-rp
```
yarn
yarn test
```
-> tests fail

remove line 8 form package json -> tests work

2017-07-18 20:49 UTC, ndelangen approved these changes
I haven't tested, but I think this is a good idea. What about you @tmeasday

2017-07-22 07:24 UTC, shilman approved these changes
LGTM (but didn't test)!

2017-07-22 11:10 UTC, tmeasday requested changes
Makes sense to me apart from the package.json change.

2017-07-22 11:10 UTC, tmeasday commented on examples/react-native-vanilla/package.json
> +    "@storybook/react": "file:../../app/react",
Are you just adding this line to prove that the fix works, or does it make sense to have it for the RNV app?

2017-07-22 13:47 UTC, ktj commented on examples/react-native-vanilla/package.json
> +    "@storybook/react": "file:../../app/react",
Just to prove it works

2017-07-22 13:55 UTC, tmeasday commented on examples/react-native-vanilla/package.json
> +    "@storybook/react": "file:../../app/react",
Ok can we drop it then? Thanks!

2017-07-23 22:53 UTC, ndelangen commented on examples/react-native-vanilla/package.json
> +    "@storybook/react": "file:../../app/react",
Sounds like this will be super easy to clear up and merge?

2017-07-24 05:00 UTC, merged

2017-07-24 05:00 UTC, tmeasday commented
Done, Thanks @ktj !