(documentation) Add a "troubleshooting" section to typescript.md
storybookjs/storybook pull request #14965
Opened 2021-05-17 22:57 UTC by Offirmo

Hi, I had trouble setting up TypeScript support and had to search a lot to make it work.

This should help the next one!

Issue:

## What I did

Added documentation

## How to test

Not needed

2021-05-18 10:03 UTC, ndelangen approved these changes

2021-05-27 22:53 UTC, jonniebigodes commented
@Offirmo sorry for not addressing this sooner. I'll take a look at it tomorrow and work with you on any proposed changes.

Stay safe

2021-06-01 21:35 UTC, jonniebigodes requested changes
@Offirmo left a couple of items that need a bit of polish, let me know once you address them and we'll go from there.

Stay safe

2021-06-01 21:35 UTC, jonniebigodes commented on docs/configure/typescript.md
> +Storybook has built-in Typescript support, so your Typescript project should work with zero configuration needed. The config files from `.storybook` can be in TypeScript as well.
@Offirmo if you could revert back to what's currently documented we'd appreciate it. The reasoning behind this is that in the first sentence we're mentioning that Storybook as a whole has Typescript support, despite the config files being created with `.js` extension.

2021-08-18 19:19 UTC, jonniebigodes commented
@Offirmo just a friendly reminder if you're willing to work on this pull request. So that the changes you're introducing will help not only you but the rest of the community.

Let me know and we'll go from there. Sounds good?

Stay safe

2021-11-29 21:09 UTC, closed without merging