Update contributor docs
storybookjs/storybook pull request #15058
Opened 2021-05-27 00:52 UTC by domyen

## What I did
Updated contributor docs for brevity and clarity.

## How to test

- Is this testable with Jest or Chromatic screenshots? No
- Does this need a new example in the kitchen sink apps? No
- Does this need an update to the documentation? No

If your answer is yes to any of these, please make sure to include it in your PR.

2021-05-27 02:48 UTC, shilman approved these changes
Great changes! A couple tweaks below

2021-05-27 02:48 UTC, shilman commented on docs/contribute/code.md
> +## Run Storybook utilities
```suggestion
## Run tests & examples
```

2021-05-27 02:48 UTC, shilman commented on docs/contribute/code.md
> +If your contribution focuses on a bugfix and you want it featured in the next stable release, mention it in the pull request description. We'll try to get it in if it appears to be non-disruptive and
```suggestion
If your contribution focuses on a bugfix and you want it featured in the next stable release, mention it in the pull request description. We'll try to patch it in if it appears to be non-disruptive and fixes a critical bug.
```

2021-05-27 22:33 UTC, domyen commented
@jonniebigodes ready for review when you get a chance

2021-05-27 22:41 UTC, jonniebigodes requested changes
@domyen one small item that needs to be updated and this should be good to go.

2021-05-27 22:41 UTC, jonniebigodes commented on docs/contribute/new-snippets.md
> +Storybook maintains code snippets for a [variety of frameworks](./../api/frameworks-feature-support). We try to keep them up to date as framework APIs evolve. But it's tricky to keep track of every A
@domyen when you're able, add the `.md` extension to this link, to allow the proper navigation in both GitHub and the website.

2021-05-28 19:14 UTC, jonniebigodes commented on docs/contribute/new-snippets.md
> +Storybook maintains code snippets for a [variety of frameworks](./../api/frameworks-feature-support). We try to keep them up to date as framework APIs evolve. But it's tricky to keep track of every A
Fixed with the latest commit. Marking this as solved

2021-05-28 21:15 UTC, jonniebigodes commented
@domyen looks good to me. Self merging. @winkerVSbecks thanks for catching the broken link.

2021-05-28 21:15 UTC, merged