Fix color controll on reset
storybookjs/storybook pull request #15059
Opened 2021-05-27 04:14 UTC by 88ta

Issue: https://github.com/storybookjs/storybook/issues/14978

## What I did
Fixed a bug where the color control was not initialized when the reset button was pressed.

## How to test

- Is this testable with Jest or Chromatic screenshots? Yes
- Does this need a new example in the kitchen sink apps? No
- Does this need an update to the documentation? No

![May-27-2021 12-05-18](https://user-images.githubusercontent.com/13187537/119764983-52c37580-beed-11eb-8d9e-3fdd29ad2009.gif)

2021-05-27 05:19 UTC, shilman reviewed
Thank you @88ta! Mind reviewing @ghengeveld @tmeasday ?

2021-05-28 01:29 UTC, tmeasday requested changes
@ghengeveld what do you think about this?

I feel like the "correct" solution to this kind of problem is to lift the state up to the level of the reset button and make the state get cleared when the reset button is pressed. That's probably a bit tricky to implement however for controls.

How is this solved (or is it not solved) for the JSON editor?

2021-05-28 01:29 UTC, tmeasday commented on lib/components/src/controls/Color.tsx
> +  }, [initialValue]);
Should this call `updateValue`?

2021-06-07 13:53 UTC, amartinez62 commented on lib/components/src/controls/Color.tsx
> +  }, [initialValue]);
@ghengeveld

2021-06-08 11:32 UTC, ghengeveld approved these changes
I made some adjustments and I think this is good to go now.

2021-06-08 12:47 UTC, shilman approved these changes
LGTM! 🙏

2021-06-08 13:10 UTC, ghengeveld commented
Build is failing in IE11 due to Acorn not being transpiled. This was fixed before afaik. Merging in `next` which will hopefully fix that.

2021-06-08 13:58 UTC, merged