other: align text and icon in sidebar tree nodes
storybookjs/storybook pull request #15080
Opened 2021-05-28 17:25 UTC by IgorSzyporyn

## What I did

Adjusted the component ui/TreeNode

- added min-height 23px (was 22px, but inferred) to BranchNode & LeafNode to make sure text would align
- removed padding from TypeIcon, adjusted dimensions to match and added +1px to margin right also to adjust

New expression
<img width="221" alt="Screenshot 2021-05-28 at 18 54 51" src="https://user-images.githubusercontent.com/6172338/120020683-5852b580-bfea-11eb-8bcc-b0bce31edc86.png">

2021-05-28 18:23 UTC, IgorSzyporyn commented
e2e test fails - do not think it has anything to do with this PR

<img width="790" alt="Screenshot 2021-05-28 at 20 22 59" src="https://user-images.githubusercontent.com/6172338/120026598-95bb4100-bff2-11eb-98cd-ff212e12e449.png">

2021-05-28 18:34 UTC, yannbf commented
Nice one @IgorSzyporyn! The error in the CI seems to be a yarn berry issue, not related to your changes at all. @gaetanmaisse have you seen this is other PRs?

2021-05-28 19:01 UTC, gaetanmaisse commented
@yannbf you're right it's not related to SB but Yarn, the issue is tracked https://github.com/yarnpkg/berry/issues/2938.

2021-05-29 05:53 UTC, IgorSzyporyn commented
> Nice one @IgorSzyporyn! The error in the CI seems to be a yarn berry issue, not related to your changes at all. @gaetanmaisse have you seen this is other PRs?
> 
> I think the changes ended up misaligning items when they have an arrow, it's quite apparent on [Chromatic](https://www.chromatic.com/test?appId=5a375b97f4b14f0020b0cda3&id=60b12afc2c7d0a0039e6807b):
> ![image](https://user-images.githubusercontent.com/1671563/120028488-0bc0a780-bff5-11eb-87c9-137166bb26bf.png)
> 
> For the inconsistency in the angular chromatic, @ThibaudAV I added a pr in #15081 to fix it

teach me to check this myself - I do not like inconsistency :-)

Thanks @ThibaudAV

2021-06-25 12:16 UTC, shilman commented
@IgorSzyporyn you can see the diffs here by clicking on "details"

<img width="887" alt="other__align_text_and_icon_in_sidebar_tree_nodes_by_IgorSzyporyn_·_Pull_Request__15080_·_storybookjs_storybook" src="https://user-images.githubusercontent.com/488689/123423549-4288de00-d5f2-11eb-9104-8f58fe2b6c91.png">

2021-06-30 05:11 UTC, shilman commented
@darleendenno Yes, I expect that's a discrepancy between the cloud snapshot environment in Chromatic and your local browser?

2021-06-30 16:20 UTC, MichaelArestad requested changes
This is already looking sharper. To make the icons align nicely with parent list items, I might add something like:

`margin-left: 1px` to both `CollapseIcon` and `TypeIcon`.

You may also add a single pixel to the left padding on `BranchNode` and `LeafNode`. I'm not sure. I just did some quick tests using browser tools. Use your best judgement.

Another thing that would be good to test is adding great-grandchildren to the story to ensure this looks good Storybooks with deeply nested items.

2021-06-30 20:05 UTC, IgorSzyporyn commented
> This is already looking sharper. To make the icons align nicely with parent list items, I might add something like:
> 
> `margin-left: 1px` to both `CollapseIcon` and `TypeIcon`.
> 
> You may also add a single pixel to the left padding on `BranchNode` and `LeafNode`. I'm not sure. I just did some quick tests using browser tools. Use your best judgement.
> 
> Another thing that would be good to test is adding great-grandchildren to the story to ensure this looks good Storybooks with deeply nested items.

Will do

2022-01-10 17:05 UTC, closed without merging