Make cra-kitchen-sink test snapshot locale-independent
storybookjs/storybook pull request #1522
Opened 2017-07-25 20:40 UTC by Hypnosphi

2017-07-26 19:05 UTC, danielduan requested changes

2017-07-26 19:05 UTC, danielduan commented on examples/cra-kitchen-sink/src/stories/index.js
> +          My birthday is: {new Date(birthday).toDateString()}
This is still locale dependant unfortunately.

I think the solution would be to keep using `toLocaleDateString` but pass in a locale and a format option.

```
var options = { weekday: 'short', year: 'numeric', month: 'short', day: 'numeric' };
date.toLocaleDateString('en-US', options);
```

or something like this.

2017-07-28 08:02 UTC, ndelangen commented
@Hypnosphi I've previously fixed this in a similar way (see merge conflicts). Thank you for helping out!! If you can find any issues related to this, please let me know or reopen and rebase this PR?

Thank you!

2017-07-28 23:16 UTC, Hypnosphi commented
@ndelangen looks like your change solves the issue only for us europeans =)

2017-07-28 23:19 UTC, Hypnosphi commented
@ndelangen looks like your change solves the issue only for us europeans, people from USA should get error now (I wonder why CI passes though)

2017-07-29 17:14 UTC, shilman approved these changes
LGTM!

2017-07-29 17:14 UTC, merged