Add hrefs to left menu links
storybookjs/storybook pull request #1523
Opened 2017-07-25 21:02 UTC by Hypnosphi

This improves UX by making it possible to open stories in new tab/window, copy links etc.

2017-07-26 00:42 UTC, shilman commented
@igor-dv mind taking a look at this?

2017-07-26 04:48 UTC, igor-dv commented
@Hypnosphi , cool thing, but:

There will be incompatible changes in the left panel structure in upcoming  [3.2 release](https://github.com/storybooks/storybook/pull/1383) , so I think you should branch from the **release/3.2**

2017-07-26 07:18 UTC, igor-dv requested changes
Let's review after the compatibility changes

2017-07-28 08:00 UTC, ndelangen commented
@Hypnosphi Awesome!! Do you think you could resolve the merge conflicts?

2017-07-28 10:35 UTC, Hypnosphi commented
Those changes may be non-trivial to integrate with react-treebeard, but I'd give it a try

2017-07-28 10:43 UTC, ndelangen commented
If you need help, just let me know! If you'd like to join the storybook slack, you can self-invite here: https://now-examples-slackin-nqnzoygycp.now.sh/

2017-07-28 11:46 UTC, igor-dv commented
@Hypnosphi , look at `HeaderDecorator` in `ui/components/left_panel/stories_tree/tree_decorators.js` . There is a `<a>`  tag that you can replace.

2017-07-28 16:12 UTC, Hypnosphi commented
@igor-dv Sure, but I also need to put onclick handler on that link instead of this div: https://github.com/alexcurtis/react-treebeard/blob/master/src/components/decorators.js#L55

2017-07-30 10:02 UTC, igor-dv commented
@Hypnosphi LMK, when it's ready to review.

2017-07-30 12:40 UTC, Hypnosphi commented
@igor-dv I think it is

2017-07-31 10:10 UTC, igor-dv reviewed
LGTM,

The only thing I am not confident about is the final blue/black UI.

![image](https://user-images.githubusercontent.com/7867954/28773299-991ec49c-75f1-11e7-8fc9-9123d048ee2a.png)

1. I think it's too much blue... 
2. IMO making the Component name bold together with a story is a bit confusing..

2017-07-31 10:10 UTC, igor-dv commented on lib/ui/src/modules/ui/components/left_panel/stories_tree/tree_decorators.js
> +      <MenuItem style={containerStyle} onClick={onClick} data-name={node.name}>
is `data-name` only for tests ?

2017-07-31 10:11 UTC, igor-dv approved these changes

2017-07-31 10:25 UTC, Hypnosphi commented on lib/ui/src/modules/ui/components/routed_link.js
> +    const { onClick, href, children, overrideParams, ...restProps } = this.props;
Null is also a value. Try and pass it to some dom element, react warns you (and from version 16 it will silently append it as an attribute)

2017-07-31 10:25 UTC, Hypnosphi commented on lib/ui/src/modules/ui/components/left_panel/stories_tree/tree_decorators.js
> +      <MenuItem style={containerStyle} onClick={onClick} data-name={node.name}>
Basically so

2017-07-31 10:28 UTC, Hypnosphi commented on lib/ui/src/modules/ui/components/theme.js
> +    -apple-system, "BlinkMacSystemFont", ".SFNSText-Regular", "San Francisco", "Roboto",
Well we've discussed in slack in the context of menu items jumping when they go from bold to normal. I can extract it to a separate PR if needed

2017-07-31 10:34 UTC, Hypnosphi commented
Speaking of the "too much blue" part, we need to indicate somehow that a particular menu item is a link. Stories and kinds are, namespaces aren't. At the same time, when some kind is already open, its link should be somehow marked as "active". If we just remove color, it becomes undistinguishable from namespace again

@shilman, what do you think?

2017-07-31 10:34 UTC, Hypnosphi commented on lib/ui/src/modules/ui/components/routed_link.js
> +  return e.button === 0 && !e.altKey && !e.ctrlKey && !e.metaKey && !e.shiftKey;
Will do

2017-07-31 15:51 UTC, igor-dv commented on lib/ui/src/modules/ui/components/routed_link.js
> +    const { onClick, href, children, overrideParams, ...restProps } = this.props;
Crap... those unused props are annoying me..

2017-07-31 21:41 UTC, Hypnosphi commented on lib/ui/src/modules/ui/components/routed_link.js
> +    const { onClick, href, children, overrideParams, ...restProps } = this.props;
plus we need an explicit `href` to make eslint-plugin-jsx-a11y happy

2017-07-31 22:08 UTC, igor-dv commented on lib/ui/src/modules/ui/components/routed_link.js
> +    const { onClick, href, children, overrideParams, ...restProps } = this.props;
:+1:

2017-08-03 03:44 UTC, Hypnosphi commented
Maybe we should use links only for stories. In that case kinds wouldn't need to visually differ from namespaces

2017-08-03 04:47 UTC, Hypnosphi commented
How do you guys feel about adding indentation for stories by the way?
<img width="223" alt="screen shot 2017-08-03 at 07 45 48" src="https://user-images.githubusercontent.com/6651625/28906396-f76e7166-781f-11e7-8a43-48a9e1083cb7.png">

2017-08-03 05:09 UTC, igor-dv commented
@Hypnosphi I like the idea to make stories only blue (or links). IMO selected story shouldn't became black.. maybe some shade of blue ? Indentations is too deep I think, but nice

Are there any designers in here :sos:  ?

2017-08-03 05:24 UTC, Hypnosphi commented
> story shouldn't became black

Why? It's quite a standard way to mark link as 'active'

2017-08-03 06:02 UTC, shilman commented
Here are my opinions on this stuff. Sorry for the slow turnaround @Hypnosphi @igor-dv:
1. It's great to change things to links to make it easy to open up stories in other windows, accessibility, etc. 👍 
2. It's great to make a better visual distinction between "stories" and "kinds". 👍 
3. I don't think there necessarily needs to be a visual distinction between "folders" and "kinds" (they are all just groupings in the end). 👎 
4. I think the original indentation was fine. I think more indentation is not a good use of space, especially if we make a good visual distinction between stories and kinds. 👎 
5. I think the bright blue is pretty overwhelming. I'd like to come up with a better way to distinguish stories and kinds.

2017-08-03 06:20 UTC, shilman commented
Also to help with your blue/black debate, I submit [this](https://en.wikipedia.org/wiki/The_dress). Heheheh.

Personal preference is to keep the existing 3.2 look-and-feel and get another option ready to help distinguish stories and kinds, but I'm ok with subtle changes as long as we can revisit it soon.

2017-08-03 08:31 UTC, ndelangen approved these changes
<img width="223" alt="screen shot 2017-08-03 at 07 45 48" src="https://user-images.githubusercontent.com/6651625/28906396-f76e7166-781f-11e7-8a43-48a9e1083cb7.png" align="right">

**My thoughts on these discussions:**
✔️ better accessibility
✔️ blue
✔️ black=active
✔️ visual difference kind|story
❌ visual difference kind|group
✔️ added indentation

Screenshot is OK with me.

@shilman the dress is blue & gold

2017-08-03 12:28 UTC, Hypnosphi commented
> I think the bright blue is pretty overwhelming

Well it's link color from our website

2017-08-03 13:02 UTC, Hypnosphi commented
@shilman @igor-dv @ndelangen 
Can we maybe compromise on some minor indentation?
<img width="252" alt="screen shot 2017-08-03 at 16 00 23" src="https://user-images.githubusercontent.com/6651625/28923022-1c98efda-7865-11e7-8188-0fe25a115d9b.png">

2017-08-03 13:13 UTC, Hypnosphi commented
As an alternative to color I can suggest slight underline:
<img width="268" alt="screen shot 2017-08-03 at 16 12 35" src="https://user-images.githubusercontent.com/6651625/28923391-99588c14-7866-11e7-84d3-bf4866ac82bb.png">

2017-08-03 14:54 UTC, shilman commented
> > I think the bright blue is pretty overwhelming
> 
> Well it's link color from our website

The website and Storybook are entirely different UI's. Just because it looks OK in one doesn't mean that it looks OK in the other.

2017-08-03 15:33 UTC, Hypnosphi commented
I tried indigo from [material palette](https://www.materialui.co/colors)
<img width="218" alt="screen shot 2017-08-03 at 18 31 53" src="https://user-images.githubusercontent.com/6651625/28930009-2abc3eea-787a-11e7-9f8a-55819e0d3733.png">

2017-08-03 15:48 UTC, shilman requested changes
I'm sure this is tiring, but I'd like to propose that we split the PR into two:

1) functional changes that i'm happy to merge/release today
2) visual changes that are a lot more contentious

I have stronger thoughts about the visual side after consulting some designers, but i'd like to get the functional aspect of this merged and shipped

2017-08-03 16:16 UTC, Hypnosphi commented
So, to be clear, you want to introduce black links without underline?

2017-08-03 17:57 UTC, Hypnosphi commented
Ok, so I've rebased the branch, and left only the functional changes plus some minor style adjustments needed for correct focus outline dispaying

2017-08-04 16:17 UTC, shilman approved these changes
LGTM! Thanks for separating out the functional pieces. We'll come up with a good visual solution too!

2017-08-04 16:24 UTC, merged

2017-08-04 23:10 UTC, ndelangen commented
🥇