Fix/update eslint usage
storybookjs/storybook pull request #15346
Opened 2021-06-24 10:55 UTC by IgorSzyporyn

## What I did

Updated `@storybook/eslint-config-storybook` to 3.1.0

2021-06-24 13:39 UTC, ndelangen requested changes

2021-06-24 13:39 UTC, ndelangen commented on .eslintrc
> +    "sourceType": "module"
why would we switch to the non-js file format?

2021-06-25 08:58 UTC, ndelangen commented
@IgorSzyporyn the `3.1.0` version doesn't seem available on npm, could you check it out?

2021-06-25 10:17 UTC, IgorSzyporyn commented
> @IgorSzyporyn the `3.1.0` version doesn't seem available on npm, could you check it out?

Just released 3.1.0 in `config-linter`

Have (this PR)[https://github.com/storybookjs/eslint-config-storybook/pull/11] up to get eslint-config-storybook up to speed, and then this will work

2021-06-25 13:41 UTC, IgorSzyporyn commented on package.json
> +    "@storybook/eslint-config-storybook": "3.1.0-beta.1",
change to 3.1.1

2021-06-25 13:41 UTC, IgorSzyporyn commented on package.json
> +    "@storybook/linter-config": "3.1.0-beta.1",
change to 3.1.1

2021-08-02 14:54 UTC, shilman commented
@IgorSzyporyn what do you want to do about this one? can we close it for now?

2021-08-02 15:52 UTC, ndelangen commented
related:
https://github.com/storybookjs/storybook/pull/15366

2022-01-10 17:05 UTC, closed without merging