fix: removed packages uuid and uuid-browser for nanoid@3.1.23
storybookjs/storybook pull request #15415
Opened 2021-06-29 11:57 UTC by IgorSzyporyn

## What I did

Removed the two packages [uuid](https://www.npmjs.com/package/uuid) and [uuid-browser](https://www.npmjs.com/package/uuid-browser) for [nanoid](https://www.npmjs.com/package/nanoid)

## Why I did it

We do have a unique id requirement in places, and nanoid provides an easier to use interface and has less bells and whistles and comes in at half the cost in unpacked size (52.7 kB vs 116 kB) - and is only 108 bytes minified/gzipped and they claim it is 60% faster than UUID

## How to test

Pipeline tests should be enough

2021-06-29 13:40 UTC, ndelangen approved these changes

2021-06-30 08:11 UTC, shilman approved these changes
LGTM

2021-06-30 08:12 UTC, shilman requested changes
Looks like this PR breaks IE11 support:

https://www.chromatic.com/build?appId=5def62c97bd45f0020ef370e&number=8752

2021-06-30 08:47 UTC, IgorSzyporyn commented
> Looks like this PR breaks IE11 support:
> 
> https://www.chromatic.com/build?appId=5def62c97bd45f0020ef370e&number=8752

looking

2022-01-10 17:05 UTC, closed without merging