Document how to add individual story description, see #8527 #10823
storybookjs/storybook pull request #15417
Opened 2021-06-29 13:37 UTC by vidhill

Issue:

## What I did
Update docs to show how to add individual story description in CSF see #8527 #10823

\- I spent a silly amount of time trying to find this piece of info, I want to save the next person the trouble

## How to test

- Is this testable with Jest or Chromatic screenshots?
- Does this need a new example in the kitchen sink apps?
- Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

2021-06-29 13:46 UTC, shilman requested changes
This is actually the deprecated way of doing it. The recommended way is here:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#docs-description-parameter

2021-06-29 14:04 UTC, vidhill commented
Oh, I did not find that method either, I just updated my example, or is it documented elsewhere?

2021-06-29 15:12 UTC, shilman commented
@vidhill yes, documented here https://storybook.js.org/docs/react/writing-docs/doc-blocks#description

2021-06-29 20:02 UTC, vidhill commented
Shall I close/cancel this PR so?

2021-06-30 07:24 UTC, shilman commented on addons/docs/docs/recipes.md
> +Add `storyDescription` to `parameters.docs`
```suggestion
Add `story` to `docs.description` parameter
```

2021-06-30 07:24 UTC, shilman approved these changes
LGTM! Merging this altho it overlaps with the official docs

2021-06-30 07:25 UTC, merged