fix: a bug of require react
storybookjs/storybook pull request #15708
Opened 2021-07-29 07:21 UTC by ron0115

sometimes this  context judgement cause bug.

Issue:

## What I did

## How to test

- Is this testable with Jest or Chromatic screenshots?
- Does this need a new example in the kitchen sink apps?
- Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

2021-08-02 00:36 UTC, merceyz requested changes
`hasJsxRuntime` should ideally be passed the path to the filename, no assumptions about the layout should be made

Ref https://github.com/storybookjs/storybook/pull/12899#discussion_r511676973
Ref https://github.com/storybookjs/storybook/pull/13899

2021-08-02 05:00 UTC, shilman commented
Do you a have a reproduction repo you can share that demonstrates this bug? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce).

2021-08-02 07:17 UTC, ron0115 commented
I think the judge about monorepo or normal repo may be a hard code. So why the command path including all paths as much as possible ? It could cover more situations.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "storybookjs/storybook"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月2日(星期一) 中午1:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [storybookjs/storybook] fix: a bug of require react (#15708)





 
Do you a have a reproduction repo you can share that demonstrates this bug? If not, can you create one? See how to create a repro.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-08-16 14:53 UTC, shilman commented
Thanks for submitting this @ron0115 but I don' think we can merge unless we know exactly what cases it fixes. Happy to re-open if you can provide that! 🙏

2021-08-16 14:53 UTC, closed without merging