Document how to use info addon as decorator
storybookjs/storybook pull request #1592
Opened 2017-08-04 10:51 UTC by slorber

Issue:

## What I did

## How to test

2017-08-04 12:18 UTC, denkristoffer commented on addons/info/README.md
> +addDecorator(withInfo()(story => story()));
Wouldn't the info addon show information on the `WrapStory` component instead of the actual story component with this?

2017-08-04 13:06 UTC, UsulPro commented on addons/info/README.md
> +addDecorator(withInfo()(story => story()));
@denkristoffer it could be only if you add other decorators. In this case, it's important to keep the right decorators order.

2017-08-04 13:09 UTC, usulpro approved these changes
Thanks! This is really an important clarification that now it is possible to use this addon in decorators as well!

2017-08-04 13:10 UTC, slorber commented
@UsulPro wait I think @denkristoffer is right and there's something not ok with my code even if it almost works

2017-08-04 13:20 UTC, denkristoffer commented
@slorber I just tested it, @UsulPro seems to be right.

This works:
```js
addDecorator(withInfo()(story => story()))
addDecorator(withKnobs)
````

This shows the `WrapStory` component:
```js
addDecorator(withKnobs)
addDecorator(withInfo()(story => story()))
````

2017-08-04 13:23 UTC, slorber commented
@denkristoffer wouldn't it work better with this syntax?

```
addDecorator(story => withInfo()(() => story()))
```

But in all cases currently when displaying more infos on my component, the "more info" overlay does not include the component. I think I'm missing something but can't understand how to display the component on the more info overlay

2017-08-04 13:34 UTC, slorber commented
Honnestly I'm not sure to know exactly what I'm doing.

I've mentionned to declare this decorator first as you asked but don't really understand why so I'll let you merge or not ;)

2017-08-04 14:50 UTC, UsulPro commented
@slorber 

I guess in general it should be:

```
addDecorator((story, context) => withInfo('common info')(story)(context));
```

(because addon Info needs context to show the title)

> the "more info" overlay does not include the component

Do you mean that it shows `withKnobs` decorator or something like this?

(it could looks like this:

```
<WrapStory
  context={kind: "Button", story: "with text"}
  storyFn=anonymous()
  channel={_sender: "21d22b66d0135", _transport: {_config: {page: "preview"}, _buffer: [], _handler: bound _handleEvent()}, _listeners: {setCurrentStory: [anonymous()], addon:knobs:knobChange: [bound knobChanged()], addon:knobs:reset: [bound resetKnobs()]}}
  knobStore={store: {}, callbacks: [bound setPaneKnobs()]}
  initialContent=<Button />
/>
```
)

2017-08-04 15:16 UTC, shilman requested changes
the example is @UsulPro 's comment is correct.

@tmeasday  and I talked about updating the API in 3.4 so you can just do:

```js
addDecorator(withInfo('some common docs'))
```

but for now the adapter is the right way to go.

2017-08-04 19:04 UTC, slorber commented
I've updated. Is it still required to use it as first decorator now?

2017-08-04 21:51 UTC, UsulPro commented
I would say that the order of decorators matters! `addon-info` will show information about the child component provided into it and it doesn't know whether it's your component or another decorator. We have hot discussions about how to improve this behavior but at this moment it is how Storybook decorators work.

So if you need to show info about your component it should be the *deepest` decorator and it's important to   take into account that "local" decorators are deeper than "global"

2017-08-05 05:49 UTC, shilman approved these changes

2017-08-05 16:30 UTC, merged