fixed broken links in readme
storybookjs/storybook pull request #16170
Opened 2021-09-27 17:09 UTC by Jayita10

Issue: #16166 

## What I did

In the README file, fixed the links which are broken.

2021-10-04 15:04 UTC, yannbf commented on README.md
> +| info   | Annotate stories with extra component usage information    |
Actually the link was broken however the repo was correct. It was just a branch renaming issue. Could you please replace it with the correct link? Thanks!

```suggestion
| [info](https://github.com/storybookjs/deprecated-addons/tree/master/addons/info)   | Annotate stories with extra component usage information    |
```

2021-10-04 15:06 UTC, yannbf requested changes
Hey @Jayita10 thanks a lot for your contribution! I think there was a miscommunication and actually the links to info/notes should be kept, just fixed. Could you please do the changes? Thank you!

2021-10-04 21:10 UTC, jonniebigodes requested changes
@Jayita10 I've checked and left one item from my end that needs addressing. Let me know once you've updated your pull request based on my and @yannbf 's feedback so that I can take another look at it and hopefully merge it.

Have a great day!

Stay safe

2021-10-04 21:10 UTC, jonniebigodes commented on README.md
> +| [Rax](storybookjs/rax)                                                 | [v6.3.x](https://storybookjs.netlify.com/rax-kitchen-sink/)                                 | [![Rax](https://img.shields.io
@Jayita10 if you wouldn't mind changing this to the following:
- Marionette.js should link to https://github.com/storybookjs/marionette
- Mithril should link to https://github.com/storybookjs/mithril
- Marko should link to https://github.com/storybookjs/marko
- Riot should link to https://github.com/storybookjs/riot
- Rax should link to https://github.com/storybookjs/rax


To give you a bit of context on this, up until recently, those frameworks were implemented within the app directory in the Storybook monorepo. With a recent change they were moved into their own separate repositories to allow any contributors to continue working on supporting them.

2021-10-06 07:12 UTC, yannbf approved these changes
Looks great to me! Thanks a lot for your contribution! ♥️

2021-10-06 11:00 UTC, merged