Core: Add Story Index error handling
storybookjs/storybook pull request #16319
Opened 2021-10-12 12:39 UTC by tmeasday

Issue: #15816

Telescoping on https://github.com/storybookjs/storybook/pull/16242

## What I did

- Catch 500 errors from `stories.json` and show in a redbox in the preview (like other errors from `preview.js`)
- Set the store to be "errored" in the manager, which has the effect of showing a loading state in the sidebar

## How to test

- [x] Is this testable with Jest or Chromatic screenshots?

## Screenshot

<img width="1815" alt="image" src="https://user-images.githubusercontent.com/132554/136957668-c5783396-c6bf-41e0-9d40-4eb29c21668f.png">

2021-10-12 14:36 UTC, shilman approved these changes
Looking good 😻

2021-10-12 14:54 UTC, shilman requested changes
But lots of unit tests failing. Fixed a few but ran out of steam.

2021-10-12 21:37 UTC, tmeasday commented
Thanks @shilman, I can fix thme

2021-10-13 01:06 UTC, shilman approved these changes

2021-10-13 01:06 UTC, merged