Addon-a11y: Fix to use `loadStory` over deprecated `fromId`
storybookjs/storybook pull request #16398
Opened 2021-10-19 05:52 UTC by tmeasday

Issue: #16353 

## What I did

Use async `loadStory()`, rather than deprecated `fromId()`

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?

We could add an e2e test?

- [x] Does this need a new example in the kitchen sink apps?

I restored `addon-a11y` to a couple of examples

2021-10-19 13:30 UTC, shilman approved these changes
LGTM. @tmeasday what implications does this have for our broader addon ecosystem, if any? do we need to write a migration guide for addon authors?

2021-10-19 13:39 UTC, shilman requested changes

2021-10-19 23:01 UTC, tmeasday commented
> LGTM. @tmeasday what implications does this have for our broader addon ecosystem, if any? do we need to write a migration guide for addon authors?

I'm not sure how common it is for addon authors to be using internal store APIs like `fromId()` or `raw()/extract()`. I can add some migration notes about it I guess?

2021-10-20 08:41 UTC, shilman approved these changes
Nice one 💯

2021-10-20 08:41 UTC, merged