Found variables that are declared but not used anywhere.
storybookjs/storybook pull request #16460
Opened 2021-10-23 16:43 UTC by SACHINnANYAKKARA

2021-10-25 01:35 UTC, shilman requested changes

2021-11-08 21:36 UTC, yannbf commented
Hey @SACHINnANYAKKARA I believe you're quite busy, but there is a bit more work involved in your PR. I tried to fix it but it seems like maintainers can't push to your fork. Could you work on the feedback or give access to maintainers? Thank you!

2021-11-08 21:37 UTC, yannbf commented on scripts/reset.js
> +                logger.error(e);
```suggestion
              .catch(() => {

```

2021-11-15 15:10 UTC, shilman commented
Closing this because we can't push to the branch

2021-11-15 15:10 UTC, closed without merging