Deprecate confusing option names
storybookjs/storybook pull request #1692
Opened 2017-08-20 03:35 UTC by Hypnosphi

"Left Panel" => "Stories Panel"
"Down Panel" => "Addon Panel"

Old option names stay fully supported for now, but produce a deprecation warning

2017-08-20 05:48 UTC, igor-dv approved these changes
LGTM. (Let's not merge until #1693, please)

2017-08-20 09:34 UTC, UsulPro commented on lib/ui/src/libs/key_events.js
> +  NAVIGATION_PANEL: 3,
Why everywhere it's called "Stories Panel" but here is "Navigation Panel"?

2017-08-20 09:49 UTC, UsulPro commented
Great! :+1: 
This change is something that we really need to have done!

But I prefer to have a strong "How to test" section and maybe better to merge it right before the next minor releasing

2017-08-20 09:57 UTC, Hypnosphi commented
> a strong "How to test" section

I've made one, but both cases are covered by added tests

2017-08-20 10:02 UTC, UsulPro commented on lib/ui/src/libs/key_events.js
>    FULLSCREEN: 1,
Maybe it's a good time to also switch from numbers to literals here, what do you think?

2017-08-20 10:03 UTC, Hypnosphi commented on lib/ui/src/libs/key_events.js
> +  NAVIGATION_PANEL: 3,
My bad, skipped when refactoring

2017-08-20 10:04 UTC, Hypnosphi commented on lib/ui/src/libs/key_events.js
>    FULLSCREEN: 1,
Nice idea

2017-08-20 22:54 UTC, danielduan requested changes
Don't forget to update the readme file too. The docs might need an update as well.

https://github.com/storybooks/storybook/blob/master/addons/options/README.md

2017-08-20 23:03 UTC, Hypnosphi commented
> I'll update the addon-options docs as soon as it's published

2017-08-30 23:10 UTC, Hypnosphi commented
@danielduan I've changed base fork to `release/3.3`, this allowed to update README right now

2017-08-31 03:30 UTC, danielduan approved these changes

2017-08-31 11:15 UTC, merged