Retain iframe.html query parameters
storybookjs/storybook pull request #17136
Opened 2022-01-05 18:12 UTC by ittaibaratz

Issue:

Retain iframe.html query parameters coming from PREVIEW_URL

## What I did

This is a follow up to my previous PR, https://github.com/storybookjs/storybook/pull/16773.

The previous PR allowed the docs add on to use a specific iframe source configured via PREVIEW_URL. However we realized that even with doing that, Storybook always overrides any pre-existing query parameters when it sets its own query parameters (id, viewMode, etc).

This PR adds a utility function (getStoryHref) that will add the storybook query params without removing the existing params in the process. 

## How to test

TBD 

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

2022-01-06 01:47 UTC, shilman requested changes
Thanks @ittaibaratz ! The concept sounds reasonable, but the code has some weird dependencies. Would be great to fix that before merging.

2022-01-06 01:47 UTC, shilman commented on lib/components/src/blocks/Story.tsx
> +import { getStoryHref } from '../../../ui/src/components/preview/utils/getStoryHref';
Can you move this to `@storybook/components` and export it from there?

2022-01-06 02:08 UTC, ittaibaratz commented
> Thanks @ittaibaratz ! The concept sounds reasonable, but the code has some weird dependencies. Would be great to fix that before merging.

Sure thing! That's done now, please check.

2022-01-10 15:23 UTC, shilman approved these changes
Great stuff @ittaibaratz 🎸

2022-01-10 17:03 UTC, merged