FIX #1709
storybookjs/storybook pull request #1713
Opened 2017-08-22 22:05 UTC by ndelangen

fixes: #1709 

## What I did
Moved cacheDirectory back to webpack config from babel config

## How to test
See issue (I think it should be apparent when using storyshots?)

2017-08-22 22:24 UTC, Hypnosphi approved these changes
LGTM

2017-08-22 22:46 UTC, tmeasday commented
RE: testing -- yes this was a storyshots issue, test the various app modes in SS.

2017-08-23 00:09 UTC, satazor requested changes

2017-08-23 00:09 UTC, satazor commented on app/vue/src/server/config/babel.js
>  module.exports = {
Remove unused findCacheDir above.

2017-08-23 00:09 UTC, satazor commented on app/vue/src/server/config.js
> +
Remove extra space.

2017-08-23 00:09 UTC, satazor commented on app/vue/src/server/config.js
> +  config.module.rules[0].query = {
Shouldn't this be applied to the react app too?

2017-08-23 00:30 UTC, Hypnosphi commented
Seems like we `.eslintignore` everything related to vue: https://github.com/storybooks/storybook/blob/master/.eslintignore#L9
Is there any good reason for that?

2017-08-23 00:32 UTC, Hypnosphi commented
That's what I get when I remove this line:
```
111 problems (10 errors, 101 warnings)
0 errors, 85 warnings potentially fixable with the `--fix` option.
```

Seems doable, I'll try to handle it

2017-08-23 00:48 UTC, Hypnosphi commented
Here it is #1715

2017-08-23 06:00 UTC, merged

2017-08-23 08:13 UTC, satazor commented
❤️ 

Could we have a patch release? :D