Angular: Fix angular 13.1 JIT error and HMR reload
storybookjs/storybook pull request #17131
Opened 2022-01-05 14:30 UTC by ThibaudAV

Issue: https://github.com/storybookjs/storybook/issues/17039

## What I did

- Disable unnesasary webpack stuff if we use angular-cli >= 12
- Add deprecation warning when project use angular.json with legacy way
- Add watch option for angular 13.x

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

Angular test by @ThibaudAV locally on project : 

- [x] Angular 12.x  (with csf3 and IRL project :p )
- [x] Angular 13.x
- [x] Angular 12.x with fresh install 

other ? 

If your answer is yes to any of these, please make sure to include it in your PR.

2022-01-05 15:05 UTC, ThibaudAV commented on app/angular/src/server/framework-preset-angular-cli.ts
> +  logger.warn(dedent` Your Storybook startup uses a solution that will not be supported in version 7.0.
maybe we can improve my English 😅

2022-01-05 17:00 UTC, shilman requested changes
Thanks @ThibaudAV !!!! 🙏 🙏 🙏 

It looks like this is breaking on the Angular12 e2e tests. Can you please take a look?

2022-01-06 08:02 UTC, ThibaudAV commented
thanks will do more test with fresh install in Angular 12.x

2022-01-06 13:04 UTC, ThibaudAV commented
fixed no ? 

There are now 2 distincts modes old and new. It was necessary to exclude this configuration with the same "reasoning"

`angular >=13` -> new way
`angular 12.2.x with builder` -> new way
`other (<=12)` -> old way 

there is this distinction for the builder and angular 12 because it allowed to validate the new way before angular 13. and I think it's good to keep it

2022-01-06 14:29 UTC, shilman approved these changes
Thanks @ThibaudAV !!! 🙏 💯 🎖️

2022-01-06 14:29 UTC, merged