Chore: (Docs) Updates Storybook configuration docs for TS and flags.
storybookjs/storybook pull request #17358
Opened 2022-01-27 21:31 UTC by jonniebigodes

With this pull request, the documentation is updated to include TS support and available feature flags.

What was done:
- Updated the Storybook configure/Overview docs.
- Polished and created snippets.

Closes #16079 and #15629

@shilman would appreciate some feedback on this, and please let me know if I forgot any feature flags or something of that nature. Thanks in advance.

2022-02-07 15:17 UTC, shilman requested changes
small change otherwise LGTM!

2022-02-07 20:16 UTC, jonniebigodes commented on docs/configure/overview.md
> +| `logLevel`            | Configures Storybook's logs in the terminal. Useful for debugging <br/> `logLevel: 'debug'`
Fixed with the latest commit. Thanks for this 🙏 !

2022-02-07 20:18 UTC, jonniebigodes commented on docs/snippets/common/storybook-main-default-setup.ts.mdx
> +  stories: [],
Indeed we can, and I've updated it with the latest commit. Let me know if you're ok with it, or any other feedback. Thanks for taking the time to review it @shilman !

2022-02-11 09:51 UTC, shilman approved these changes
LGTM!! 💯

2022-02-11 09:51 UTC, merged

2022-06-10 11:14 UTC, SoundAsleep192 commented
Adding `.babelrc` solves the compiling issue but has problems with `type: module` throwing errors about `require`. Any thoughts?