refactor(store): move csf related logic to its own folder
storybookjs/storybook pull request #17381
Opened 2022-02-01 08:58 UTC by yannbf

Issue: N/A

## What I did

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

2022-02-02 01:47 UTC, tmeasday approved these changes
Awesome, thanks @yannbf

2022-02-02 06:22 UTC, shilman requested changes

2022-02-02 06:22 UTC, shilman commented on lib/store/src/csf/processCSFFile.ts
> +import { Path } from '..';
```suggestion
import type { Path } from '../types';
```

Isn't this a circular dependency otherwise?

2022-02-04 11:47 UTC, shilman approved these changes
Nice! 🚀

2022-02-04 11:47 UTC, merged