chore: bump addon_docs @jest/transform
storybookjs/storybook pull request #17933
Opened 2022-04-11 14:24 UTC by trfv

Issue:

## What I did
bump addon_docs @jest/transform to fix this warning
```
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
```

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

2022-04-11 14:42 UTC, shilman requested changes
Thanks @trfv! This is technically a breaking change for Jest 26 users. If you update to accept either 26 or 27, it should achieve your intended results AND not be breaking. WDYT?

2022-04-11 14:42 UTC, shilman commented on addons/docs/package.json
> +    "@jest/transform": "^27.5.1",
```suggestion
    "@jest/transform": "^26.6.2 || ^27.5.1",
```

2022-04-12 05:44 UTC, shilman reviewed
@trfv thanks for making those changes. can you please try updating the snapshots to see if the build passes that way?

```
yarn bootstrap --core
yarn test -u
```

2022-04-13 10:46 UTC, trfv commented
> @trfv thanks for making those changes. can you please try updating the snapshots to see if the build passes that way?
> 
> ```
> yarn bootstrap --core
> yarn test -u
> ```

hi @shilman 
thank you for your kind support.
`yarn bootstrap --core` did not make any change.
`yarn test -u` made some update for snapshots.

2022-05-06 11:23 UTC, closed without merging