Fix/17063/avoid undefined args
storybookjs/storybook pull request #17973
Opened 2022-04-15 06:06 UTC by evont

Issue:

## What I did
fix args values not present in url are casted to !undefined for controls of type select and radio [issue](https://github.com/storybookjs/storybook/issues/17063) 

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

2022-05-03 20:00 UTC, kylegach reviewed
Thank for fixing this important issue, @evont! And with your very first contribution. 👏 

@shilman @tmeasday — This change seems sound to me, but the args code in general is likely quite nuanced and I think it would benefit from you taking a look as well. Also, is it OK that this PR is against `main` instead of `next`?

2022-05-03 20:36 UTC, kylegach commented
@evont — I'd do this myself, but I cannot push to your fork's branch. Can you please add this story, to the `examples/official-storybook/stories/core/args.stories.js` file?

```js
export const TestUndefinedArgs = Template.bind({});
TestUndefinedArgs.args = {
  first: 'Bob',
  last: 'Miller',
  foo: 'bar',
};
TestUndefinedArgs.argTypes = {
  first: {
    options: ['Bob', 'Alice'],
  },
  last: {
    options: ['Miller', 'Meyer'],
  },
  foo: {
    control: { type: 'text' },
  },
};
```

That will allow maintainers to easily test your change (use the same repro steps as the linked issue) in the deployed Storybook. Thanks!

2022-05-04 01:37 UTC, shilman requested changes
Hi @evont @kylegach -- thanks for the fix! Indeed all PRs should go against `next` not `main` unless it's a special case, which AFAICT this is not. Please rebase & retarget the PR. 🙏

2022-05-04 01:43 UTC, tmeasday requested changes
Thanks for the contribution @evont. Can you please add test case(s) that demonstrate the original problem?

2022-05-04 01:43 UTC, tmeasday commented on lib/store/src/args.ts
>      if (args[key] === undefined || options.includes(args[key]) || isValidArray) {
This check for `args[key] === undefined` seems a little pointless if we later do `if (key in args)`. Do we understand why the code was there in the first place? We should get rid of it, and perhaps figure that out.

2022-05-04 01:43 UTC, tmeasday commented on lib/store/src/args.ts
>      if (args[key] === undefined || options.includes(args[key]) || isValidArray) {
Or does it remain here to avoid the warning lower down?

2022-05-04 14:49 UTC, evont commented
> @evont — I'd do this myself, but I cannot push to your fork's branch. Can you please add this story, to the `examples/official-storybook/stories/core/args.stories.js` file?
> 
> ```js
> export const TestUndefinedArgs = Template.bind({});
> TestUndefinedArgs.args = {
>   first: 'Bob',
>   last: 'Miller',
>   foo: 'bar',
> };
> TestUndefinedArgs.argTypes = {
>   first: {
>     options: ['Bob', 'Alice'],
>   },
>   last: {
>     options: ['Miller', 'Meyer'],
>   },
>   foo: {
>     control: { type: 'text' },
>   },
> };
> ```
> 
> That will allow maintainers to easily test your change (use the same repro steps as the linked issue) in the [deployed Storybook](https://deploy-preview-17973--storybookjs.netlify.app/official-storybook/?path=/story/core-args--test-undefined-args). Thanks!

Sure, with pleasure, I have added it and push it to the branch, except I added `control: { type: 'select' }` because it is odd that if I don't do that, the `options` will not transform into `select` but `text`

2022-05-04 16:05 UTC, evont commented
Sorry for my mistake, fork from main branch and rebase to next will be that tough, so I decided to fork form next and make a new PR, please check in this [new PR](https://github.com/storybookjs/storybook/pull/18135)
@tmeasday @kylegach @shilman

2022-05-05 00:14 UTC, shilman commented
Thanks @evont! Closing this in favor of #18135

2022-05-05 00:14 UTC, closed without merging