security: update x-default-browser
storybookjs/storybook pull request #18157
Opened 2022-05-06 09:55 UTC by The-Code-Monkey

Issue:

## What I did

created the package under my mono repo and published it with the security update, should work fine, i also converted all to typescript which means we don't need to declare any types 

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

2022-05-06 10:25 UTC, shilman requested changes
@The-Code-Monkey looks like you need to update the import in the source code as well

2022-05-16 15:20 UTC, The-Code-Monkey commented
@shilman bump.

2022-05-18 21:53 UTC, Codex- commented
This addresses a new audit warning introduced in [this commit](https://github.com/storybookjs/storybook/commit/813d3bd142851ab68583b5337dfadf276b866677) so would be great to see this brought in

2022-05-18 21:53 UTC, Codex- commented on lib/core-client/src/typings.d.ts
> +declare module '@storybook/ui';
removed eof newline

2022-05-19 11:53 UTC, merged