Vue: fix implicit render function
storybookjs/storybook pull request #18209
Opened 2022-05-12 13:26 UTC by yannbf

Issue: N/A

## What I did

The implicit render function was not being exported nor props from components that are defined via `@Prop` were correctly passed to the component. Both of these things are now fixed!

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

2022-05-12 13:30 UTC, yannbf commented
Thank you so much for catching this bug @kylesuss!

2022-05-14 10:16 UTC, shilman requested changes
@yannbf any idea why CI is broken?

2022-05-16 10:07 UTC, yannbf commented
> @yannbf any idea why CI is broken?

Funny enough the default render function was wrong, but still worked. I changed it to the correct way, which is by passing `Object.keys(argTypes)` to `props` rather than the actual `args`. The way Vue sb renders stories is... curious. Hehe

Should be good now!

2022-05-16 11:35 UTC, shilman approved these changes

2022-05-16 11:36 UTC, merged