Allow react-test-renderer 18 for storyshots (#17985)
storybookjs/storybook pull request #18296
Opened 2022-05-21 22:15 UTC by geisterfurz007

Issue: addon-storyshots limits versions for react-test-renderer to 16/17 colliding with React 18 (see #17985)

## What I did

Added ^18.0.0 to the allowed range for react-test-render so newer versions can be used without package.json hacks.

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

2022-05-23 14:45 UTC, yannbf commented
Hey @geisterfurz007 thanks for your contribution! Could you update the lockfile as well? Thanks!

2022-05-23 18:56 UTC, geisterfurz007 commented
Yes of course, my bad! Should be better now 👍

2022-05-30 15:49 UTC, geisterfurz007 commented
@yannbf Hey, just to make sure; do you need anything else from me?

2022-06-06 15:23 UTC, shilman requested changes
This looks like it's breaking CI. Storybook's monorepo is currently on React 17, so this causes the monorepo to use `react-test-renderer` 18, which is incompatible.

I wonder if we could get around this by adding the following to `devDependencies` to trick it to using v17 in the monorepo:

```
react-test-renderer": "^17.0.0"
```

WDYT? Mind giving it a try @geisterfurz007 ?

2022-06-06 15:29 UTC, geisterfurz007 commented
I hope I put it in the correct file; let me know if I didn't! I recall Yarn not being too happy with the same package in both dependency and devDependency so I assumed you meant the root package.json. 🤞

2022-06-06 15:53 UTC, shilman commented
@geisterfurz007 that's not what I meant, but putting it at the root is pretty clever! let's see what CI says 😄

2022-06-06 16:53 UTC, geisterfurz007 commented
@shilman Seems like moving the line up to the resolutions block works (at least the previously failing unit-tests now run through and the other failing circleci jobs appear to be caused by other packages.

Let me know if this counts as bandaid fix; otherwise I will stick to the resolutions field in my own project for the time being 😄

2022-07-06 16:16 UTC, ndelangen approved these changes

2022-07-11 14:56 UTC, merged