chore(repro): add additional files api to sb repro
storybookjs/storybook pull request #18389
Opened 2022-06-02 13:15 UTC by yannbf

Issue: N/A

## What I did

Added `additionalFiles` to repro config, so that we can add files before initializing Storybook.

Looks like this:
```js
export const react = {
  framework: 'react',
  name: 'react',
  version: 'latest',
  generator: fromDeps('react', 'react-dom'),
  additionalDeps: ['prop-types'],
  additionalFiles: [
    { 
      path: '.babelrc',
      contents: dedent`
        {
          "presets": ["@babel/preset-env"]
        }
      `,
    }
  ]
};
```

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

2022-06-03 14:34 UTC, shilman approved these changes
LGTM -- any idea what's up with the codecov comments in the review mode? it's really annoying

2022-06-03 14:36 UTC, shilman requested changes

2022-06-03 14:36 UTC, shilman commented on lib/cli/src/repro-generators/scripts.ts
> +  console.log({ options });
Extra `console.log`?

2022-06-06 11:46 UTC, yannbf commented on lib/cli/src/repro-generators/scripts.ts
> +  additionalFiles.forEach(async (file) => {
Great catch – It was working for my small tests and I definitely overlooked it. Updated now

2022-06-06 11:49 UTC, yannbf commented
> LGTM -- any idea what's up with the codecov comments in the review mode? it's really annoying

Definitely annoying – I think the "problem" was introduced with the A11yPanel component changes from another PR: https://app.codecov.io/gh/storybookjs/storybook/compare/18389/changes

2022-06-06 14:44 UTC, shilman approved these changes
Looks great! 💯

2022-06-06 14:44 UTC, merged