Support .cjs extension
storybookjs/storybook pull request #18502
Opened 2022-06-17 09:11 UTC by ddalpange

Issue:

## What I did

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

2022-06-28 21:50 UTC, ndelangen commented on app/angular/src/server/framework-preset-angular-cli.test.ts
> +      extensions: ['.cjs', '.mjs', '.js', '.jsx', '.ts', '.tsx', '.json'],
I fear this order changing will likely break some user's setup!

2022-06-28 21:50 UTC, ndelangen commented on lib/builder-webpack4/src/preview/iframe-webpack.config.ts
> +      extensions: ['.cjs', '.mjs', '.js', '.jsx', '.ts', '.tsx', '.json'],
same here

2022-06-28 21:50 UTC, ndelangen commented on lib/builder-webpack5/src/preview/iframe-webpack.config.ts
> +      extensions: ['.cjs', '.mjs', '.js', '.jsx', '.ts', '.tsx', '.json', '.cjs'],
same here

2022-06-28 21:50 UTC, ndelangen commented on lib/manager-webpack4/src/presets/manager-preset.ts
> +      extensions: ['.cjs', '.mjs', '.js', '.jsx', '.json', '.cjs', '.ts', '.tsx'],
same here

2022-06-28 21:50 UTC, ndelangen commented on lib/manager-webpack5/src/presets/manager-preset.ts
> +      extensions: ['.cjs', '.mjs', '.js', '.jsx', '.json', '.cjs', '.ts', '.tsx'],
same here

2022-06-28 21:52 UTC, ndelangen requested changes
I fear changing the order of these resolve configs will be a problem for other users...

2022-06-29 10:18 UTC, shilman approved these changes
LGTM. Thanks so much for doing this @ddalpange !!!

2022-06-29 10:18 UTC, merged