Allow configuring docs index processing via main.js
storybookjs/storybook pull request #18573
Opened 2022-06-26 12:07 UTC by tmeasday

Added three options on the top-level field `docs`:

 - `enabled` - if unset, we don't generate any `type: docs` entries
 - `defaultName` - what name to use for docs entries?
 - `docsPage` - [NOT YET USED] -- will be used to drive the creation of docs entries per-CSF file.

## How to test

- See unit tests
- Can also set the field in an example app and see if enabled disables docs entries, and `defaultName` changes the entry for "Examples/Button":
<img width="227" alt="image" src="https://user-images.githubusercontent.com/132554/175813308-500ab49d-2a74-4490-957f-ad5f62152465.png">

2022-07-06 04:49 UTC, shilman requested changes
Mostly LGTM. A couple nits.

2022-07-06 04:49 UTC, shilman commented on lib/core-server/src/dev-server.ts
> +import {
This goes against the coding style established by @ndelangen where the types & concrete imports are always separate. We should update it OR update the project style guidelines

2022-07-06 04:49 UTC, shilman commented on addons/docs/src/preset.ts
> +export const storyIndexers = async (indexers: StoryIndexer[] | null) => {
why not undefined?

2022-07-06 09:02 UTC, tmeasday commented on addons/docs/src/preset.ts
> +export const storyIndexers = async (indexers: StoryIndexer[] | null) => {
I don't think I meant to change that 🤔

2022-07-07 00:41 UTC, shilman commented
@tmeasday can you
- resolve merge conflicts
- get the build green

let me know if you need any help with the latter

2022-07-07 02:40 UTC, tmeasday commented
@shilman I think it is green now apart from one flaky chromatic test that I believe @ghengeveld introduced (and maybe fixed)?

2022-07-07 23:38 UTC, shilman approved these changes
LGTM. Merging!

2022-07-07 23:38 UTC, merged