do not remove the old framework, because that's now the renderer
storybookjs/storybook pull request #19129
Opened 2022-09-07 13:11 UTC by ndelangen

I saw an auto-migration remove `@stroybook/react` that is incorrect.

Although this package is no longer the 'framework' it is the renderer, and users can import APIs from it, so it should remain a dependency for users.

2022-09-07 13:15 UTC, yannbf commented
Even though that's correct, shouldn't users change their imports from @storybook/react to @storybook/react-webpack5?

2022-09-08 14:16 UTC, ndelangen commented
> Even though that's correct, shouldn't users change their imports from @storybook/react to @storybook/react-webpack5? If so, we could print out on the banner that users should change their imports too

No, they should not.

Users should keep importing from `@storybook/react`.

Importing from `@storybook/react-webpack5` is only for config.

2022-09-08 15:35 UTC, yannbf requested changes
Got it! Can you please update the tests?

2022-09-13 12:07 UTC, ndelangen commented on code/lib/builder-webpack5/src/preview/iframe-webpack.config.ts
> +// @ts-ignore
This started throwing an error at build, no idea why.

I tried installing the `@types/..` package but it's not using the right version of webpack, so it's un-usable..

2022-09-13 12:17 UTC, merged