fix: typos in migration docs
storybookjs/storybook pull request #19629
Opened 2022-10-26 09:41 UTC by mohdashraf010897

minor typos

2022-10-29 13:44 UTC, jonniebigodes requested changes
@mohdashraf010897, thanks for taking the time and effort for this pull request and helping us improve the documentation by fixing the typos. We appreciate it. Just one small item and this should be good to go

2022-10-29 13:44 UTC, jonniebigodes commented on the the
> +me, you can continue to use the `docs.theme` parameter.
@mohdashraf010897, I'd appreciate it if you wouldn't mind reverting this to how it was initially. The change you're making here is introducing additional typos.

2022-11-05 19:39 UTC, jonniebigodes reviewed
@mohdashraf010897, thanks for addressing the feedback so promptly. Appreciate it 🙏 ! Going to check it and if all is good merge it

2022-11-06 11:50 UTC, CasperSocio approved these changes

2022-12-30 19:30 UTC, jonniebigodes commented
Closing this as it was fixed in a follow up pull request.

2022-12-30 19:30 UTC, closed without merging