Disable play functions in docs mode, unless you set `parameters.docs.autoplay`
storybookjs/storybook pull request #19659
Opened 2022-10-28 05:35 UTC by tmeasday

Issue: Play functions cause havoc on docs pages ;)

## What I did

- Don't play unless `runPlayFunction` is set
- Pass that true by default
- Pass that false from the `<Story>` doc block, unless `parameters.docs.autoplay` is set

## How to test

See `autoplay` stories, or e2e/unit tests

2022-10-28 06:13 UTC, shilman requested changes
Nice one!!! 🚀

2022-10-28 06:13 UTC, shilman commented on code/lib/preview-web/src/render/StoryRender.ts
> +      console.log(err);
```suggestion
```

2022-10-28 09:08 UTC, JReinhold reviewed
In general I think this is good, but I don't understand why `autoplay` and `runPlayFunction` are different. As far as I understand they do the exact same thing, they're just applied in different places, so I would think it was simpler if they were both called `autoplay`.

2022-10-28 12:32 UTC, tmeasday commented
I guess that's a fair point. I guess my thought process was that a pithy name makes more sense for a user facing parameter (`autoplay`) but a longer, more descriptive name made more sense for an internal API.

However, I agree, the confusion of having different names for the same thing is not worth the dubious benefit of the above.

2022-10-31 01:26 UTC, tmeasday commented
So the E2E test is failing for `svelte` SBs for a reason I think unrelated to this PR: the "primary" story in docs page isn't rendering properly:
<img width="680" alt="image" src="https://user-images.githubusercontent.com/132554/198913273-e1abfd34-b777-4a91-974b-10e65e4f16eb.png">

Note, oddly, that the rest of the stories do render fine in docspage.

2022-10-31 01:43 UTC, shilman approved these changes
I agree with @JReinhold 's comment on renaming `runPlayFunction` to `autoplay`. Otherwise LGTM!

2022-11-01 02:47 UTC, tmeasday commented
Changes are made, this PR is just [blocked on this now](https://github.com/storybookjs/storybook/pull/19659#issuecomment-1296426368).

2022-11-01 07:54 UTC, JReinhold approved these changes
Looks good to me. I'll investigate the Svelte issue. It's been there for a while, I guess it's just now that we're catching it in our tests.

2022-11-04 01:46 UTC, merged

2022-11-04 01:46 UTC, tmeasday commented
Thanks for the assist @JReinhold !!