Docs: Update cli templates for v7 beta
storybookjs/storybook pull request #19847
Opened 2022-11-16 10:35 UTC by kasperpeulen

Issue:

## What I did

- Only one comment about args
- Only one comment above meta
- Change links to point to 7.0

2022-11-16 19:05 UTC, jonniebigodes requested changes
@kasperpeulen, this is shaping up great. Thanks for taking care of this so promptly. Appreciate it. From my end, I left a couple of items that require addressing, and this should be good to go. I'll defer to @shilman's input so we can merge this.

2022-11-16 19:05 UTC, jonniebigodes commented on code/renderers/vue3/template/cli/Page.stories.js
>    component: MyPage,
@kasperpeulen seems that you accidentally removed the `render` function am I correct?

2022-11-17 10:48 UTC, kasperpeulen commented on code/frameworks/angular/template/cli/Header.stories.ts
> +    // More on Story layout: https://storybook.js.org/docs/7.0/angular/configure/story-layout
Sounds good to me.

2022-11-17 10:50 UTC, kasperpeulen commented on code/renderers/react/template/cli/ts/Button.stories.ts
> +// 3. And change links to point to 7.0
Will fix that :D

2022-11-17 10:57 UTC, kasperpeulen commented on code/renderers/vue3/template/cli/Button.stories.js
>    tags: ['docsPage'],
@jonniebigodes I would say that now that we have default render functions for all major renderers, we should only show the render function when it is different than the default. What do you think @shilman ?

2022-11-17 10:58 UTC, kasperpeulen commented on code/frameworks/ember/template/cli/1-Button.stories.js
> +// More on how to set up stories at: https://storybook.js.org/docs/7.0/ember/writing-stories/introduction
I think so too, I will change it.

2022-11-17 15:22 UTC, jonniebigodes commented on code/renderers/vue3/template/cli/Button.stories.js
>    tags: ['docsPage'],
Thanks for the clarification on this @kasperpeulen !  And we can add an example featuring a `render` function further down the line as we previously discussed.

2022-11-17 15:23 UTC, jonniebigodes approved these changes
@kasperpeulen all is good on my end. Thanks for providing the clarification and addressing the feedback so promptly. Appreciate it 🙏 ! Merge when able

2022-11-17 16:06 UTC, merged