Upgrade snippets for v7 TS changes
storybookjs/storybook pull request #19850
Opened 2022-11-16 13:54 UTC by kasperpeulen

## What I did

- Upgrade snippets for v7 TS changes

2022-11-16 20:11 UTC, jonniebigodes requested changes
@kasperpeulen, thanks for the fantastic job on this one. From my end, just a couple of small tweaks and this is good to go. Let me know once they're addressed.

2022-11-17 11:09 UTC, kasperpeulen commented on docs/snippets/angular/button-group-story.ts.mdx
Done that

2022-11-17 11:14 UTC, kasperpeulen commented on docs/snippets/angular/storybook-preview-global-decorator.ts.mdx
>  // .storybook/preview.js
Yes already available! Changed the filename.

2022-11-17 15:19 UTC, jonniebigodes approved these changes
All good on my end! This is good to merge! Thanks for taking care of the feedback so promptly @kasperpeulen

2022-11-17 15:42 UTC, merged