Build: tsup to build vite-builder
storybookjs/storybook pull request #19895
Opened 2022-11-19 00:50 UTC by ndelangen

Issue:

## What I did

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

2022-11-20 09:28 UTC, ndelangen commented on code/lib/builder-vite/package.json
> +  "peerDependencies": {
I'd make it a regular dep, myself.
but make the version range very open.

2022-11-20 22:09 UTC, IanVS commented on code/lib/builder-vite/package.json
> +  "peerDependencies": {
Sounds good.  Want to do that in this PR?  I think that `>= 3.0.0` should work.  4.0 is in alpha right now, though, which won't be included in that range and we'll end up with potentially duplicated versions.  I don't know of a way for `dependencies` to handle that situation.  Whereas `peerDependencies` of `>= 3.0.0 || >= 4.0.0-0` would accept either one, I think.  But maybe the pain of peer deps isn't worth it, and if someone wants to use the alpha of vite they just need to be sure to use `overrides` or `resolutions` in their package.json.

2022-11-21 12:00 UTC, IanVS requested changes
I don't think we can leave vite in devDependencies or it will be prebundled.

2022-11-21 12:34 UTC, ndelangen commented
@IanVS it's in both, therefore not pre-bundled.

2022-11-21 12:55 UTC, IanVS commented
Thanks, what is the purpose of keeping it in devDependencies if it is also in dependencies?

2022-11-21 16:10 UTC, IanVS approved these changes

2022-11-21 16:43 UTC, merged