Add `contribute/framework` doc
storybookjs/storybook pull request #19943
Opened 2022-11-23 20:29 UTC by kylegach

## What I did

Add a page at the `/docs/<framework>/contribute/framework` route explaining how to contribute a Storybook framework

2022-11-24 01:06 UTC, shilman approved these changes
This is great!

Historically, people have wanted to contribute frameworks directly to the monorepo--I wonder if this doc should somehow preempt that.

I also wonder about a step on distributing the framework, e.g. tweet and mention `@storybookjs`. Or if the pattern described here will automatically get picked up by the integrations catalog, mention that?

2022-11-28 12:30 UTC, jonniebigodes requested changes
@kylegach, this looks great. Just left a couple of items for you to look at. Let me know if you're ok with it, and we'll go from there also while we're at it. It seems that you left out the toc.js entry so we can hook this up to the documentation. Was this intentional or not?

2022-11-28 12:30 UTC, jonniebigodes commented on docs/contribute/framework.md
> +Before writing any code, we advise you to write up a helpful README. It should, at minimum, contain installation instructions and a list of available features. Use the [README for `@storybook/nextjs`
@kylegach we can probably rename this  "Write documentation". What do you think?

2022-11-28 12:30 UTC, jonniebigodes commented on docs/contribute/framework.md
> +We deeply appreciate your help in making Storybook work for more developers and the libraries in which they build. If you have any suggestions to improve this document, please use the “Edit” link bel
@kylegach, if this is going to be added to the documentation, we don't need this. Instead, we could replace this with something linking to the other parts of the documentation of how to contribute, something like:
```md
---
Learn about other ways you can contribute to Storybook:
- [Documentation](./documentation.md) 
- [Examples](./new-snippets.md) 
- [Code](./code.md)
```

If you're ok with this, we can adjust the other contribution pages

2022-11-29 11:43 UTC, jonniebigodes approved these changes
Thanks for taking care of the feedback so promptly @kylegach! Appreciate it. All good on my end! Merge when able

2022-11-29 15:58 UTC, merged