export the controlOrMetaKey fn from manager-api
storybookjs/storybook pull request #19972
Opened 2022-11-25 18:19 UTC by winkerVSbecks

## What I did

export the `controlOrMetaKey` functions from manager-api. It's used by `@storybook/components-marketing`. Previously we could import from `@storybook/api/shortcuts` however that is no longer the case. 

## How to test

- [x] Is this testable with Jest or Chromatic screenshots?
- [x] Does this need a new example in the kitchen sink apps?
- [x] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

2022-11-25 18:33 UTC, yannbf approved these changes
Great catch @winkerVSbecks !

2022-11-25 23:13 UTC, shilman requested changes
@winkerVSbecks @ndelangen why don't we just `export * from './lib/shortcut'`? Isn't it weird to export one of these helper functions and not the others?

2022-11-26 01:39 UTC, winkerVSbecks commented
@shilman good point. I'll update

2022-11-28 07:48 UTC, yannbf approved these changes

2022-11-28 07:48 UTC, merged