Angular: Switch to default to inlineStories=true
storybookjs/storybook pull request #20118
Opened 2022-12-07 04:34 UTC by tmeasday

Issue: https://github.com/storybookjs/storybook/issues/18176#issuecomment-1340267173

## What I did

Fix up some loose ends

## How to test

Check angular sandboxes

2022-12-07 04:45 UTC, shilman requested changes

2022-12-07 04:45 UTC, shilman commented on code/addons/docs/angular/README.md
> +export const parameters = { docs: { inlineStories: true } };
```suggestion
export const parameters = { docs: { inlineStories: false } };
```

2022-12-07 04:45 UTC, shilman commented on code/addons/docs/react/README.md
> +export const parameters = { docs: { inlineStories: true } };
```suggestion
export const parameters = { docs: { inlineStories: false } };
```

2022-12-07 04:45 UTC, shilman commented on code/addons/docs/vue/README.md
> +export const parameters = { docs: { inlineStories: true, }, };
```suggestion
export const parameters = { docs: { inlineStories: false, }, };
```

2022-12-07 04:45 UTC, shilman commented on code/addons/docs/vue3/README.md
> +export const parameters = { docs: { inlineStories: true } };
```suggestion
export const parameters = { docs: { inlineStories: false } };
```

2022-12-07 04:45 UTC, shilman commented on code/addons/docs/vue3/README.md
> +export const parameters = { docs: { inlineStories: true } };
Add iframeHeight to example also?

2022-12-07 04:45 UTC, shilman commented on code/addons/docs/web-components/README.md
> +export const parameters = { docs: { inlineStories: true } };
```suggestion
export const parameters = { docs: { inlineStories: false } };
```

2022-12-07 04:46 UTC, tmeasday reviewed
x

2022-12-07 04:48 UTC, tmeasday commented
I decided not to add the height parameter in case people thought it was needed, but I can change it.

2022-12-20 15:42 UTC, ndelangen approved these changes

2022-12-21 01:17 UTC, merged