Vite: make vite a peer dependency, update plugins
storybookjs/storybook pull request #20281
Opened 2022-12-14 23:09 UTC by IanVS

Issue:

Closes https://github.com/storybookjs/storybook/pull/20227

## What I did

This moves `vite` to a peer dependency, and allows either version 3 or 4.  

It keeps the plugins as normal dependencies.  They are only used as fallbacks in case the user does not have a `vite.config.js`.  For the most part, the newer plugins will work with vite 3, with the possible exception of svelte.  But the solution in those cases is pretty straightforward (update vite or install an older plugin and use a vite.config.js).

As noted in #20227, we may want to add a migration step to add vite, but we don't need to add one for the plugins, if we go with this approach.

## How to test

CI should pass for all vite frameworks.

2022-12-14 23:13 UTC, JReinhold requested changes
Code changes looks good, but we should probably add an entry to MIGRATION.md

We might also want an automigration in this PR? I don't know.

2022-12-14 23:48 UTC, JReinhold approved these changes
Scratch that, vite was already a peer dep in 6.5, no migration nor automigration needed I think

2022-12-15 22:42 UTC, IanVS commented
I need to add an eslint ignore because the svelte plugin does not have a main in package.json.

2022-12-16 02:24 UTC, IanVS commented on code/frameworks/svelte-vite/src/preset.ts
> +  // eslint-disable-next-line import/no-unresolved
https://github.com/sveltejs/vite-plugin-svelte/issues/552

2022-12-16 07:07 UTC, ndelangen commented
https://github.com/storybookjs/storybook/pull/20294 does something similar 👍

2022-12-16 07:15 UTC, ndelangen approved these changes

2022-12-16 07:15 UTC, ndelangen commented on code/frameworks/react-vite/package.json
> +    "vite": "3 - 4"
```suggestion
    "vite": "^3.0.0 || ^4.0.0"
```

2022-12-16 12:29 UTC, IanVS commented
@ndelangen it looks like during one of the merges of `next`, we lost the fix for pinning react-docgen.  I've re-applied it here, and 🤞 that CI will be green now.

2022-12-16 12:56 UTC, shilman approved these changes
LGTM! @IanVS do we need to do a followup with some combination of:
- Documentation updates
- Automigration to automatically add a vite dep if you don't have it

2022-12-16 13:10 UTC, IanVS commented
@shilman we could, though I'm not entirely convinced it's necessary.  I think it makes sense to have the migration for react, since it's surprising to need react in a svelte project, but it's not surprising to need vite in a svelte-vite project.  Also, in 6.5, vite was a peer dependency, so this is not a change in 7.0.  My personal recommendation would be to avoid making our already-very-long mirgration doc even longer, and wait to see if we hear any confusion over it.  Personally I don't think we will.

2022-12-16 13:13 UTC, shilman commented
@IanVS WFM! Merging 🎉

2022-12-16 13:14 UTC, merged