Update MIGRATION.md
storybookjs/storybook pull request #20571
Opened 2023-01-11 10:39 UTC by valentinpalkovic

Issue:

## What I did

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

2023-01-11 14:08 UTC, shilman requested changes

2023-01-11 14:08 UTC, shilman commented on MIGRATION.md
> +- `@storybook/next`
```suggestion
- `@storybook/nextjs`
```

2023-01-11 18:48 UTC, valentinpalkovic commented
@shilman Thanks! Corrected!

2023-01-11 21:38 UTC, jonniebigodes approved these changes
Thanks for this @valentinpalkovic, all good on my end. Merge when able

2023-01-14 09:49 UTC, shilman approved these changes

2023-01-14 09:49 UTC, merged