add support for favicon.ico again
storybookjs/storybook pull request #20612
Opened 2023-01-13 14:45 UTC by ndelangen

Issue: https://github.com/storybookjs/storybook/issues/20487

## What I did

- resolve the favicon path in a preset-property
- pick the first one, if any is found, warn user, if we found multiple
- make the link tag injection work for both svg and ico

2023-01-13 19:15 UTC, ndelangen commented
I'd like to give this a manual test before merging

2023-01-15 07:49 UTC, valentinpalkovic approved these changes

2023-01-15 07:52 UTC, shilman requested changes
Generally LGTM!

2023-01-15 07:52 UTC, shilman commented on code/lib/core-server/src/presets/common-preset.ts
> +const defaultFavIcon = require.resolve('@storybook/core-server/public/favicon.svg');
```suggestion
const defaultFavicon = require.resolve('@storybook/core-server/public/favicon.svg');
```

2023-01-15 07:52 UTC, shilman commented on code/lib/core-server/src/presets/common-preset.ts
> +const defaultFavIcon = require.resolve('@storybook/core-server/public/favicon.svg');
Capitalization consistency 😄

2023-01-15 07:52 UTC, shilman commented on code/lib/core-server/src/presets/common-preset.ts
> +export const favicon = async (value: string, options: Options) => {
Can we please add unit tests for this?

2023-01-16 13:54 UTC, ndelangen commented on code/lib/core-server/src/presets/common-preset.ts
> +export const favicon = async (value: string, options: Options) => {
yes!

2023-01-16 15:19 UTC, merged