fix: convert casing on vue2 events to camel case in render fn
storybookjs/storybook pull request #20754
Opened 2023-01-23 20:59 UTC by fazulk

Issue: #20753

## What I did

Fix casing for vue2 events to be camelcased by default when using the default storybook render fn. 

## How to test

1. load vue2/vite sandbox. 
2. Add `this.$emit('also-clicked')` to line 51 of Button.vue
3. Remove the render function, line 8-12 from Button.stories.js
4. Add arg types `alsoClicked: { action: 'clicked' }` to argTypes
5. Error should be gone and should show event inside storybook actions.

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [x] Make sure to add/update documentation regarding your changes
- [x] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

2023-01-31 07:59 UTC, ndelangen commented on code/renderers/vue/src/render.ts
> +    eventsBinding = eventProps.map((name) => `@${name}="$props.${camelCase(name)}"`).join(' ');
```suggestion
    eventsBinding = eventProps.map((name) => `@${name}="$props['${name}"']`).join(' ');
```

2023-01-31 07:59 UTC, ndelangen commented on code/renderers/vue/src/render.ts
> +const camelCase = (str: string) => str.replace(/-([a-z])/g, (g) => g[1].toUpperCase());
```suggestion
```

2023-01-31 09:30 UTC, ndelangen commented
@fazulk thank you for contributing, we discussed this with the team, and we think a better solution would be to use bracket-notation to reference the property, instead of trying to convert it to something it might or might not be. It's less magic.

I left 2 comments with suggestion, could you have a look at applying them, and test if this indeed is a viable alternative? 🙏

2023-02-01 09:07 UTC, ndelangen approved these changes

2023-02-01 15:06 UTC, phunguyenmurcul commented on code/renderers/vue/src/render.ts
> +    eventsBinding = eventProps.map((name) => `@${name}="$props['${name}"']`).join(' ');
@ndelangen As far as I know Vue2 will convert kebab-case prop to camelCase props. so if you define `also-clicked` in `argTypes` or story `args`, you will see only `alsoClicked` in `props`

<img width="400" alt="Screenshot at Feb 01 22-03-39" src="https://user-images.githubusercontent.com/51897872/216080320-47aa0442-c523-468b-9cce-06ad623e8803.png">
<img width="366" alt="Screenshot at Feb 01 22-03-15" src="https://user-images.githubusercontent.com/51897872/216080343-e5d0f0d0-ef8b-476b-ab60-a3e72d409b69.png">

2023-02-01 20:10 UTC, fazulk commented
> @fazulk thank you for contributing, we discussed this with the team, and we think a better solution would be to use bracket-notation to reference the property, instead of trying to convert it to something it might or might not be. It's less magic.
> 
> I left 2 comments with a suggestion, could you have a look at applying them, and test if this indeed is a viable alternative? 🙏

@ndelangen , unfortunately that doesn't work. Because vue2 converts props from kebab-case to camelCase. the prop 'also-clicked' will be undefined, as @phunguyenmurcul pointed out. I tried the method you mentioned, by using `$props['some-event']` and it didn't work. Let me know if I should re-commit the changes made, or if you'd like to explore another solution, But because prop conversion to camel case is baked into vue -- i'm not sure if there is another route.

2023-02-02 11:00 UTC, ndelangen commented
OK, then yeah, we should change back to the code you committed before, sorry to make this more difficult then it needed to be.

2023-02-02 22:53 UTC, fazulk commented
@ndelangen Made an adjustment here which doesn't require mutating the key name of the event. 

Using the mutation to camelCase worked, but there was console errors for any events that weren't declared in `argTypes` or caught by the `argTypesRegex`. If you declared those, the errors went away. But you still needed to change them to camel case.

The work around is to check to see if the event is included in `$props` and not undefined. Then execute that function on the event. This works 100% of the time with `camelCasedEvents`

If that fails, then execute the function from initialArgs, which retains the original casing of the event. 

This allows the user to emit `this.$emit('something-happened')` and if our `argTypesRegex` isn't setup to catch it. The user can declare it:

```
argTypes: {
   'something-happened': { action: 'it really did' }
}
```

2023-02-03 15:34 UTC, ndelangen commented
@storybookjs/vue I'm inclined to merge this PR, can someone leave a review 🙏 Thanks!

2023-02-15 18:46 UTC, fazulk commented
Any update on when this might get looked at? This bug is the only thing thats preventing me from updating to storybook 7 ..

2023-02-15 22:42 UTC, chakAs3 commented
> Any update on when this might get looked at? This bug is the only thing thats preventing me from updating to storybook 7 ..

hi @fazulk  i will be reviewing your PR. we will sort out this today

2023-02-16 02:20 UTC, chakAs3 requested changes

2023-02-17 16:58 UTC, fazulk commented on code/renderers/vue/src/render.ts
> -    eventsBinding = eventProps.map((name) => `@${name}="$props.${name}"`).join(' ');
No problem, this was my original commit actually :)

2023-02-17 23:25 UTC, chakAs3 approved these changes

2023-02-17 23:25 UTC, merged