CLI: Install @storybook/testing-library@next
storybookjs/storybook pull request #20819
Opened 2023-01-28 17:10 UTC by IanVS

Issue: #

An older, incompatible version of `@storybook/testing-react` was being installed into 7.0 projects, which came along with old storybook dependencies like `@storybook/api@6.5`

## What I did

I made sure that we install the `next` version of `@storybook/testing-library`

## How to test

I'm not sure.

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [X] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

2023-01-28 19:11 UTC, jonniebigodes commented
@IanVS can you update the description and reference this [issue](https://github.com/storybookjs/storybook/issues/20529), I'd appreciate it.

2023-01-28 19:14 UTC, IanVS commented
@jonniebigodes Sorry, I don't understand what this has to do with that issue.  Can you explain now they're related?

2023-01-28 19:48 UTC, jonniebigodes commented
@IanVS, sorry for misleading you. I was looking at another item related to this and referenced it incorrectly :🤦

2023-01-30 10:09 UTC, yannbf approved these changes
LGTM! thanks Ian!

2023-01-30 10:11 UTC, yannbf requested changes
Oops, I celebrated too early. Thought the CI erros were from something else, but I noticed your branch is up to date with `next`. There's an issue going on in`sb init`:

```
 • Detecting project type. ✓
 • Adding Storybook support to your "Create React App" based project➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: @storybook/testing-library@^undefined isn't supported by any available resolver
    at zf.getResolverByDescriptor (/tmp/storybook/bench/cra-default-ts/.yarn/releases/yarn-3.3.1.cjs:391:1647)
    at zf.bindDescriptor (/tmp/storybook/bench/cra-default-ts/.yarn/releases/yarn-3.3.1.cjs:391:1036)
    at Z (/tmp/storybook/bench/cra-default-ts/.yarn/releases/yarn-3.3.1.cjs:439:6905)
```

2023-01-30 12:39 UTC, IanVS commented
Thanks @yannbf, turns out we can't use tags, based on the way that we get the latest version that supports the constraint we specify.

2023-01-30 14:12 UTC, kylegach approved these changes
Looks good; thanks!

2023-01-30 14:14 UTC, yannbf approved these changes

2023-01-30 14:15 UTC, merged