feat: added satisfies to ConfigFile [csf-tools].
storybookjs/storybook pull request #20936
Opened 2023-02-05 10:39 UTC by zhyd1997

Closes #20935 

## What I did

AST comparison:
<img width="567" alt="Screenshot 2023-02-05 at 18 35 03" src="https://user-images.githubusercontent.com/31362988/216814211-46565d9f-22f8-4e79-9ca6-418f9863799c.png">
<img width="567" alt="Screenshot 2023-02-05 at 18 36 25" src="https://user-images.githubusercontent.com/31362988/216814213-699f455b-e54a-4658-90ff-5827c0a19eca.png">

## How to test

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

2023-02-05 10:41 UTC, zhyd1997 commented on code/lib/csf-tools/src/ConfigFile.ts
> +            expression.properties.forEach((p: t.ObjectProperty) => {
AST comparison:
<img width="567" alt="Screenshot 2023-02-05 at 18 35 03" src="https://user-images.githubusercontent.com/31362988/216814211-46565d9f-22f8-4e79-9ca6-418f9863799c.png">
<img width="567" alt="Screenshot 2023-02-05 at 18 36 25" src="https://user-images.githubusercontent.com/31362988/216814213-699f455b-e54a-4658-90ff-5827c0a19eca.png">

2023-02-05 11:34 UTC, shilman approved these changes
Nice one @zhyd1997 !! Thanks for this 🙏

2023-02-05 11:43 UTC, zhyd1997 commented
@shilman 

I am not familiar with the codebase, so please review the PR carefully to make sure it will not break something, If you have any questions , please let me know.

2023-02-05 11:51 UTC, shilman requested changes
I didn't review closely enough. LMK what you think about this

2023-02-05 11:51 UTC, shilman commented on code/lib/csf-tools/src/ConfigFile.ts
> +              ? (decl.expression as Extract<t.Expression, t.ObjectExpression>)
I'm suspicious of this line. I think it should be something like:

```ts
          let decl =
            t.isIdentifier(node.declaration) && t.isProgram(parent)
              ? _findVarInitialization(node.declaration.name, parent)
              : node.declaration;
          if(t.isAsExpression(decl) || t.isTSSatisfiesExpression(decl)) {
            decl = decl.expression;
          }
          if(t.isObjectExpression(decl)) {
            ... 
          } else {
            logger.warn(`Unexpected ${JSON.stringify(node)}`);
          }
 ```
 
The problem with the current code is that it assumes the satisfies expression is an ObjectExpression, which might not be the case. For example:

```ts
export default 'foo' satisfies Bar;
```

2023-02-05 15:04 UTC, stevezhu commented
Nice! Thanks for implementing this!

2023-02-06 07:05 UTC, yannbf approved these changes
Looks great to me, thanks @zhyd1997 !!

2023-02-06 07:10 UTC, shilman approved these changes

2023-02-06 07:11 UTC, merged