Documentation: Update main.js exports migration
storybookjs/storybook pull request #21220
Opened 2023-02-23 10:51 UTC by yannbf

Added some notes about types in js files

2023-02-23 11:28 UTC, shilman commented on MIGRATION.md
> +const config: StorybookConfig = {
```suggestion
const config = {
```

2023-02-23 11:29 UTC, shilman requested changes
LGTM to me except for what I think is a typo

2023-02-23 11:30 UTC, JReinhold approved these changes

2023-02-23 11:30 UTC, JReinhold commented on MIGRATION.md
> +In Javascript projects using `main.js`, it's also possible to use the `StorybookConfig` type (for autocompletion, not type safety), via the JSDoc @type tag:
```suggestion
In JavaScript projects using `main.js`, it's also possible to use the `StorybookConfig` type (for autocompletion, not type safety), via the JSDoc @type tag:
```

2023-02-24 08:38 UTC, yannbf commented on MIGRATION.md
> +const config: StorybookConfig = {
Great catch!!

2023-02-24 08:38 UTC, yannbf commented on MIGRATION.md
> +In Javascript projects using `main.js`, it's also possible to use the `StorybookConfig` type (for autocompletion, not type safety), via the JSDoc @type tag:
thanks!

2023-02-24 16:49 UTC, shilman approved these changes

2023-02-24 18:55 UTC, merged