Docs: Ppdate Vite docs to v7
storybookjs/storybook pull request #21295
Opened 2023-02-28 13:30 UTC by JReinhold

## What I did

Minor changes to the Vite docs:

1. Describe how Vite now automatically merges configuration with the default `vite.config.js`
2. Remove section about `svelteOptions` as that is no longer supported
3. Included Svelte in list of frameworks with arg type inference.

There's still more work to be done, that I've left out of this PR to move this forward quickly:

1. Update builder docs to no longer mention `@storybook/builder-vite` as that is configured with the framework instead. this is also applicable for the Webpack docs.
2. Describe that you can customize the path to your Vite config. introduced in https://github.com/storybookjs/storybook/pull/20681, described at https://github.com/storybookjs/storybook/tree/next/code/lib/builder-vite#customize-vite-config

## How to test

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

2023-02-28 14:16 UTC, IanVS approved these changes
Thanks for the cleanup, I could have sworn I updated these earlier, but maybe that was just in the README file.  I had a few small suggestions, but no blockers.

2023-02-28 14:16 UTC, IanVS commented on docs/builders/vite.md
> +Out of the box, Storybook's Vite builder includes a set of configuration defaults for the supported frameworks, merged with your default `vite.config.js` configuration. We recommend keeping your Stor
```suggestion
Out of the box, Storybook's Vite builder includes a set of configuration defaults for the supported frameworks, merged with your `vite.config.js` configuration file. We recommend keeping your Storybook Vite configuration the same as your app Vite configuration by only making changes to your `vite.config.js`. But you can also fine-tune the configuration specifically for Storybook by adjusting your Storybook configuration file (`.storybook/main.js|ts`) and providing the following:
```

2023-02-28 14:16 UTC, IanVS commented on docs/snippets/common/storybook-vite-builder-aliasing.js.mdx
>          include: ['storybook-dark-mode'],
We might want to pick a different addon, as far as I can tell this one is unneeded in v7 and is not compatible either.

2023-02-28 15:26 UTC, kylegach commented on docs/builders/vite.md
> +The asynchronous function`viteFinal` receives a `config` object with the default builder configuration and returns the updated configuration.
```suggestion
The asynchronous function `viteFinal` receives a `config` object with the default builder configuration and returns the updated configuration.
```

2023-02-28 15:31 UTC, kylegach approved these changes
Looks like there's some minor comments, but I'll go ahead and approve.

2023-02-28 16:10 UTC, jonniebigodes requested changes
@JReinhold when you're able can you apply the change I've mentioned? Thanks in advance.

2023-02-28 21:27 UTC, JReinhold commented on docs/builders/vite.md
> +Out of the box, Storybook's Vite builder includes a set of configuration defaults for the supported frameworks, merged with your `vite.config.js` configuration file. We recommend keeping your Storybo
Thanks. I changed it to something similar, but wording that doesn't talk about configuration _changes_, but rather configuration in general, changed or static. I don't think it makes sense to think of them as changes that needs to be picked up.

2023-03-01 14:25 UTC, jonniebigodes approved these changes
@JReinhold, thanks for addressing the feedback so promptly. Appreciate it. Regarding your comment, we can always circle back to this and update it later on. Going to approve this to unblock you.

2023-03-01 14:27 UTC, merged