fix(angular): source preview for angular stories does not show proper props values
storybookjs/storybook pull request #21609
Opened 2023-03-14 21:22 UTC by sheriffMoose

Closes #21066

## What I did

* [x] enforce using brackets as a best practice for inputs in angular components.
* [x] fix values showing as `false` because they don't have `enum` type.
* [x] display string props within single quotes pair.
* [x] display object & array items as JSON strings instead of just a duplicate of `propertyName`.

## Before
![image](https://user-images.githubusercontent.com/1110191/225138039-e8294b36-688e-4ebd-b363-c4e376304da8.png)

## After
![image](https://user-images.githubusercontent.com/1110191/225138095-78210d72-3206-4ca9-84f0-fd50e9d8cc79.png)

## How to test

* [ ] CI Passes

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [x] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

2023-03-15 10:15 UTC, valentinpalkovic requested changes

2023-03-15 10:15 UTC, valentinpalkovic commented on code/frameworks/angular/src/client/angular-beta/ComputesTemplateFromComponent.ts
> +      templateValue = JSON.stringify(value).replace(/"/g, "'");
I don't think this is a safe operation.

Let's consider the following object:

```jsx
const obj = {"hello":"This is a nice 'sentence'"}
```

JSON.stringify will convert it to:

```jsx
const value = `{"hello":"This is a nice 'sentence'"}`
```

The replace operation would output:
```jsx
const replaced = "{'hello':'This is a nice 'sentence''}"
```

2023-03-16 10:25 UTC, sheriffMoose commented on code/frameworks/angular/src/client/angular-beta/ComputesTemplateFromComponent.ts
> +        .replace(/'/g, '\u2019')
done

2023-03-16 10:41 UTC, valentinpalkovic approved these changes

2023-03-17 07:00 UTC, merged