React decorators can conditionally render children
storybookjs/storybook pull request #22336
Opened 2023-05-01 21:38 UTC by redbugz

Fixes #15223
Custom preview-api hooks assumed that all decorators were always rendered however if a custom decorator conditionally rendered it's children, then not all decorators would get rendered, especially jsxDecorator. This would result in the error
"Rendered more hooks than during the previous render." This removes the assumption that all decorators render every time and relies on each decorator to register itself during MOUNT phase which is handled when each decorator goes through `hookify`

Closes #

## What I did

## How to test

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

2023-05-03 01:47 UTC, tmeasday requested changes
I think this seems reasonable given my (limited) understanding of the motivation of the hook restrictions. Similar to the way that React can scope hooks to a single component, we can scope hooks to a single decorator, correct?

@redbugz -- I think it would be good to add a "template story" to `preview-api` and a test (either e2e or just an interaction test on the story) that demonstrates the error no longer occurs.

2023-05-03 15:42 UTC, redbugz commented
> @redbugz -- I think it would be good to add a "template story" to `preview-api` and a test (either e2e or just an interaction test on the story) that demonstrates the error no longer occurs.

Sure I can give that a try. I'm still learning this codebase so I'm not sure where that would go. Poking around, would it be adding a story to https://github.com/storybookjs/storybook/blob/next/code/renderers/react/template/stories/decorators.stories.tsx or https://github.com/storybookjs/storybook/blob/next/code/renderers/react/template/stories/hooks.stories.tsx or a new file in that location or a different location like adding a templates/stories dir inside of https://github.com/storybookjs/storybook/tree/next/code/lib/preview-api?

Would an e2e test go here https://github.com/storybookjs/storybook/blob/next/code/e2e-tests/preview-web.spec.ts or somewhere else?

2023-05-16 01:38 UTC, tmeasday commented
@redbugz any luck with this? I can take a look if you are stuck.

2023-05-18 04:25 UTC, tmeasday commented
@redbugz I created the test here: https://github.com/storybookjs/storybook/commit/c718894fd995baa821bf9c3a1a431250f9412f45

2023-05-18 22:24 UTC, redbugz commented
> @redbugz I created the test here: [c718894](https://github.com/storybookjs/storybook/commit/c718894fd995baa821bf9c3a1a431250f9412f45)

Thank you. I got busy with a few things and was hoping to get back to this in a few days.

2023-05-19 01:40 UTC, tmeasday commented
@redbugz I'm happy to merge this if you cherry pick that test across (and it passes :) )

2023-05-28 23:39 UTC, tmeasday approved these changes

2023-05-28 23:40 UTC, tmeasday commented
Hmm. It looks like returning `null` from the decorator doesn't work in angular, lit and vue. @shilman let's figure out a pattern to get this test working.

2023-05-29 12:46 UTC, tmeasday commented
@kasperpeulen @chakAs3 I'll note that I looked at this story in vue3 and it isn't actually possible to conditionally render there. Even with the story in this PR, the second decorator always gets rendered.

We should probably write some proper stories/tests for decorator behaviour like this, and get all renderers to conform to a common contract for sanity's sake.

2023-05-31 12:43 UTC, chakAs3 commented
> Hmm. It looks like returning `null` from the decorator doesn't work in angular, lit and vue. @shilman let's figure out a pattern to get this test working.

yes at least for vue should return modified story, but I can open PR that handles the null/undefined  value

2023-06-01 01:51 UTC, tmeasday commented
> Hi @tmeasday you are right I think we should skip this for vue ( renderer they don't use useEffect hook ).
for test purpose why don't we move   const [counter, setCounter] = useState(0); up to have function scope, and just use setCounter, avoiding using useEffect

@chakAs3 I think you misunderstand. This is not testing vue hooks, it is testing the *storybook hooks* which should work for every framework. So I wouldn't want to skip the test in vue.

My problem is actually that the test won't fail prior to this change in vue because it isn't possible to actually conditionally render in a decorator in the first place. This seems wrong to me but is out of scope of this PR.

>  yes at least sure for vue should return modified story, but I can open a PR that handles the null/undefined value.

I disagree. **It should be possible to not render the story at all in a decorator**. I made it work, but the interesting (broken?) part is the intervening decorator (which isn't rendered) still gets called.

> is it normal for this PR to have over 1500 files changed? 

Definitely not, something weird has happened when I updated the branch.

2023-06-01 18:31 UTC, redbugz commented
Sorry, I'm back from vacation now, thanks to everyone for helping. I'm still trying to understand how the repo works, I have the latest code with the new template story. I have a few days I can help now, so willing to do whatever I can to help finish things up.
A few things I am noticing that I could use help with.

When I create a new sandbox, I am not getting the new templated story in that sandbox, even after I do all the steps in `yarn task` that I think I need, even `Publish the packages of the monorepo to an internal npm server (publish)`, it's not clear to me how the sandboxes are created to now how to get the new code to show up in a new sandbox without copy/paste.
If I copy/paste the Hooks story into the sandbox and run it in dev mode, then Interactions tab shows nothing available on the new `Hooks` story even though there is a `play` function. I noticed most of the other play functions have an expectation, so when I add any trivial `expect` to the play function, then the Interactions tab now show up in the story. So I think we just need to add some kind of expect at the end of the story for the play to work?

It's also not clear to me how the play function is executed by tests, or even how to run the tests locally against these templated stories, and you mentioned a chromatic test which I'm not familiar with and I get an error trying to run the chromatic tests locally. Do those just run during CI?

2023-06-02 00:56 UTC, tmeasday commented
Hi @redbugz you should be able to view these stories if you just run `yarn start` and browse to ...

> If I copy/paste the Hooks story into the sandbox and run it in dev mode, then Interactions tab shows nothing available on the new Hooks story even though there is a play function.

This is because only certain testing library commands are "instrumented" (so show up in the panel). Random stuff like emitting on the channel isn't. That's OK, the play function is still running.

> It's also not clear to me how the play function is executed by tests, or even how to run the tests locally against these templated stories, and you mentioned a chromatic test or an interaction test which I'm not familiar with and I get an error trying to run the chromatic tests locally. Do those just run during CI?

Yes, Chromatic has run against all the sandboxes in CI.

The interaction tests is just the play function. To run it, you can just navigate to the story.

> Also all of the CI checks seem to be failing on storyshots-puppeteer, not sure what I need to do to get those resolved, just continue to merge next into this branch?

Yeah the failures on this branch seem unrelated, it was working earlier, I'll dig into it.

2023-06-02 01:27 UTC, tmeasday commented
This story is just not rendering consistently across frameworks. @shilman I'm not sure how concerned to be. TLDR: it seems like decorators are a bit of an inconsistent mess between renderers.

2023-06-05 11:01 UTC, tmeasday commented
@shilman OK, thanks for bearing with me. So this story "decorators: Hooks" is supposed to render `component project text`. It is good that it is not erroring in any framework (it would have before, but it is inconsistent in Vue:

- in Vue2 it renders blank, perhaps it isn't possible render the `originalStoryFn`? eg https://www.chromatic.com/test?appId=633bec4b9116cbe3b986bd53&id=64794476758af17ea832047e
- In Vue 3 it renders `story component project text` -- like it's rendering all decorators no matter what - e.g https://www.chromatic.com/test?appId=632066d4ff4ffcc927dd0bba&id=64794459f8b7ab17a31e605b

2023-06-05 11:06 UTC, shilman commented
@tmeasday I spoke with @kasperpeulen about it and he's going to take a quick look at the Vue failures. My gut says we should forget about the Vue2 case and diagnose the Vue3 case / fix it if it's an easy fix.

2023-06-06 17:38 UTC, shilman commented
@kasperpeulen i'd say mark it with a FIXME and let's move on

2023-06-07 01:20 UTC, tmeasday commented
I guess my final question is what is the best way to "approve" the above 5 or so vue2/3 stories that are rendering "wrong" (or at least inconsistent with the other renderers). It feels like we should comment somewhere about it.

2023-06-07 05:37 UTC, shilman commented
@tmeasday I have created https://github.com/storybookjs/storybook/issues/22945 and also commented above the story in question with a reference to the code. Merging this.

2023-06-07 12:44 UTC, shilman commented
Good call @kasperpeulen . Done!

2023-06-07 12:45 UTC, merged

2023-06-09 06:45 UTC, chakAs3 commented
Hi. @tmeasday @shilman @kasperpeulen, Sorry I just saw this conversation (I hate GitHub notifications ).
I got some time this morning to open PR #22994, it may solve all this mystery.