Build: Migrate @storybook/channel-websocket to strict TS
storybookjs/storybook pull request #22364
Opened 2023-05-02 21:58 UTC by EDuToit

Closes #

## What I did
Migrate @storybook/channel-websocket to strict-ts

## How to test

## Checklist
- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

2023-05-03 10:52 UTC, kasperpeulen requested changes
Thanks! I left some feedback :)

2023-05-03 10:52 UTC, kasperpeulen commented on code/lib/channel-websocket/src/index.ts
> +  private socket?: WebSocket;
I would prefer inlining the connect function in the constructor, to show TS that it is always defined. As it is private, it is really only used in the constructor anyway.

2023-05-03 10:52 UTC, kasperpeulen commented on code/lib/channel-websocket/src/index.ts
> +      }
I think we expect a handler to be set here. Could you do a runtime assertion with `tiny-invariant`?
```ts
invariant(this.handler, "WebsocketTransport handler should be set");
```

2023-05-04 08:14 UTC, kasperpeulen approved these changes
I rolled bock one socket null check that is not neccesary anymore, LGTM now!

2023-05-04 09:32 UTC, merged

2023-05-04 09:40 UTC, EDuToit commented
#22176