Chore:(Docs) Add TS version of Svelte snippet(get-started)
storybookjs/storybook pull request #22433
Opened 2023-05-07 02:52 UTC by miily8310s

Closes #

## What I did

Add TS version of Svelte snippet(only on get-started page)

## How to test

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [x] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

2023-05-11 21:50 UTC, jonniebigodes requested changes
@miily8310s, thanks for taking the time to put together this pull request and complement our existing examples. Appreciate it greatly 🙏 ! I left a couple of items for you to look at when you have a chance. For context, I'm aware that the existing Javascript variations for Svelte mirroring this pull request include explicit `render` functions, but for these examples, we don't need them, and if you're ok we can adjust them on a follow-up pull request. Would you be interested in it?

Let me know, and we'll go from there.

Looking forward to hearing from you and getting this one in.

Have a great day.

Stay safe

2023-05-11 21:50 UTC, jonniebigodes commented on docs/snippets/svelte/button-story-with-args.ts-4-9.mdx
> +  }),
@miily8310s, we can drop the render function and comment in this example and the pre-TS variation with the same name.

2023-05-11 21:50 UTC, jonniebigodes commented on docs/snippets/svelte/histogram-story.ts-4-9.mdx
> +  }),
@miily8310s the same applies here. We can drop the render function and comment for this and the pre-TS-4.9 variation

2023-05-11 21:50 UTC, jonniebigodes commented on docs/snippets/svelte/your-component.ts-4-9.mdx
> +  }),
@miily8310s same rule applies here and for the follow-up pre-TS-4.9 variation

2023-05-12 00:01 UTC, miily8310s commented
> if you're ok we can adjust them on a follow-up pull request. Would you be interested in it?

OK

2023-05-12 15:12 UTC, jonniebigodes commented
@miily8310s, that's great to hear. Glad that you're willing to do it 🙏 ! 

Let me know once you've addressed the feedback so that we can get this one in and go from here for the next one.

Once again, thanks for this great contribution ❤️

2023-05-14 11:16 UTC, miily8310s commented
@jonniebigodes 

> Let me know once you've addressed the feedback so that we can get this one in and go from here for the next one.

I'm sorry for responding slowly. I'd reflected your feedback, please check my modification!

2023-05-15 14:43 UTC, jonniebigodes commented
@miily8310s, no need to be sorry whatsoever. I understand it. I checked the changes, and they're great. Once again thanks for addressing the feedback so promptly. Appreciate it 🙏 ! I'm going to go ahead and merge this one. And if you're interested in contributing to the changes for the JS versions, let me know once the pull request is up, and I'll be more than glad to follow up with you and we'll go from there.

Hope you have a great week.

Stay safe

2023-05-15 14:44 UTC, merged