doc: link 'Image, fonts, and assets' to static `preview-head.html`; enhance code snippet to demonstrate relative pathing
storybookjs/storybook pull request #22688
Opened 2023-05-22 15:50 UTC by usrrname

It seems like there's frequent enough questions about how to load fonts in stories, and devs aren't entirely connecting the existing doc to the use of `preview-head.html` to serve their own static fonts.

Discord issues:
https://discord.com/channels/486522875931656193/1110070593056952351/1110070593056952351
https://discord.com/channels/486522875931656193/1097070271040589865/1097070271040589865
https://discord.com/channels/486522875931656193/1100050706196598964/1100050706196598964
https://discord.com/channels/486522875931656193/1083367049021104188/1083367049021104188
https://discord.com/channels/486522875931656193/1089727645685645342/1089727645685645342

Related:

https://github.com/storybookjs/storybook/issues/15507
https://github.com/storybookjs/storybook/issues/15826
https://github.com/storybookjs/storybook/issues/14644

(Not sure it "Closes" any of those but I think the gap here is making the connection to the resource and how `preview-head.html` acts like it's already referencing assets bundled in `storybook-static` imo)

## What I did

doc: 'Images, fonts, and assets' (`images-and-assets.md`) now reference code snippet for importing and referencing static fonts in `preview-head.html` (`common/storybook-preview-head-example.html.mdx`)

improve code snippet commentary about relative path referencing of static files.

## How to test

`yarn lint`

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [x] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

2023-05-22 17:21 UTC, usrrname commented on docs/configure/images-and-assets.md
> +Example:
This line can be axed; I felt compelled to tie the idea of static-imports having relative pathing to above the section below, but I can see how this is now like a dangling line.

2023-05-23 17:28 UTC, kylegach requested changes
Thanks, @usrrname! This is, overall, a great improvement! I left some comments and suggestions for you to address before merging.

2023-05-23 17:28 UTC, kylegach commented on docs/configure/images-and-assets.md
> -<!-- prettier-ignore-end -->
Please ensure that the `<CodeSnippets />` are still wrapped with these prettier comments (with a blank line in-between).

2023-05-23 17:28 UTC, kylegach commented on docs/configure/images-and-assets.md
> +You've placed the fonts in your static folder, now what?
😄 Love it. It's not quite the tone of the rest of ours docs, though. What about this?

```suggestion
After configuring Storybook to server assets from your static folder, you can reference those assets in Storybook. For example, you can reference and apply a custom font in your stories.
```

2023-05-23 17:28 UTC, kylegach commented on docs/configure/images-and-assets.md
> +<!-- prettier-ignore-end -->
Please remove this, per my prior comment.

2023-05-23 17:42 UTC, usrrname commented on docs/snippets/common/storybook-preview-head-example.html.mdx
> +<link rel=”preload” href=”public/my-font.woff2” />
That example here presumes that someone has a fonts folder inside `public/` right?

2023-05-23 17:43 UTC, usrrname commented on docs/snippets/common/storybook-preview-head-example.html.mdx
> +<link rel=”preload” href=”public/my-font.woff2” />
Great catch re: the correct property

2023-05-23 20:24 UTC, kylegach commented on docs/configure/images-and-assets.md
> +After configuring Storybook to server assets from your static folder, you can reference those assets in Storybook. For example, you can reference and apply a custom font in your stories.
Made a typo. 🤦‍♂️ 

```suggestion
After configuring Storybook to serve assets from your static folder, you can reference those assets in Storybook. For example, you can reference and apply a custom font in your stories.
```

2023-05-23 20:25 UTC, kylegach approved these changes
This looks great! Thanks again for the thoughtful addition, @usrrname!

2023-05-24 12:55 UTC, merged

2023-05-24 13:24 UTC, usrrname commented
Woohoo! Thanks a lot! This is going to help folks at my company too!