Fix `managerHead` configuration possibility in `main.ts`
storybookjs/storybook pull request #22701
Opened 2023-05-23 13:15 UTC by ndelangen

Closes https://github.com/storybookjs/storybook/issues/22597

## What I did

I moved the code to load manager-head.html to a preset value, then get the value needed by the builder-manager via presrt.apply.
This allows the user to set this value via main.ts if they so desire.

I also added this as a valid presetProperty in `StorybookConfig` interface.

## How to test

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] If this PR should be tested against many or all sandboxes,
      make sure to add the `ci:merged` or `ci:daily` GH label to it.
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

2023-05-23 15:42 UTC, shilman requested changes
I added a "how to test" section to the description if we want to support the 6.5 API. The default implementation should read the value of `manager-head.html` if it exists and return its contents.

2023-05-23 20:27 UTC, ndelangen commented
> The default implementation should read the value of manager-head.html if it exists and return its contents.

That's what it does, of course..
Am I missing something?

2023-05-24 00:04 UTC, shilman commented
@ndelangen it just returns the filename. It does not return the contents of the file. Pleas read my "how to test" addition to the PR description

2023-05-24 07:24 UTC, ndelangen commented
Understood, I'll fix it.

2023-05-24 07:55 UTC, ndelangen commented
ok, fixed, and used your steps on how to test:
![Screenshot 2023-05-24 at 09 55 25](https://github.com/storybookjs/storybook/assets/3070389/8772bc97-c13e-4130-8242-8dbea706b2d4)

2023-05-24 08:23 UTC, shilman approved these changes

2023-05-24 08:23 UTC, merged