Migrate mono-repo dependency versions to use yarn workspace syntax
storybookjs/storybook pull request #23572
Opened 2023-07-24 08:04 UTC by valentinpalkovic

Closes N/A

## What I did

- Migrated mono-repo dependency versions to use yarn workspace syntax

## How to test

## Checklist

- [ ] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests)
- [ ] Make sure to add/update documentation regarding your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

#### Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below.

`["cleanup", "BREAKING CHANGE", "feature request", "bug", "build", "documentation", "maintenance", "dependencies", "other"]`

2023-07-25 07:57 UTC, ndelangen commented
Let's discuss today @valentinpalkovic

2023-07-25 08:18 UTC, JReinhold requested changes
> yarn npm publish would call internally yarn pack. So this would be a win. Unfortuately, it doesn't support the same CLI arguments then npm publish. Therefore first yarn pack is called to create a package.tgz per package, and with npm publish package.tgz this package is taken to publish to npm. Therefore, npm isn't responsible anymore to build the package. It only takes the tarball archive and publishes it.

I don't really follow this. If `yarn npm publish` already runs `yarn pack`, why do you want to run `npm publish` separately? You say that _"it doesn't support the same CLI arguments then npm publish"_`, but as far as I can see you don't supply any other arguments other than the `.tgz` file, which I would think wouldn't be needed at all if you just used `yarn npm publish`?

2023-07-25 08:18 UTC, JReinhold commented on scripts/release/publish.ts
> +  const command = `yarn workspaces foreach --parallel --no-private --verbose exec "yarn pack && npm publish ./package.tgz --tolerate-republish --tag ${tag} && rm package.tgz"`;
I'm pretty sure this change would mean that we need to change the `YARN_NPM_AUTH_TOKEN` env var to just `NPM_TOKEN` [here](https://github.com/storybookjs/storybook/blob/valentin/migrate-version-to-use-workspace-syntax/.github/workflows/publish.yml#L107).

2023-07-25 08:24 UTC, valentinpalkovic commented
> 

You're right! For the actual release, we might be able to switch to `yarn npm publish`. But I was referencing this code https://github.com/storybookjs/storybook/pull/23572/files#diff-f350f808916daeed26ed59e8d3d6be02aff71db58dd04ce8dcda9ae280dbb537L73-R73. So for verdaccio it seemed to be complicated to switch to `yarn npm publish`. I tried it, but already setting up the Verdaccio registry seemed to not be worth to switch to `yarn npm publish`.

2023-07-25 08:41 UTC, JReinhold commented
> You're right! For the actual release, we might be able to switch to `yarn npm publish`. But I was referencing this code [#23572 (files)](https://github.com/storybookjs/storybook/pull/23572/files#diff-f350f808916daeed26ed59e8d3d6be02aff71db58dd04ce8dcda9ae280dbb537L73-R73). So for verdaccio it seemed to be complicated to switch to `yarn npm publish`. I tried it, but already setting up the Verdaccio registry seemed to not be worth to switch to `yarn npm publish`.

Oh I see what you mean. Yeah all of this makes sense to me.

2023-07-25 11:20 UTC, ndelangen approved these changes

2023-07-26 09:09 UTC, JReinhold approved these changes

2023-07-27 08:08 UTC, merged