Update Number.js
storybookjs/storybook pull request #2371
Opened 2017-11-25 14:13 UTC by lifeiscontent

Fix inconsistency in number API

fix step,min,max attributes in number type

Issue:

## What I did

Fixed inconsistency in number type.

## How to test

when setting the options of a number, the step,min,max attributes now get applied.

Is this testable with jest or storyshots? Yes, but I didn't write a test.

Does this need a new example in the kitchen sink apps? No.

Does this need an update to the documentation? Not really, but I could add an example.

If your answer is yes to any of these, please make sure to include it in your PR.

2017-11-25 14:23 UTC, Hypnosphi commented
> Does this need a new example in the kitchen sink apps

Actually, I think it does. Please add one here: https://github.com/storybooks/storybook/blob/master/examples/cra-kitchen-sink/src/stories/addon-knobs.stories.js

You may need to run `yarn jest -u` to update storyshots after that

2017-11-25 16:24 UTC, ndelangen commented
Thank you for this PR @lifeiscontent !

@Hypnosphi Looks like the min,max,step was already in the example?
https://github.com/storybooks/storybook/blob/master/examples/cra-kitchen-sink/src/stories/addon-knobs.stories.js#L52

2017-11-25 16:36 UTC, Hypnosphi commented
@ndelangen we need the same but without `range: true`

2017-11-26 13:17 UTC, lifeiscontent commented
@Hypnosphi how do I run the kitchen sink example?

I tried the following.

```
yarn
yarn bootstrap # and selected core and examples
cd storybook/examples/cra-kitchen-sink
yarn storybook
```

but I get issues saying none of the storybook modules exist.

2017-11-26 13:19 UTC, lifeiscontent commented
@Hypnosphi updated!

2017-11-26 13:22 UTC, Hypnosphi commented on examples/cra-kitchen-sink/src/stories/addon-knobs.stories.js
> +  .add('tweaks static values via range', () => {
This example includes a lot of other knobs

2017-11-26 13:24 UTC, Hypnosphi requested changes

2017-11-26 13:24 UTC, Hypnosphi commented on examples/cra-kitchen-sink/src/stories/addon-knobs.stories.js
> +  .add('tweaks static values via range', () => {
Let’s add min/max/step to `dollars` below instead of duplicating the example

2017-11-26 13:25 UTC, Hypnosphi commented on examples/cra-kitchen-sink/src/stories/addon-knobs.stories.js
> +  .add('tweaks static values via range', () => {
Please run `yarn jest -u` after that

2017-11-26 14:08 UTC, lifeiscontent commented
@Hypnosphi updated.

2017-11-26 14:56 UTC, Hypnosphi commented
Ok looks like it passes as is. I'll be to test the example manually in a few hours

2017-11-26 19:36 UTC, Hypnosphi approved these changes

2017-11-26 19:41 UTC, merged