Fix type checking.
storybookjs/storybook pull request #23932
Opened 2023-08-23 17:08 UTC by mastrzyz

## What I did

- Fix function signature in PNPProxy UT
- Fix type for `handleProp` test

## Checklist for Contributors

### Testing

#### The changes in this PR are covered in the following automated tests:
- [x] compiler 
- [x] unit tests

<img width="855" alt="image" src="https://github.com/storybookjs/storybook/assets/37447884/06449348-93e4-4935-81d8-e3ba629789ff">
 
<img width="704" alt="image" src="https://github.com/storybookjs/storybook/assets/37447884/d7b4d28e-4b6b-4faa-9e84-33bd45bd2e26">

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

2023-08-24 07:42 UTC, kasperpeulen approved these changes
LGTM!

2023-08-28 15:21 UTC, ndelangen requested changes

2023-09-19 09:29 UTC, yannbf commented
Hey @ndelangen would you mind checking this out whenever you have time? Thanks!


_It might take some time as we are quite busy, we really appreciate your efforts and patience <3_

2023-09-19 15:59 UTC, ndelangen approved these changes

2023-09-19 15:59 UTC, merged