Edited template of search box result item to fix overflow text in row
storybookjs/storybook pull request #2419
Opened 2017-12-03 14:50 UTC by jozefpetro

Issue: #2183 

## What I did

- fixed overflow in row when name of story is too long as you can see in the pictures
<img width="440" alt="screen shot 2017-12-03 at 23 22 34" src="https://user-images.githubusercontent.com/15748491/33526374-a331354c-d883-11e7-87a8-e09d8369c272.png">
<img width="445" alt="screen shot 2017-12-03 at 23 25 45" src="https://user-images.githubusercontent.com/15748491/33526375-a3546ff8-d883-11e7-8824-0bed25b49bd3.png">

## How to test
- bootstrap everything
- open cra-kitchen-sink storybook
- cmd+shift+p on mac to open searchbox or use win equivalent hotkey
- type 'saa' in searchbox

Is this testable with jest or storyshots?
- not really sure about this one, maybe it's not necessary for this ?

2017-12-04 22:40 UTC, Hypnosphi requested changes
Let's add `text-align: right` to the second `p`

2017-12-04 22:40 UTC, Hypnosphi commented on lib/ui/src/modules/ui/components/search_box.js
> +        <p style={{ opacity: 0.5, margin: 0, paddingLeft: 10 }}>
Let's add `text-align: right` here

2017-12-05 03:30 UTC, jozefpetro commented on lib/ui/src/modules/ui/components/search_box.js
> +        <p style={{ opacity: 0.5, margin: 0, paddingLeft: 10 }}>
Thanks for reviewing !

2017-12-05 13:31 UTC, Hypnosphi approved these changes

2017-12-05 13:46 UTC, merged