Expand ArgTypes's InputType
storybookjs/storybook pull request #24331
Opened 2023-09-29 03:14 UTC by SadScream

Closes #24174

## What I did
Redefined the InputType so that it conforms to the [documentation](https://storybook.js.org/docs/angular/api/arg-types#argtypes)

## Checklist for Contributors

### Testing

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

2023-09-29 23:33 UTC, noahgregory-basis requested changes
A good start, but I think some changes should be made.

2023-09-29 23:33 UTC, noahgregory-basis commented on code/lib/types/src/modules/csf.ts
> +
Is using `Extract` really the best way to do this?

2023-09-29 23:33 UTC, noahgregory-basis commented on code/lib/types/src/modules/csf.ts
> +export type InputTypeOverride = InputType & {
Calling it `InputTypeOverride` feels like a temporary name. It should maybe be changed.

2023-09-29 23:33 UTC, noahgregory-basis commented on code/lib/types/src/modules/csf.ts
> +        labels?: { [option: string]: string };
Does any `ControlType` allow for the `labels` property?

2023-09-29 23:33 UTC, noahgregory-basis commented on code/lib/types/src/modules/csf.ts
> +  InputTypeOverride as InputType,
Don't export from here and require the mess of imports above. Just remove the original export and export it separately (see next comments).

```suggestion
```

2023-09-29 23:33 UTC, noahgregory-basis commented on code/lib/types/src/modules/csf.ts
> +};
Keep the `from` clause of the first export block as is and simply move your export to its own block.

```suggestion
} from '@storybook/csf';

export type { InputTypeOverride as InputType };
```

2023-09-29 23:33 UTC, noahgregory-basis commented on code/lib/types/src/modules/csf.ts
> +} from '@storybook/csf';
None of this should be imported. The export should be done differently (see next comments).
```suggestion
import type { ViewMode as ViewModeBase } from '@storybook/csf';
```

2023-10-02 19:51 UTC, kylegach commented
Hey, @SadScream. Thank you for your PR. If you see [my comment on the issue this closes](https://github.com/storybookjs/storybook/issues/24174#issuecomment-1743658209), you'll hopefully understand that we cannot merge this work as it doesn't fit the reality of the situation.

2023-10-02 19:51 UTC, closed without merging