Improve the accessibility of the object control buttons
storybookjs/storybook pull request #24580
Opened 2023-10-25 23:14 UTC by fscgustavo

Closes #24150

## What I did

<ol>
<li>Transformed the span trigger elements into button elements.</li>

<ol>
<li>Button elements already have many implicit accessible behaviors that a span/div does not.</li>
<li>The tag change implied in some CSS changes, so I did it and made some optimizations along the way</li>
</ol>

<li>Removed the document onkeydown listeners of this context and passed its function to the inputs
<ol>
<li>The function of the listener was triggered even if the input was not focused.</li>

<li>By passing the function directly to the inputs we avoid necessary executions and restore the native behavior of the HTML button element (every button element outside of the iframe was is not triggered by the enter key)</li>
</ol>

<li>Improved the acessibility and semantic of the raw button </li>
</ol>

### Before

https://github-production-user-asset-6210df.s3.amazonaws.com/93735775/267240406-cd41e462-fb4e-4416-86c6-40017124b5a6.webm

### After

https://github.com/storybookjs/storybook/assets/48841071/eb8d18a5-4b22-4f92-a726-edc6ef7ec6b6

## Checklist for Contributors

### Testing

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

1. Run a template and search for a story that contains an object control
2. Add a variety of values and verify if the behavior of the accordion and the other buttons stays the same
3. Verify if you can trigger the buttons outside the iframe with the enter key
4. Verify if the enter and that esc key still work inside the object control inputs

This is the object and the path that I used to test:

file path: sandbox/react-vite-default-ts/src/stories/Header.stories.ts
object:
```js
export const LoggedIn: Story = {
  args: {
    user: {
      name: 'Jane Doe',
      exampleObj: {
        key: 'value',
        methodOfObj: function() {
          return true;
        },
      },
      list: ['valueOfList', {foo: 'bar'}],
      method: function() {
        return true
      }
    },
  },
};
```

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

2023-10-26 12:13 UTC, JReinhold requested changes
This looks great, thanks!

1. There are some UI regressions, the left margin for the object/arrays seems to have increased. You can see the differences here in Chromatic, could you take a look at that? https://www.chromatic.com/test?appId=635781f3500dd2c49e189caf&id=653a54b591e4e555d209e0f4

2. It appears the tabindex order is reversed for "Save"/"Cancel" when adding a new property, could you look at that? See this recording for what I mean: 
![Kapture 2023-10-26 at 14 11 19](https://github.com/storybookjs/storybook/assets/5678122/43eced2b-b474-4ab6-825d-40ab567b1379)


I'd love you to QA this as well @cdedreuille

2023-10-29 23:23 UTC, fscgustavo commented
> There are some UI regressions, the left margin for the object/arrays seems to have increased. You can see the differences here in Chromatic, could you take a look at that? 

The margin-right of the button was adjusted ✔️ 

Do you think the Safari layout variation is still bad for the control?

2023-11-08 01:42 UTC, fscgustavo reviewed
I forgot to submit the comment 😅

2024-05-15 12:00 UTC, JReinhold commented on code/ui/blocks/src/controls/react-editable-json-tree/JsonNodes.tsx
> +            {inputElementLayout} {editButtonElementLayout}
> Are there any intentions to make these buttons appear again, or can we remove this piece of code?

I think we can remove it just fine.

2024-05-15 12:02 UTC, JReinhold approved these changes
Sorry for the delay and thanks for your patience. I think this looks great.

If you could resolve the merge conflicts then I think this is good to go.

2024-05-15 19:58 UTC, JReinhold commented
There's a visual regression introduced for the arrays, you can see the visual diff here: https://www.chromatic.com/test?appId=635781f3500dd2c49e189caf&id=66450f76b7ff051578a13b9b

And in this story: https://635781f3500dd2c49e189caf-lcdshmxzdy.chromatic.com/?path=/story/blocks-controls-object--array

It looks like an `li` bullet is visible now, which it probably shouldn't be.

2024-05-15 20:44 UTC, fscgustavo commented
> There's a visual regression introduced for the arrays, you can see the visual diff here: https://www.chromatic.com/test?appId=635781f3500dd2c49e189caf&id=66450f76b7ff051578a13b9b
> 
> And in this story: https://635781f3500dd2c49e189caf-lcdshmxzdy.chromatic.com/?path=/story/blocks-controls-object--array
> 
> It looks like an `li` bullet is visible now, which it probably shouldn't be.

@JReinhold The bug has been resolved! It was likely lost during the conflict resolution.

I have also deleted the edit button that was already hidden with CSS.

Thanks for getting back to me! I am available if any new important changes are required :)

2025-05-27 12:39 UTC, Sidnioulz commented
@JReinhold I'd suggest merging this PR's content as it is. I've rebased and opened https://github.com/storybookjs/storybook/pull/31581 so we get a clean CI status and can work on merging this.

I'll also update the issue with additional steps to close it, as I don't believe this PR itself is enough to make the component accessible. I just don't feel comfortable giving @fscgustavo more work a year after he has submitted this, and I think it would be better to continue work on a follow-up PR.

2025-05-27 12:39 UTC, closed without merging