add support for storyshots to save files according to different patterns
storybookjs/storybook pull request #2517
Opened 2017-12-19 14:16 UTC by zvictor

# The issue

In my setup, I always have a `cases.spec.js` that contains different props for my components. This file provides cases scenarios for both unit tests and storybook. With that in place, my components always have a standard `stories.js` file next to it, that looks like that:

```js
import React from 'react';
import { storiesOf } from '@storybook/react';

import Component from './component';
import cases from './cases.spec.js';

const stories = storiesOf('Category Icon Hover Menu', module)

for (const [caseName, caseData] of cases) {
  stories.addCentered(caseName, () => (
    <Component {...caseData} />
  ));
}
```

I like organising the project like this because I get storybook "for free" while writing tests. However, the `multiSnapshotWithOptions` does not work the way I intended with such setup. I don't like that it always create a `__snapshots__` folder with a **single file** on it.

![screen shot 2017-11-30 at 13 25 24](https://user-images.githubusercontent.com/181076/33431047-2d2c6194-d5d3-11e7-9695-a2068e3b494a.png)

# The alternative

I rewrote `getStoryshotFileName` to use the stories `kind` and `name` instead of the original filename:

![screen shot 2017-11-30 at 13 31 20](https://user-images.githubusercontent.com/181076/33431649-79a5ab14-d5d5-11e7-86f1-6796af2a71a9.png)

The API is quite simple:

```js
import initStoryshots, { snapshotPerStoryAdded, snapshotPerStoryFile  } from '@storybook/addon-storyshots';

initStoryshots({
  // filesPattern: snapshotPerStoryAdded,
  filesPattern: snapshotPerStoryFile,
});
```

with that I also killed the `multiSnapshotWithOptions`. I hope nobody minds 😄

2017-12-19 14:16 UTC, zvictor commented on addons/storyshots/src/utils.js
> +    const name = sanitize(`${kind}--${story}`)
is `--` the separator we want to use?

2017-12-19 23:35 UTC, ndelangen approved these changes

2017-12-20 04:58 UTC, igor-dv commented
I will test it soon too. Let's not merge for now. We want to fix things with angular in 3.3 before + we have [this](https://github.com/storybooks/storybook/pull/2413) that might conflict.

2017-12-20 10:30 UTC, zvictor commented
> I will test it soon too. Let's not merge for now.

Cool. Just to make it clear, I am starting my vacations now and I will be out for a whole month. If you need me to make changes in the code it will need to wait. Sorry for that.

2017-12-20 11:45 UTC, igor-dv commented
If it's not impeding your work - it's ok. I think there won't be a much work here during the holidays.

2017-12-21 10:32 UTC, ndelangen commented
Hey @zvictor can you please fix the merge conflict?

2018-01-03 17:09 UTC, igor-dv requested changes
You can't really remove the 'multiSnapshotWithOptions' it's already in 3.3 release, so renaming/removing it is a breaking change.

2018-01-04 13:34 UTC, igor-dv commented
@zvictor , when you are back, let's revisit the implementation. I find it very useful to customize file names and extensions.

2018-02-21 14:18 UTC, zvictor commented
@igor-dv sorry for my absence. I have been more busy than I expected since I came back from vacation and to be honest I cannot estimate when I would have some time available. Nonetheless, some of the changes that were made in the project since the creation of this PR are beyond my comprehension, so it would be a bit hard for me to do a proper merge.

with all of that said, I would be more than happy if you could take over this PR and work on the needed changes.

2018-02-21 19:27 UTC, igor-dv commented
Sure

2018-06-06 14:46 UTC, bialesdaniel commented
Any updates on this? My use case is that I have multiple `index.stories.js` files and if one of the stories change it gives me multiple failed tests. Being able to name the file based on the parent directory or something would be helpful.

2018-06-10 14:00 UTC, igor-dv commented
@bialesdaniel, I am working on it.
I am closing this PR since there are too many changes in the repo to make it work.

2018-06-10 14:00 UTC, closed without merging