add uniqueness to cacheDir
storybookjs/storybook pull request #25264
Opened 2023-12-19 11:07 UTC by ndelangen

Closes #24082

## What I did

I ensured that storybook when using a cache directory as an output directory, will use a unique sub-dir per storybook configDir.

I also cleaned up a bit of terminal output, there were absolute paths in there, which feels noisy.
It also printed out a message about copying over things from node_modules, which I doubt is useful information to the user, as it was storybook's internal pre-bundled stuff that was getting copied)

## Checklist for Contributors

### Testing

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [x] integration tests
- [x] end-to-end tests

#### Manual testing

- Making a static build of any storybook, and check if it work.
- Provide a manual outputDir via a CLI flag and see if it works

- Start a dev sandbox
- check the `node_modules/.cache` directory. It's contents should include:
  ![Screenshot 2023-12-19 at 12 06 09](https://github.com/storybookjs/storybook/assets/3070389/975a0543-23fd-49e1-a8d2-26eca28c11f0)

The long hash is unique per storybook configDir. It does not leak anything personally identifiable.
Here's the code creating it:
https://github.com/storybookjs/storybook/blob/3b94da1a9f4e5942dae067f277c2a4672271cf2e/code/lib/core-server/src/build-dev.ts#L60

- check if the dev version works as expected.

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

2023-12-21 11:44 UTC, shilman requested changes
Looks good!!! Minor changes

2023-12-21 11:44 UTC, shilman commented on code/lib/core-server/src/utils/copy-all-static-files.ts
> +          if (!staticDir.includes('node_modules')) {
This line could use a comment explaining why

2023-12-21 11:44 UTC, shilman commented on code/lib/core-server/src/utils/copy-all-static-files.ts
> +    // logger.info(chalk`=> Copying static files: {cyan ${from}} at {cyan ${targetPath}}`);
```suggestion
```

2023-12-21 12:05 UTC, shilman approved these changes

2023-12-21 13:12 UTC, merged

2023-12-26 03:22 UTC, domneo commented
Will this be patched in V7 as well?

2023-12-26 03:40 UTC, shilman commented
@domneo Nope. Please upgrade to the latest prerelease to use it. We're expecting a stable release in early 2024:

```
npx storybook@next upgrade --prerelease
```

2024-08-30 14:36 UTC, bobleap commented
> Will this be patched in V7 as well?
+1