UI: Update default shortcuts
storybookjs/storybook pull request #25625
Opened 2024-01-17 10:35 UTC by cdedreuille

Closes #16022

## What I did

In this PR I'm modifying the default shortcuts to avoid having shortcuts being triggered unintentionally. I added `command/ctrl` before the first 6 shortcuts transforming from `S` to `command + S`.

I also replaced `/` for search into `command + K` as we are exploring updating our search into a command palette and `command + k` is a well known shortcut for that.

## Checklist for Contributors

### Testing

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

2024-01-17 10:48 UTC, ndelangen approved these changes

2024-01-17 11:11 UTC, cdedreuille commented on code/lib/manager-api/src/modules/shortcuts.ts
> +  search: [controlOrMetaKey(), 'K'],
Thanks @ndelangen I updated them now.

2024-01-17 13:40 UTC, JReinhold requested changes
Code looks good, but it needs a migration note.

2024-01-17 14:50 UTC, cdedreuille commented
@JReinhold I updated the shortcuts to use `Alt` instead of `command for most of them except for search that will stay as `command + K` to match what others are doing with their command action. I also added migration guides as you suggested.

2024-01-18 10:36 UTC, cdedreuille commented
It seems we have flaky E2E tests. Since all other tests passed, we discussed this with @JReinhold and he gave me approval to merge this PR directly since the E2E bug is very unlikely related to this issue.

2024-01-18 10:36 UTC, merged

2024-07-18 07:57 UTC, adrian-cocoara-lgp commented
Hello @cdedreuille,
These changes broke some of our Test Cases since the shortcuts keys have changed.
I checked the documentation if there is any way these shortcuts are configurable, but I can't find anything. 
Is there any way I can revert them to the values of Storybook 7? Thanks!