Attempt to make propTablesExclude usage clearer
storybookjs/storybook pull request #2568
Opened 2017-12-26 22:34 UTC by mattferderer

See issue #2266, specifically https://github.com/storybooks/storybook/issues/2266#issuecomment-351472412 for discussion.

Issue: #2266 

## What I did
Added text to documentation make propTablesExclude clearer

## How to test
No changes to code made.

Is this testable with jest or storyshots?
No

Does this need a new example in the kitchen sink apps?
No but would maybe be a good idea.

Does this need an update to the documentation?
This is an update.

If your answer is yes to any of these, please make sure to include it in your PR.

2017-12-26 23:36 UTC, Hypnosphi requested changes

2017-12-26 23:36 UTC, Hypnosphi commented on addons/info/README.md
> +  propTablesExclude: [], // Exclude Components from being shown in Prop Tables section. Pass the imported component names as values to the array.
Component name is a string, but here the component itself (class or stateless function) should be passed

2017-12-27 03:13 UTC, mattferderer commented
Would it make more sense to say "Pass the imported component class or function to the array."

2017-12-27 11:51 UTC, Hypnosphi commented
"Accepts an array of component classes or functions"

2017-12-27 15:44 UTC, Hypnosphi approved these changes

2017-12-27 16:01 UTC, merged