Docs: StoriesOf API removal
storybookjs/storybook pull request #25863
Opened 2024-02-01 17:32 UTC by jonniebigodes

Follows up on #24655

## What I did

With this pull request, I've updated the wording about the removal of the `storiesOf` API, that's been deprecated for a while and has now been removed.

@ndelangen and @JReinhold, when you have a moment, can both of you take a look and let me know of any feedback you may have so that we can get this merged in and the documentation updated to reflect these changes? Additionally, I would like some input on the `storiesOf.md` file located in the `code/lib/preview-api/docs` directory, specifically if we should keep it or not. I've updated the wording to factor in the removal, but wanted to hear from both of you first so that we can follow through.

## Checklist for Contributors

### Testing

1. Follow the steps in the [contributing instructions](https://storybook.js.org/docs/react/contribute/new-snippets#preview-your-work) for this branch, `docs_stories_of_updates`.
2. Open the relevant documentation and verify the feature changes.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

2024-02-02 12:28 UTC, JReinhold requested changes

2024-02-02 12:28 UTC, JReinhold commented on code/lib/preview-api/docs/storiesOf.md
I think we should remove this file completely.

2024-02-02 12:28 UTC, JReinhold commented on docs/api/csf.md
> +If you are writing stories in the older `storiesOf()` syntax, it was removed in Storybook 8.0 and is no longer maintained. We recommend migrating your stories to CSF. See the [migration guide](../mig
```suggestion
If you have stories written in the older `storiesOf()` syntax, it was removed in Storybook 8.0 and is no longer maintained. We recommend migrating your stories to CSF. See the [migration guide](../migration-guide.md#storiesof-to-csf) for more information.
```

2024-02-02 12:41 UTC, jonniebigodes commented on code/lib/preview-api/docs/storiesOf.md
@JReinhold I can work with that, we'll need to make some tweaks  [here](https://storybook.js.org/docs/api/main-config-indexers#examples) so that we don't forget about it.

2024-02-05 15:08 UTC, ndelangen approved these changes

2024-02-05 15:46 UTC, merged