Docs: add message that storybook creates node_modules in pnp
storybookjs/storybook pull request #25988
Opened 2024-02-11 10:49 UTC by turtle601

Closes #25987

## What I did

i add 'yarn storybook' creates node_modules/.cache in Yarn 2 PnP project in get-started/install.md files

## Checklist for Contributors

### Testing

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

2024-02-16 02:30 UTC, turtle601 commented
@jonniebigodes I'm really looking forward to your feedback on that pr

2024-02-20 20:00 UTC, jonniebigodes requested changes
@turtle601 appreciate you taking the time to put together this pull request and helping us improve our documentation by adding this small but rather important piece of information that is affecting you and can affect other users as well. I left a small item for you to look into when you have a moment.

Let me know of any questions you may have so that I can unblock you and get this merged.

Looking forward to hearing from you.

Have a fantastic day.

Stay safe

2024-02-21 08:22 UTC, turtle601 commented on docs/get-started/install.md
> +</Callout>
@jonniebigodes Thank you so much for your feedback. :)

I saw your feedback and reflected it exactly.

I would appreciate it if you could check my PR one more time.

2024-02-22 17:10 UTC, jonniebigodes approved these changes

2024-02-22 17:13 UTC, jonniebigodes commented
@turtle601, no need to thank you whatsoever, glad to help you! I appreciate you addressing the feedback so quickly. I've checked, and all is good on my end. I'm going to merge this once the checklist clears. 

Hope you have a fantastic day.

2024-02-22 17:33 UTC, merged