Docs: Don't show empty arg tables in doc pages
storybookjs/storybook pull request #26200
Opened 2024-02-26 15:26 UTC by kasperpeulen

Closes #

## What I did

Don't show empty arg tables in doc pages

## Checklist for Contributors

### Testing

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

2024-02-26 16:30 UTC, kasperpeulen commented on code/ui/blocks/src/blocks/Controls.tsx
> +    if (Object.keys(filteredArgTypes).length > 0 || Object.keys(args).length > 0) {
I think we need both, as even without argTypes we will show controls based on arg values.

2024-02-26 16:34 UTC, JReinhold requested changes
We should have a story for this. It's a bit tricky with stories for these doc blocks component, let me know if you need help/pairing.

2024-02-26 16:34 UTC, JReinhold commented on code/ui/blocks/src/blocks/Controls.tsx
> +    return null;
```suggestion
    if (Object.keys(filteredArgTypes).length === 0 && Object.keys(args).length === 0) {
      return null;
    }
    return (
      <PureArgsTable
        rows={filteredArgTypes}
        sort={sort}
        args={args}
        globals={globals}
        updateArgs={updateArgs}
        resetArgs={resetArgs}
      />
    );
```

2024-02-27 14:12 UTC, JReinhold approved these changes
💅

2024-02-27 14:12 UTC, merged