UI: Improve empty state of addon panel
storybookjs/storybook pull request #26481
Opened 2024-03-13 16:20 UTC by yannbf

Closes #26445

## What I did

This PR revamps the empty state of the addon panel (when users have zero addons) by doing a couple of things:

1 - Adds the toolbar items so that users can toggle position and close the panel
2 - Adds some copy with a link to the integrations catalog, so that users can explore Storybook addons

<img width="1203" alt="image" src="https://github.com/storybookjs/storybook/assets/1671563/a7db5b2e-77c2-4941-ada4-975ff92c28cb">

<img width="1207" alt="image" src="https://github.com/storybookjs/storybook/assets/1671563/a88ed2ec-0e2e-4e11-b2b6-52d26944f68a">

## Checklist for Contributors

### Testing

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

2024-03-14 08:37 UTC, mkosir commented
Hi @yannbf, having a quick look into the PR, just wondering will it be possible to not show/hide add on panel completely?

2024-03-15 11:19 UTC, cdedreuille commented
@mkosir The addon panel is part of the manager UI. After a couple of discussion we think it is best to make sure we always show the addon panel with options to hide it if you want as expected. If you have no addon, we will show a message that redirect you to the addons catalog.

The idea to remove the addon panel if you have no addon didn't felt right to us. Addons are a big part of what makes Storybook great.

2024-03-16 15:03 UTC, mkosir commented
> we always show the addon panel with options to hide it if you want as expected.

@cdedreuille thanks, if I understand correctly it will be possible to hide it, with some config option e.g. `showPanel: false`.

2024-03-18 10:27 UTC, cdedreuille commented
@mkosir I was referring to the option to hide or show the panel but not removing it completely. I'm not sure I see the value to have an option to remove it completely. What is your use case? Is it to present your design system to your team? Can docs be a good alternative to what you are trying to achieve?

2024-03-18 10:29 UTC, cdedreuille requested changes
@yannbf If you could just change the life boat ring icon to the docs one that would be great. Other than that, the code looks great. Thank you 🙏

2024-03-18 10:38 UTC, mkosir commented
> @mkosir I was referring to the option to hide or show the panel but not removing it completely. I'm not sure I see the value to have an option to remove it completely. What is your use case?

@cdedreuille I see, I have some use cases, mostly libraries, that just want to quickly visualize different capabilities without adjusting addons params ([for example](https://mkosir.github.io/react-parallax-tilt/?path=/story/react-parallax-tilt--event-params)).

>  Is it to present your design system to your team? Can docs be a good alternative to what you are trying to achieve?

Yes I think for some of the projects I will just navigate away from Storybook since it's not the right fit and go with something simpler 👍 
But keep doing great job and offering a lot of features out of the box (testing, addons etc.) that many projects will find it useful.

2024-03-18 10:42 UTC, cdedreuille commented
@mkosir Thanks a lot for sharing your use case. That's really interesting. Have your tried using Storybook Docs? It seems that this could be the right fit for you since this was built for this use case, to actually present your component + code without tooling.

If this doesn't work, we are working on a new concept called Portable Stories that will allow you to embed your stories in your own website so you can have full control over the presentation.

2024-03-18 10:45 UTC, mkosir commented
> @mkosir Thanks a lot for sharing your use case. That's really interesting. Have your tried using Storybook Docs? It seems that this could be the right fit for you since this was built for this use case, to actually present your component + code without tooling.
> 
> If this doesn't work, we are working on a new concept called Portable Stories that will allow you to embed your stories in your own website so you can have full control over the presentation.

Thanks will try it out, can't wait what you guys will come up with! 🚀

2024-03-18 10:48 UTC, cdedreuille commented
@mkosir Also, looking at your Storybook, I think your components could benefit from the controls addon to show what props are available and play with them with easy to use controls.

2024-03-18 10:59 UTC, JReinhold approved these changes
A few minor nits, but other than that it looks good!

2024-03-18 10:59 UTC, JReinhold commented on code/ui/components/src/components/tabs/EmptyTabContent.stories.tsx
> +export const CustomFooter: Story = {
```suggestion
export const TitleDescriptionAndFooter: Story = {
```

2024-03-18 10:59 UTC, JReinhold commented on code/ui/components/src/components/tabs/EmptyTabContent.stories.tsx
> +};
Could we add a story here with a title and footer but no description?

2024-03-18 10:59 UTC, JReinhold commented on code/ui/components/src/components/tabs/tabs.tsx
> +  customEmptyState?: ReactNode;
nit: not a fan of `custom` in props, I feel like it's implicit that a prop customizes something, so it can just be `emptyState`.

2024-03-18 10:59 UTC, JReinhold commented on code/ui/manager/src/components/panel/Panel.tsx
> +            </Fragment>
the fragment seems unnecessary here?

```suggestion
            <P>Storybook add-ons</P>
```

2024-03-18 10:59 UTC, JReinhold commented on code/ui/manager/src/components/panel/Panel.tsx
> +            <EmptyStateDescription key="content">
Does `key` have an effect here?

```suggestion
            <EmptyStateDescription>
```

2024-03-19 09:23 UTC, merged