Align documentation with CSF v3
storybookjs/storybook pull request #26621
Opened 2024-03-22 15:22 UTC by nkabrown

* CSF v3 component examples are story objects not story functions
* add missing punctuation mark

## What I did

This PR updates some areas in the documentation that still described stories as functions (CSF v2) instead of objects (CSF v3). This PR will require a 'documentation' label.

2024-03-24 15:16 UTC, jonniebigodes requested changes
@nkabrown, thanks for putting together this pull request and helping us improve the documentation by catching these regressions that were introduced into our documentation. We appreciate it 🙏 !

Left a small item for you to look into when you have a moment.

Let me know once you've addressed it and I'll be more than glad to get this in and published into the documentation.

Have a fantastic day.

Stay safe

2024-03-24 15:16 UTC, jonniebigodes commented on docs/writing-stories/index.md
> +A story captures the rendered state of a UI component. It’s an object with annotations and a render function that returns a component’s state given a set of arguments.
@nkabrown we have room for improvement here and we can go with something along these lines:
```suggestion
A story captures the rendered state of a UI component. It's an object with annotations that describe the component's behavior and appearance given a set
of arguments.
```

2024-03-25 13:35 UTC, nkabrown commented
@jonniebigodes thanks for the suggestion. This is resolved.

2024-03-25 16:12 UTC, jonniebigodes approved these changes

2024-03-25 16:14 UTC, jonniebigodes commented
@nkabrown no need to thank whatsoever, glad to help. Thanks for addressing the feedback so promptly. All is good on my end and going to merge this once the checklist clears. 

Have a great day.

Stay safe

2024-03-25 16:27 UTC, merged