Extract tslint exclusions out of package.json scripts
storybookjs/storybook pull request #2684
Opened 2018-01-08 14:45 UTC by igor-dv

Issue: https://github.com/storybooks/storybook/pull/2682#discussion_r160148758

## What I did
Extract tslint exclusions to the section inside `tslint.json`.

2018-01-08 14:48 UTC, Hypnosphi approved these changes

2018-01-08 14:50 UTC, Hypnosphi requested changes

2018-01-08 14:50 UTC, Hypnosphi commented on package.json
> +    "lint:ts": "tslint -p . -c tslint.json -t stylish **/*.ts",
This will lint all the files on each commit. Please remove the `**/*.ts` part and add it in `lint` script instead (as it's done for eslint)

2018-01-08 16:18 UTC, Hypnosphi approved these changes

2018-01-08 16:18 UTC, merged

2018-01-10 06:23 UTC, shilman commented
adding to patch to reduce merge conflicts