Added "Copy button" for code example (addon-info)
storybookjs/storybook pull request #2713
Opened 2018-01-10 20:18 UTC by SuperOl3g

Issue:
nope

## What I did
Added "Copy button" for code example and add some customization options

2018-01-10 20:54 UTC, Hypnosphi commented on addons/info/src/components/markdown/pre/copyButton.js
> +    outline: 'none',
Please either keep the default outline, or provide some replacement for it (i. e. some styles for `:focus` state)

2018-01-10 20:57 UTC, Hypnosphi commented on addons/info/src/components/markdown/pre/copyButton.js
> +  } = props.theme;
It's quite hard for me to wrap the head around nested destructuring assignments. Can you please make them no more than 1 level deep?

2018-01-10 21:01 UTC, Hypnosphi commented
[Live example](https://deploy-preview-2713--storybooks-official.netlify.com/?selectedKind=Addons%7CInfo.React%20Docgen&selectedStory=Comments%20from%20PropType%20declarations&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

2018-01-10 21:12 UTC, Hypnosphi requested changes
See comments

2018-01-14 15:18 UTC, Hypnosphi approved these changes

2018-01-14 15:32 UTC, Hypnosphi commented
Looks like you need to add `glamorous` to `addons/info/package.json`'s `dependencies`

2018-01-14 17:00 UTC, merged

2018-01-14 18:54 UTC, ndelangen commented
🎉

2018-01-14 19:27 UTC, SuperOl3g commented
🎊🎊🎊
Can somebody tell when it will be published?)

2018-01-14 20:51 UTC, Hypnosphi commented
Probably in a week, @shilman does releases every weekend