Bugfix : `summary: undefined` type issue
storybookjs/storybook pull request #27202
Opened 2024-05-20 05:50 UTC by angad-sethi

Closes #27129

## What I did

I've updated the type for `ArgType.table.type.summary` to be `string | undefined` so as to enable `exactOptionalPropertyTypes: true` in `tsconfig.json`
## Checklist for Contributors

### Testing

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

2024-05-21 12:01 UTC, Hyzual commented
I've cloned your repository, how can I test this from a project using storybook ? I guess I need to replace the version used by the local repo I cloned, but I've never done that. Could you share some pointers ? :)

2024-05-22 09:02 UTC, valentinpalkovic commented
@Hyzual I have created a canary release. You can try it out by upgrading Storybook to it:

```
npx storybook@0.0.0-pr-27202-sha-9b58ef19 upgrade
```

2024-05-23 10:45 UTC, Hyzual requested changes
The TypeScript error is still present. We have found that we had to modify an interface named `InputType` from the `@storybook/types` package to add `string | undefined` for the TypeScript error to be fixed. I tried looking for it in the code but did not find it 😓. If you know where it is and could change it, I would be grateful!

2024-05-25 13:49 UTC, shilman commented
@angad-sethi Perhaps here https://github.com/ComponentDriven/csf/blob/81a58c947078157f58cc1f45f1fd0c04c2bd1771/src/story.ts#L159

2025-07-21 13:56 UTC, yannbf commented
Hey @kasperpeulen can you please check this PR? Thanks!

2025-12-02 12:41 UTC, Sidnioulz commented
Hi @angad-sethi,

Thanks for your contribution. We unfortunately did not merge it for some time, and we've since merged another PR fixing the same issue. So I'm gonna go ahead and close this PR; thanks nonetheless for bringing this to our attention and taking some time to fix it.

2025-12-02 12:41 UTC, closed without merging