Feat: Compact folders (smart flatten)
storybookjs/storybook pull request #27369
Opened 2024-05-25 18:50 UTC by Diogorrib

Closes #25014

## What we did

### Feature implementation

In storybook, there is currently a route tree which can go quite deep. With this, it is necessary to click trough all of the folders to access all the files of the project. With compact folders (smart flatten) this problem can be solved.

Compact folders allow folders with just one entry of the same type (relevant for storybook, since there are many types of folders and files) to be collapsed into the same level with single headings, which improves readability and keeps the tree cleaner.

For example: a group folder with just one group folder as entry becomes
a single heading which name is composed by these 2 folders.

Here is a visual example of the feature:

![Alt text](https://i.ibb.co/dmRvGgt/image.png)

### Feature coverage with new unit tests

Since the new feature changes manager API (introduced nested folders types) we find it relevant to add some unit tests to cover this implementation.

## Checklist for Contributors

### Testing

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [x] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

Example:
1. Run storybook in localhost using the command below:
```
$ yarn start
```
2. Verify in the sidebar that folders are now nested

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

2025-05-12 13:54 UTC, Sidnioulz commented
Note: there could be accessibility implications based on how https://github.com/storybookjs/storybook/issues/31267 evolves. If we end up having a tree grid navigation pattern, how should it be announced to blind users that we're jumping down two levels here?

2025-06-12 13:43 UTC, ndelangen requested changes
I think if we want such a feature it should be implemented in the indexer, instead of the UI, WDYT @JReinhold ?

2025-06-12 15:06 UTC, JReinhold commented
Hmm no I'd think it's best to build it in the UI. Let the raw data stay intact, modify the UI. that makes it easier to tweak the UI later, or allow for users to opt-in to stuff like this.

2025-06-12 15:50 UTC, Sidnioulz commented
> Hmm no I'd think it's best to build it in the UI. Let the raw data stay intact, modify the UI. that makes it easier to tweak the UI later, or allow for users to opt-in to stuff like this.

I'm tempted to agree with this but it does complicate the handling of HashItems quite a bit. It would mean we have entries that don't appear in the sidebar. Do these entries only have an ID? Or do they have a title? Does the parent entry that collapses its only child have the child's title in its title?

It does add a layer of complexity and unpredictability to an API that I already find hard to make sense of as an external consumer.

I think it would be great to consolidate __id, title and other similar information in that HashItem API to ensure there is a clear way for addon (`renderLabel` specifically) / indexer authors to identify entries and understand how they appear in the UI.

If that is too low ROI, then I would prefer default indexers to consolidate the data just so it doesn't add a layer of complexity to the API, even though I agree with Jeppe that doing the collapsing in the UI is better conceptually.

2025-06-23 08:57 UTC, valentinpalkovic commented
@MichaelArestad, do we want to have a feature like this? Please feel free to comment or close the PR if we don't want to support it.

2025-06-24 21:22 UTC, MichaelArestad commented
> do we want to have a feature like this? Please feel free to comment or close the PR if we don't want to support it.

@valentinpalkovic I can't say without knowing a little more.

1. Is this a common scenario?
2. What implications might this have in the UI outside of the above screenshot? Is Search impacted?
3. Is there complexity in maintenance added?

If we did do this, I have some minor design suggestions (very straightforward). I just don't know enough to make a call either way.

2025-06-24 22:16 UTC, Sidnioulz commented
I do feel that this is a minor UI improvement with significant
complications both for the indexed story structure and accessibility
compliance.

If nobody feels strongly about it, maybe we could provide guidelines for
external contributions and then wait for someone to step up?

2025-07-01 07:18 UTC, valentinpalkovic commented
@Sidnioulz I tend to agree! Since this PR got stale and needs a major revamp, and the team is not sure whether we want to support a feature like this, I am about to close this PR. Please feel free to open [a RFC](https://github.com/storybookjs/storybook/discussions) so that we can first discuss how this feature should look and whether we want to implement it. Thank you for your understanding!

2025-07-01 07:18 UTC, closed without merging