Updating css-style testing docs to mention StoryShots image snapshots feature
storybookjs/storybook pull request #2767
Opened 2018-01-17 16:17 UTC by anescobar1991

Issue: With https://github.com/storybooks/storybook/pull/2413 being merged into master and adding image snapshot capabilities into StoryShots the [documentation](https://storybook.js.org/testing/css-style-testing/#supported-cssstyle-testing-frameworks) should reflect the change.

## What I did

Updated css-style-testing doc to mention StoryShots integration with `jest-image-snapshot`

## How to test

View doc in markdown editor.

2018-01-17 16:42 UTC, Hypnosphi requested changes

2018-01-17 16:42 UTC, Hypnosphi commented on docs/src/pages/testing/css-style-testing/index.md
> -- [Loki](https://loki.js.org/): Is a great tool for visual regression testing.
I think all those tools are still worth mentioning

2018-01-17 17:45 UTC, Hypnosphi approved these changes

2018-01-17 17:45 UTC, Hypnosphi commented
@tmeasday would you like Chromatic to be mentioned here as well?

2018-01-17 18:56 UTC, ndelangen approved these changes

2018-01-18 00:03 UTC, tmeasday commented
@Hypnosphi sure! We should mention the other commercial offerings that support storybook too: [Percy](https://percy.io/docs/clients/javascript/react-storybook) and [Screener](https://screener.io/v2/docs).

2018-01-18 02:10 UTC, anescobar1991 commented
@Hypnosphi should I do that here? Or should those be added in a separate PR?

2018-01-18 10:19 UTC, Hypnosphi commented
@anescobar1991 as you wish =)

2018-01-18 15:03 UTC, anescobar1991 commented
@Hypnosphi I added them in 728cad8e1975eaf82d03f55c0df0416fe00bd9a7 :)

2018-01-18 15:12 UTC, Hypnosphi commented on docs/src/pages/testing/css-style-testing/index.md
> +- [Screener](https://screener.io/v2/docs)
And also [Chromatic](https://www.chromaticqa.com/)

2018-01-18 22:16 UTC, merged