Self documented Storybook (A.K.A Addon Stories)
storybookjs/storybook pull request #2885
Opened 2018-01-31 13:47 UTC by igor-dv

So, I've been a bit annoyed about too many questions regarding documentation, like:
- "You need to improve docs",
- "How to do this or that"

One of the problems is that though we do have a lot of examples, they are not easily discoverable. So I thought what if we just show the code of the story as an addon. Then we can publish all the examples and link to them from docs. 🤔 Or even put them in the docs with Iframe.

## What I did
So, I've added an experimental addon-stories, which probably won't have any sense for external usages.:

1. ~~It works with a custom loader that should be configured with a custom webpack.config ( maybe there is a better way 🤷‍♂️ ). This loader injects decorator with the source of the file. For the POC purposes, I've used some naive "string.indexOf" implementation, and probably should be replaced with some AST processing.~~
2. ~~Currently, the addon panel just shows the source as a plain text.~~

TBD:
- [x] Use syntax highlighting
- [x] Use AST parsing to find stories and inject decorator
- [x] Add option to highlight specific "add()" because we have multiple "adds" in one story file
- [x] Extract kind and use kind#story as a key in highlight locations map (only when kind is "Literal")
- [x] Rename package to something that makes sense

2018-01-31 14:07 UTC, shilman commented
Awesome!!! Suggestion: addon-source? Addon-sourcecode?

2018-01-31 14:21 UTC, Hypnosphi commented
`addon-storysource`?

2018-02-01 07:45 UTC, igor-dv commented
"addon-storysource" makes me happy =)

2018-02-01 08:14 UTC, igor-dv commented
It looks much better with the syntax highlighting =)

![image](https://user-images.githubusercontent.com/7867954/35668055-995d9bee-0738-11e8-8ba0-fed50d21b27d.png)

2018-02-01 13:23 UTC, Hypnosphi commented
I have a crazy idea: what if we add CodeMirror?

2018-02-01 13:27 UTC, igor-dv commented
Oh it's indeed crazy. So CodeMirror will allow code editing, but what's next 🙀

2018-02-02 08:06 UTC, ndelangen commented
Needs syntax highlighting tbh

2018-02-02 11:35 UTC, igor-dv commented
![image](https://user-images.githubusercontent.com/7867954/35731353-e7e729d4-081d-11e8-88ae-cfad0e4d49bd.png)

2018-02-13 19:29 UTC, ndelangen commented
What's needed to get this merged?

2018-02-13 20:09 UTC, igor-dv commented
I think of a way we can publish every example to some static place and link it to the docs...

2018-02-17 11:41 UTC, Hypnosphi commented
> a way we can publish every example to some static place

What's wrong with netlify deploys?

2018-02-17 11:58 UTC, igor-dv commented
Can it be automated?

2018-02-17 11:59 UTC, Hypnosphi commented
What do you mean? We currently deploy each commit

2018-02-17 12:10 UTC, igor-dv commented
Is there any way to link netlify builds to docs?

2018-02-17 12:27 UTC, Hypnosphi commented
There are branch deploys with permalinks

For example, this is a link to deploy of this branch that gets updated authomatically with each commit

https://addon-stories--storybooks-official.netlify.com/

On documentation site, we should use links to `release/3.3` branch deploys (because `master` can contain usages of alpha features):
https://release-3-3--storybooks-official.netlify.com/

2018-02-17 12:35 UTC, Hypnosphi requested changes
Please add a `README.md` for the addon

2018-02-17 12:39 UTC, Hypnosphi commented on examples/angular-cli/.storybook/webpack.config.js
> +    loaders: [ ...originalTsRule.loaders, require.resolve('@storybook/addon-storysource/loader') ],
We can add this loader with `enforce: 'pre'` instead of patching the original rule:
https://webpack.js.org/configuration/module/#rule-enforce

2018-02-17 15:38 UTC, Hypnosphi approved these changes

2018-02-18 13:43 UTC, igor-dv commented
I think I will add Netlify to docs in a separate PR.

2018-02-18 14:04 UTC, Hypnosphi commented
Can we add scroll to the highlighted story (maybe in separate PR)?

2018-02-18 14:05 UTC, merged

2018-02-18 14:37 UTC, igor-dv commented
> Can we add scroll to the highlighted story (in separate PR)?

Sure

2018-02-19 06:30 UTC, igor-dv commented
Can we make it as a patch to 3.3 ?

2018-02-19 09:49 UTC, Hypnosphi commented
@shilman technically, it's a feature, but releasing it as patch could improve our documentation right now. WDYT?

2018-02-21 14:36 UTC, shilman commented
I think we should just get 3.4 out sooner rather than back-patching a large new feature