Pull request to close "[Feature Request]: Allow hooks to be passed in component or similar property - React/Typescript #23216"
storybookjs/storybook pull request #28910
Opened 2024-08-16 20:29 UTC by Danielmart02

Closes #

 Closes#23216 : Feature Request]: Allow hooks to be passed in component or similar property - React/Typescript 

## What I did

This PR introduces the useExampleHook.stories.tsx and useExampleHook.ts files to address the issue of passing hooks as component properties within a Storybook project using React and TypeScript. These changes enable developers to integrate hooks as arguments or within components, ensuring proper type-checking and seamless JSDoc documentation.

Created useExampleHook.stories.tsx: Developed a Storybook story to demonstrate the usage of a React hook within a component, ensuring compatibility with TypeScript and integration with JSDoc for enhanced documentation.

Created useExampleHook.ts: Implemented a custom React hook (useExampleHook) with JSDoc commentary to facilitate its usage and documentation in Storybook stories.

This PR does not modify Storybook's core functionality but offers a practical workaround for developers facing similar issues when using hooks with TypeScript in their projects.

## Checklist for Contributors

### Testing

#### The changes in this PR are covered in the following automated tests:
- [x ] stories
- [x ] unit tests
- [x ] integration tests
- [x] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

2024-08-19 13:14 UTC, ndelangen commented
@Danielmart02Can you tell me how does this fix the problem described in the linked issue?

If we need to add an extra story for the testing the react renderer, we'd have to do it here:
`code/renderers/react/template/stories`

2024-08-22 10:39 UTC, marcelo-morales commented on sandbox/react-vite-default-ts/src/stories/useExampleHook.stories.tsx
> +export const Default: Story = {
If there is no message returned from the hook, how would the Story look like? Or should there always be a message? Also would be nice to see some unit tests, even if the functionality seems pretty straightforwrd

2024-08-22 10:41 UTC, marcelo-morales requested changes
I suggest adding some unit tests, in addition look into @ndelangen 's comment

2025-07-02 07:45 UTC, valentinpalkovic commented
@Danielmart02 
Thank you for your contribution so far!
Though I am closing this PR due to inactivity. Please open a new PR if you are still interested in contributing this bug fix or let me know if I should reopen it. Thanks!

2025-07-02 07:45 UTC, closed without merging