Fix documentation link
storybookjs/storybook pull request #28925
Opened 2024-08-20 06:13 UTC by peschee

Closes #25727

## What I did

Fixed the link to the `ADVANCED.md` file in the action addon section.

## Checklist for Contributors

### Testing

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [x] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

2024-08-20 06:14 UTC, peschee commented
I wasn't able to add the `documentation` label myself…

2024-09-09 19:49 UTC, jonniebigodes requested changes
@peschee thank you for taking the time to put together this pull request and helping us improve the documentation by catching this small but rather important issue with this link. We appreciate it 🙏 !

I left a small item for you to look into when you have a moment.

Let me know and we'll go from there.

Have a great day.

Stay safe

2024-09-09 19:49 UTC, jonniebigodes commented on docs/essentials/actions.mdx
> +There are also some older ways to use actions as documented in the [advanced README](../../../code/addons/actions/ADVANCED.md).
@peschee, when you have a moment, can you adjust the link to be as follows:
```suggestion
There are also some older ways to use actions as documented in the [advanced README](https://github.com/storybookjs/storybook/blob/next/code/addons/actions/ADVANCED.md).
```

2024-11-22 11:49 UTC, jonniebigodes commented
@peschee, thank you for putting together this pull request and helping us improve the documentation. We appreciate it 🙏 ! However, the changes you're introducing have already been added to a recent pull request. I hope you don't take it the wrong way, and I look forward to your next contribution.

Have a great day.

Stay safe.

2024-11-22 11:49 UTC, closed without merging

2024-11-22 13:44 UTC, peschee commented
All good @jonniebigodes ;)