Addon Vitest: support read story name for vitest test description
storybookjs/storybook pull request #29147
Opened 2024-09-18 07:21 UTC by InfiniteXyy

## What I did

I added a new feature to the newly published `vitest-test` plugin:

Now the test description will use the explictly settled `name` of the story, and then fallback to the `exportName`.

The requirement comes from that developers might want to have spaces/brackets/etc... in the test description, which is not allowed in exportName.

At the same time, this can also keep consistent with the name display in storybook preview.

## Checklist for Contributors

### Testing

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [x] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [x] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

2024-09-18 07:29 UTC, InfiniteXyy commented on code/core/src/csf-tools/vitest-plugin/transformer.ts
> +      const testName = (function getTestName(): string {
remove the usage of iife

2024-09-18 07:46 UTC, InfiniteXyy commented on code/core/src/csf-tools/vitest-plugin/transformer.ts
> +          }
With find, the type will be hard to define

2024-09-20 13:32 UTC, yannbf requested changes
Hey @InfiniteXyy thanks a lot for your contribution! This was something we were planning to do, so thanks for speeding that up! I'd love if you could change the implemention to make it simpler, given that the underlying parsing tool (CsfTools) already handles extracting the story name.

I believe you can delete most of the code and use something like this:
```ts
const exportName = parsed._stories[exportName].name || exportName;
return getTestStatementForStory({
          exportName,
          node,
});
```

Test cases:

CSF1/2
```ts
export const Story = () => {}
Story.storyName = 'custom name'
```

CSF3
```ts
export const Story = () => {
  name: 'custom name'
}
```

Let me know how it goes and if you need anything else!

2024-09-20 13:35 UTC, yannbf commented on docs/writing-tests/vitest-plugin.mdx
> +We are using the exportName of a story definition by default, but you can provide a `name` property for the story to customize the test description. This is useful when you want have places, brackets
Can you add a code snippet alongside this so users can understand it better?

```ts
export const Story = {
  storyName: 'custom, descriptive name'
};
```

```suggestion
### How do I customize the test description?

By default, the export name of a story is mapped to the test name. You can provide a `name` property for the story to customize the test description, allowing you to write more descriptive names. This is useful when you want use spaces, brackets or other special characters in the test description.
```

2024-09-20 13:36 UTC, yannbf commented
Also, can you share examples of how you are naming your stories for your tests? It's pretty useful for us to have an idea about use cases! Thanks!

2024-09-21 08:50 UTC, InfiniteXyy commented
> Also, can you share examples of how you are naming your stories for your tests? It's pretty useful for us to have an idea about use cases! Thanks!

Hi, thank you for your code review and feed back.
In our project, we are following a naming convention in test descriptions.

Each test cases should have a description like `WHEN user click reply, THEN a request should be sent with a double confirm dialog`.

It's more like a sentense, because we want each test to have a meaningful description that represents a specific scenario.

2024-09-21 09:20 UTC, InfiniteXyy commented
ser

> Hey @InfiniteXyy thanks a lot for your contribution! This was something we were planning to do, so thanks for speeding that up! I'd love if you could change the implemention to make it simpler, given that the underlying parsing tool (CsfTools) already handles extracting the story name.
> 
> I believe you can delete most of the code and use something like this:
> 
> ```ts
> const exportName = parsed._stories[exportName].name || exportName;
> return getTestStatementForStory({
>           exportName,
>           node,
> });
> ```
> 
> Test cases:
> 
> CSF1/2
> 
> ```ts
> export const Story = () => {}
> Story.storyName = 'custom name'
> ```
> 
> CSF3
> 
> ```ts
> export const Story = () => {
>   name: 'custom name'
> }
> ```
> 
> Let me know how it goes and if you need anything else!

Thank you for your suggestions! It's helpful and by using `parsedStory`, the code looks just much better now.

I also try adding the test cases for csf v1/2 and function config, but I am not familiar with csf v1/2, hope I didn't do it wrong.

2024-09-23 10:43 UTC, yannbf commented
Hey @InfiniteXyy I'm trying to wrap this PR up but I am not allowed to push to your remote. Would you mind [allowing edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) in your fork? Thanks!

2024-09-23 15:04 UTC, InfiniteXyy commented
> Hey @InfiniteXyy I'm trying to wrap this PR up but I am not allowed to push to your remote. Would you mind [allowing edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) in your fork? Thanks!

I have enabled this, hope it's the correct place for allowing permission
![image](https://github.com/user-attachments/assets/a996b310-38a9-45ac-a972-22657ed3324b)

2024-09-23 15:52 UTC, yannbf approved these changes
Thank you so much for your contribution!

2024-09-23 16:38 UTC, merged