docs: Add example to the Indexer API doc
storybookjs/storybook pull request #29272
Opened 2024-10-03 17:47 UTC by Sidnioulz

## What I did

Added a doc example on the Indexer API, pointing to a Stackblitz that shows how to hack the Indexer API and a few other parts of SB to add external URLs to the sidebar.

This is useful because it shows how to connect arbitrary formats in the Indexer and in a Vite plugin that outputs CSF on each named export being indexed.

## Checklist for Contributors

### Testing

#### The changes in this PR are covered in the following automated tests:

_not relevant_

#### Manual testing

> [!CAUTION]
> Please note I couldn't live test the change. I couldn't manage to run frontpage and will require help to run it.

### Documentation

- [x] Add or update documentation reflecting your changes

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

2024-12-01 21:01 UTC, jonniebigodes requested changes
@Sidnioulz sorry for the delayed response on this pull request. I've checked and left one small item for you to look into when you can.

Let me know and we'll go from there.

Have a great day.

Stay safe

2024-12-01 21:01 UTC, jonniebigodes commented on docs/api/main-config/main-config-indexers.mdx
> +</details>
@Sidnioulz, we have a bit of room for improvement here and we could go with the following:
````suggestion

<details>
  <summary>Adding sidebar links from a URL collection</summary>

  The indexer API is flexible enough to let you process arbitrary content, so long as your framework tooling can transform the exports in that content into actual stories it can run. This advanced example demonstrates how you can create a custom indexer to process a collection of URLs, extract the title and URL from each page, and render them as sidebar links in the UI. Implemented with Svelte, it can be adapted to any framework.

  Start by creating the URL collection file (i.e., `src/MyLinks.url.js`) with a list of URLs listed as named exports. The indexer will use the export name as the story title and the value as the unique identifier.

  ```js title="MyLinks.url.js"
  export default {};

  export const DesignTokens = 'https://www.designtokens.org/';
  export const CobaltUI = 'https://cobalt-ui.pages.dev/';
  export const MiseEnMode = 'https://mode.place/';
  export const IndexerAPI = 'https://github.com/storybookjs/storybook/discussions/23176';
  ```

  Adjust your Vite configuration file to include a custom plugin complementing the indexer. This will allow Storybook to process and import the URl collection file as stories.

  ```ts title="vite.config.ts"
  import * as acorn from 'acorn';
  import * as walk from 'acorn-walk';
  import { defineConfig, type Plugin } from 'vite';
  import { svelte } from '@sveltejs/vite-plugin-svelte';

  function StorybookUrlLinksPlugin(): Plugin {
    return {
      name: 'storybook-url-links',
      async transform(code: string, id: string) {
        if (id.endsWith('.url.js')) {
          const ast = acorn.parse(code, {
            ecmaVersion: 2020,
            sourceType: 'module',
          });

          const namedExports: string[] = [];
          let defaultExport = 'export default {};';

          walk.simple(ast, {
            // Extracts the named exports, those represent our stories, and for each of them, we'll return a valid Svelte component.
            ExportNamedDeclaration(node: acorn.ExportNamedDeclaration) {
              if (
                node.declaration &&
                node.declaration.type === 'VariableDeclaration'
              ) {
                node.declaration.declarations.forEach((declaration) => {
                  if ('name' in declaration.id) {
                    namedExports.push(declaration.id.name);
                  }
                });
              }
            },
            // Preserve our default export.
            ExportDefaultDeclaration(node: acorn.ExportDefaultDeclaration) {
              defaultExport = code.slice(node.start, node.end);
            },
          });

          return {
            code: `
              import RedirectBack from '../../.storybook/components/RedirectBack.svelte';
              ${namedExports
                .map(
                  (name) =>
                    `export const ${name} = () => new RedirectBack({ target: 'storybook-root'});`
                )
                .join('\n')}
              ${defaultExport}
            `,
            map: null,
          };
        }
      },
    };
  }

  export default defineConfig({
    plugins: [StorybookUrlLinksPlugin(), svelte()],
  })
  ```

  Update your Storybook configuration (i.e., `.storybook/main.js|ts`) to include the custom indexer.

  ```ts title=".storybook/main.js|ts"
  import type { StorybookConfig } from '@storybook/svelte-vite';
  import type { Indexer } from '@storybook/types';

  const urlIndexer: Indexer = {
    test: /\.url\.js$/,
    createIndex: async (fileName, { makeTitle }) => {
      const fileData = await import(fileName);

      return Object.entries(fileData)
        .filter(([key]) => key != 'default')
        .map(([name, url]) => {
          return {
            type: 'docs',
            importPath: fileName,
            exportName: name,
            title: makeTitle(name)
              .replace(/([a-z])([A-Z])/g, '$1 $2')
              .trim(),
            __id: `url--${name}--${encodeURIComponent(url as string)}`,
            tags: ['!autodocs', 'url']
          };
        });
    }
  };

  const config: StorybookConfig = {
    stories: ['../src/**/*.stories.@(js|ts|svelte)', '../src/**/*.url.js'],
    framework: {
      name: '@storybook/svelte-vite',
      options: {},
    },
    experimental_indexers: async (existingIndexers) => [urlIndexer, ...existingIndexers]
  };
  export default config;
  ```

  Add a Storybook UI configuration file (i.e., `.storybook/manager.js|ts`) to render the indexed URLs as sidebar links in the UI:

  ```ts title=".storybook/manager.ts"
  import { addons } from '@storybook/manager-api';

  import SidebarLabelWrapper from './components/SidebarLabelWrapper.tsx';

  addons.setConfig({
      sidebar: {
        renderLabel: (item) => SidebarLabelWrapper({ item }),
      },
  });
  ```

  This example's code and live demo are available on [StackBlitz](https://stackblitz.com/~/github.com/Sidnioulz/storybook-sidebar-urls).

</details>
````

2024-12-02 05:03 UTC, Sidnioulz commented on docs/api/main-config/main-config-indexers.mdx
> +</details>
Thanks for the iteration on copy, @jonniebigodes :pray:

There's a tiny casing typo in your updated version, so I've taken the liberty to edit your suggestion before merging it.

2024-12-02 13:56 UTC, jonniebigodes approved these changes
@Sidnioulz, thank you for addressing the feedback and fixing the minor casing typo. Appreciate it 🙏 !  I've checked, and we're good to go on this end. I will gladly merge this once the checklist clears.

One small item for you to look into when you can. I was wondering if you have a bit of time to adjust the Stackblitz so that the URL links are easily readable for anyone who checks it, as you can see below:
![Content-Indexers-UI-issue](https://github.com/user-attachments/assets/11f56b42-4365-4282-b645-08509acfb4db)


Have a great day.

Stay safe

2024-12-02 14:29 UTC, merged

2024-12-02 17:22 UTC, Sidnioulz commented
> @Sidnioulz, thank you for addressing the feedback and fixing the minor casing typo. Appreciate it 🙏 ! I've checked, and we're good to go on this end. I will gladly merge this once the checklist clears.
> 
> One small item for you to look into when you can. I was wondering if you have a bit of time to adjust the Stackblitz so that the URL links are easily readable for anyone who checks it, as you can see below: ![Content-Indexers-UI-issue](https://private-user-images.githubusercontent.com/22988955/391569924-11f56b42-4365-4282-b645-08509acfb4db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNTg1NTQsIm5iZiI6MTczMzE1ODI1NCwicGF0aCI6Ii8yMjk4ODk1NS8zOTE1Njk5MjQtMTFmNTZiNDItNDM2NS00MjgyLWI2NDUtMDg1MDlhY2ZiNGRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDE2NTA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlN2ZlNWNiNzEwNDNlYjIxNjNlYWI0ZmM0MzExMWU2YjdiZTI4MGE4MTQ0ZTA0MjNkYzM1Y2I2ZTYwNjU4ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L0rNFBRvILw-ElAAK2k0k9eW579GymT3P2yEOnucfJU)
> 
> Have a great day.
> 
> Stay safe

Thanks for letting me know! I've switched to using `light-dark` so light colours have a default that works now. Didn't want to import emotion into the showcase as it's kind of beside the point, but I will in the future if others find other issues with this code.