Update docs to cover changes discussed in #22674
storybookjs/storybook pull request #29397
Opened 2024-10-18 14:37 UTC by rdebeasi

Related to #22674 (already closed) and #29386 (might close; I'm not sure).

## What I did

I documented a breaking change in Storybook v7, per [this recommendation](https://github.com/storybookjs/storybook/issues/22674#issuecomment-1600330886). I described the approach that I'm using instead. If there's a better option - or if you'd prefer for me to remove that code snippet - just let me know!

I also noticed that my editor removed some escaping and adjusted some whitespace. I think these changes are in line with the standards for this file, but I can back those changes out if they're incorrect. 

## Checklist for Contributors

### Testing

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

(Not applicable - documentation only)

#### Manual testing

This change includes documentation only.

### Documentation

- [ ] Add or update documentation reflecting your changes
- [x] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

2024-11-06 18:41 UTC, valentinpalkovic approved these changes

2024-11-06 18:42 UTC, jonniebigodes commented on MIGRATION.md
> +```
````suggestion
#### Angular: Initializer functions

Initializer functions using the `APP_INITIALIZER` dependency injection token only run when the component renders. To ensure an initializer function is always executed, you can adjust your `.storybook/preview.ts` and invoke it directly.

```js
myCustomInitializer();
export default preview;
```
````

2024-11-06 18:45 UTC, jonniebigodes requested changes
@rdebeasi, thanks for putting together this pull request and helping improve the migration guide with this important information. Appreciate it 🙏 ! I left one small item for you to look into when you can.

Let me know once you've addressed it, and I'll gladly merge this one.

@valentinpalkovic thanks for taking a look into this as well 🙏

2024-11-22 21:38 UTC, rdebeasi commented
Updated. Thank you for taking a look!

2024-11-22 21:42 UTC, jonniebigodes approved these changes

2024-11-22 21:42 UTC, jonniebigodes commented
@rdebeasi thanks for addressing the feedback! Appreciate it 🙏 ! I'll gladly merge this once the checklist clears.

Have a great day.

Stay safe

2024-11-22 22:30 UTC, merged

2024-12-05 16:47 UTC, twesk commented on MIGRATION.md
> +myCustomInitializer();
I'm trying to initialize some services, which would normally happen during the APP_INITIALIZER stage in the main app

2024-12-05 17:22 UTC, twesk commented on MIGRATION.md
> +myCustomInitializer();
Ok figured it out - looks like the solution was use `applicationConfig` instead of `moduleMetadata`