CLI: Add index command
storybookjs/storybook pull request #30071
Opened 2024-12-16 03:27 UTC by shilman

Closes #

## What I did

## Checklist for Contributors

### Testing

#### The changes in this PR are covered in the following automated tests:

- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli-storybook/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

  - `bug`: Internal changes that fixes incorrect behavior.
  - `maintenance`: User-facing maintenance tasks.
  - `dependencies`: Upgrading (sometimes downgrading) dependencies.
  - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
  - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
  - `documentation`: Documentation **only** changes. Will not show up in release changelog.
  - `feature request`: Introducing a new feature.
  - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
  - `other`: Changes that don't fit in the above categories.

   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

2024-12-16 03:51 UTC, tmeasday commented on code/core/src/core-server/build-index.ts
> +};
Should this get added to `standalone.ts` also? I'm not quite sure what's up with that API.

2025-02-27 19:46 UTC, JReinhold requested changes
Looks good apart from a few comments.

I also think most of greptile's comments are correct.

2025-02-27 19:46 UTC, JReinhold commented on code/core/src/cli/buildIndex.ts
> +  invariant(packageJson, 'Failed to find the closest package.json file.');
you already do this in the `cli/index.ts` file that calls this function

2025-02-27 19:46 UTC, JReinhold commented on code/core/src/core-server/build-index.ts
> +export const buildIndex = async (options: BuildIndexOptions) => {
I think a big chunk of this code could be replaced by a single call to `loadStorybook` - https://github.com/storybookjs/storybook/blob/next/code/core/src/core-server/load.ts/#L15

That function is new in 8.5

2025-02-27 21:55 UTC, dannyhw commented on code/core/src/core-server/build-index.ts
> +export const buildIndex = async (options: BuildIndexOptions) => {
I don't think buildIndex node function outputs to file right? I was testing this and its requiring a outputFile which I think should not be required in the options to this function

2025-02-28 07:54 UTC, ndelangen commented on code/package.json
> +    "storybook:ui:index": "NODE_OPTIONS=\"--preserve-symlinks --preserve-symlinks-main\" ./lib/cli/bin/index.cjs index --config-dir ./.storybook",
What's this npm-script used for?

2025-03-01 04:46 UTC, shilman commented on code/package.json
> +    "storybook:ui:index": "NODE_OPTIONS=\"--preserve-symlinks --preserve-symlinks-main\" ./lib/cli/bin/index.cjs index --config-dir ./.storybook",
Was using it to test the command, will remove

2025-03-01 05:34 UTC, shilman commented on code/core/src/core-server/standalone.ts
>  async function build(options: any = {}, frameworkOptions: any = {}) {
Out of scope IMO. I think the node API should be reconsidered and possibly even remove this layer.

2025-03-01 05:35 UTC, shilman commented
@JReinhold thanks for the feedback. I think I addressed everybody's comments.

2025-03-04 01:17 UTC, merged