Select the first story in tree when opening a tree item
storybookjs/storybook pull request #3105
Opened 2018-02-26 23:57 UTC by real34

## What I did

I improved the tree view to automatically select the first story (leaf) when opening a group if possible. It allows the styleguide to open a section more easily so an user could go to the content faster.

## How to test

Is this testable with jest or storyshots? Not sure

Does this need a new example in the kitchen sink apps? No

Does this need an update to the documentation? No

2018-02-27 00:12 UTC, Hypnosphi commented
@igor-dv AFAIR, you intentionally removed this behaviour at some point

2018-02-27 07:58 UTC, igor-dv requested changes
Yeah, there was an old discussion here #1699. IMO it doesn't make anything easier. 
Anyway, if this is a wanted behavior at least it should be configurable.

2018-02-27 08:03 UTC, igor-dv commented
CC. #2863

2018-02-27 09:37 UTC, real34 commented
I’d be glad to add a configuration for this.

However I have not yet taken the time to setup the tests locally, and might find time for it only Friday I think. Do you think it could be on time for the `3.4.0` release ?

2018-02-27 09:42 UTC, igor-dv commented
I think the release should be somewhere soon. If you won't be ready up to the time, maybe we will be able to sneak it as a patch release after.

CC. @shilman.

2018-04-30 23:35 UTC, closed without merging

2018-09-27 19:46 UTC, creatyvtype commented
@real34 did this ever get implemented?