addon-options: Make shortcuts in storybook optional
storybookjs/storybook pull request #3237
Opened 2018-03-19 15:48 UTC by PunitGr

Issue: #3196 

## What I did
I've added an option for `enabling/disabling` keyboard shortcuts.

## How to test
One can try this feature by updating the storybook `config.js` as:
```javascript
setOptions({
    ...
    enableShortcuts: false, // true by default
})

This will disable the shortcuts.
```

2018-03-19 16:06 UTC, Hypnosphi commented
Should we remove shortcuts help button and popup when shortcuts are disabled?

2018-03-19 17:22 UTC, PunitGr commented
Yeah, that makes sense to disable it. Or we can add a text saying that `shortcuts` have been disabled.

2018-03-20 12:58 UTC, PunitGr commented
Hey @Hypnosphi, Removed the shortcut help button when `enableShortcuts: false`.
![screen shot 2018-03-20 at 6 24 21 pm](https://user-images.githubusercontent.com/9111111/37655853-6289826e-2c6c-11e8-984c-5930a9f7379d.png)

2018-03-20 14:38 UTC, Hypnosphi requested changes

2018-03-20 14:38 UTC, Hypnosphi commented on lib/ui/src/modules/ui/components/stories_panel/index.js
> +  shortcutOptions: PropTypes.objectof(
typo: `objectOf`

But it's actually not needed here, it should be just `shape`

2018-03-20 21:27 UTC, Hypnosphi approved these changes

2018-03-20 21:27 UTC, merged