RN Disables websockets when using onDeviceUI
storybookjs/storybook pull request #3278
Opened 2018-03-24 18:28 UTC by Gongreg

This change will by default disable websockets when using onDeviceUI.
I've also added option enable websockets back.

Issue is #3271

There are few questions that I have:

1. Do we need the option in the first place. Is there anybody using onDeviceUI with websockets. Can we brake it for them? Should we brake it?

2. If we keep the option where it should be documented.

3. There is an increasing need to add tests for RN part. 

4. Where is resetStorybook option used at all? What does it bring. Why would we want to reset channel if it already exists?

2018-03-24 18:43 UTC, danielduan commented
Breaking this would basically disable all addons by default right? Since our addons don’t run inside the device UI?

I’m definitely in support of just removing it permanently instead of keeping it as an option. It will make maintaining a lot easier. Wondering if we can get some usage data.

2018-03-24 20:27 UTC, Gongreg commented
You are correct, if we implement is and user is using onDeviceUI the addons would be disabled (unless he specifically says useWebsockets in options.

Nonetheless the current implementation I've done in our app is to simply check whether storybook is running with simple fetch.

Something like

```
  fetch('http://localhost:7007')
	.then(() => this.setState({UI: getStorybook()}))
    .catch(() => this.setState({UI: getStorybook(..., {onDeviceUI: true})}));
```

So if server is running onDeviceUI is disabled and addons work, if server is down, it simply displays stories without any addons.

2018-03-24 21:14 UTC, danielduan approved these changes

2018-03-24 21:28 UTC, danielduan commented
Maybe we can put that fetch test as a default in the getstorybook cli template?

2018-03-24 21:44 UTC, Gongreg commented
It could be added I guess, just need to think what about port/host? Should we do separate PR for it?

2018-03-24 21:49 UTC, danielduan commented
That’s probably a better idea

2018-03-25 18:13 UTC, shilman requested changes
This change makes sense to me, and I like that it's still possible to use plugins if you depend on them.

Can we document the `useWebsockets` option as part of this PR, and also document the fact that after this PR, `onDeviceUI` will make the native storybook standalone unless you specify `useWebsockets`? Since it's a big breaking change, it needs a documentation update, both in the normal docs and also in the migration guide (assuming this is a 4.0 feature)

2018-03-27 19:10 UTC, f0rr0 commented
I was able to get a standalone build working without changing anything in the storybook source. I'm assuming not having a server running throws errors but they are silently consumed?

2018-04-05 18:04 UTC, danielduan commented
@f0rr0 do you have a public repo somewhere where you are running Storybook RN without the web UI?

2018-04-26 23:15 UTC, rmevans9 commented
@f0rr0 It depends on platform too. I think on iOS if the websocket connection fails it just silently eats that error but Android makes a lot of noise (red boxes) if it fails.

2018-05-18 06:43 UTC, Gongreg commented
Still relevant.

2018-05-23 15:04 UTC, closed without merging