Fix links and code examples in addons/knobs
storybookjs/storybook pull request #3359
Opened 2018-04-05 12:18 UTC by SilencerWeb

Issue: broken links and not appropriate code examples to screenshot

## What I did
Fixed links and code examples

2018-04-05 12:41 UTC, Hypnosphi commented on addons/knobs/README.md
> +> Checkout the above [Live Storybook](https://goo.gl/uX9WLf) or [watch this video](https://www.youtube.com/watch?v=kopW6vzs9dg&feature=youtu.be).
This example uses some pretty outdated version of storybook. Please use this one instead:
https://storybooks-official.netlify.com/?knob-Dollars=12.5&knob-Name=Storyteller&knob-Years%20in%20NY=9&knob-background=%23ffff00&knob-Age=70&knob-Items%5B0%5D=Laptop&knob-Items%5B1%5D=Book&knob-Items%5B2%5D=Whiskey&knob-Other%20Fruit=lime&knob-Birthday=1484870400000&knob-Nice=true&knob-Styles=%7B%22border%22%3A%223px%20solid%20%23ff00ff%22%2C%22padding%22%3A%2210px%22%7D&knob-Fruit=apple&selectedKind=Addons%7CKnobs.withKnobs&selectedStory=tweaks%20static%20values&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

2018-04-05 12:41 UTC, Hypnosphi submitted a review, later dismissed
see comment

2018-04-13 16:19 UTC, danielduan approved these changes

2018-04-13 23:13 UTC, Hypnosphi commented
I think we need to take new screenshots as well

2018-04-13 23:15 UTC, Hypnosphi requested changes
"Live Storybook with Knobs" link is still outdated:

https://github.com/SilencerWeb/storybook/blob/d1949e353c58934a357bc51b17e3a8705f3a1e64/addons/knobs/README.md#additional-links

2018-04-17 15:29 UTC, danielduan commented
@Hypnosphi I removed that section because half the links don't work and the other half are duplicated from the top section

2018-04-22 14:09 UTC, Hypnosphi approved these changes

2018-05-05 09:33 UTC, wuweiweiwu approved these changes

2018-05-05 09:34 UTC, merged