using disableWebsockets instead of useWebsockets
storybookjs/storybook pull request #3686
Opened 2018-05-30 08:01 UTC by Gongreg

Additional PR for #3636. As discussed with @shilman it would be better to maintain backwards compatibility with using both onDeviceUI and storybook server at the same time. So I swapped useWebsockets with disableWebsockets. So now if somebody will want to use storybook without server in the app he will have to pass in the disableWebsockets option. This will be described in some documentation when we start separating RN storybook into two parts.

2018-05-30 08:13 UTC, shilman requested changes
LGTM, can we also document this in the README?

2018-05-30 14:07 UTC, shilman approved these changes

2018-05-31 10:52 UTC, Hypnosphi commented
@shilman IDK, some problem with cached dependencies maybe. Corresponding TeamCity build passes

2018-05-31 10:53 UTC, merged

2018-05-31 11:00 UTC, Hypnosphi commented
@shilman To make it more deterministic, you can add `marko-widgets` as top-level `devDependency`