Homepage: Replace ♥️ with ❤
storybookjs/storybook pull request #3799
Opened 2018-06-26 11:06 UTC by moigagoo

"Black Heart Suit" is rendered black on some platforms (e.g. Edge, Firefox). "Red Heart Emoji" is always rendered red.

Refs:
- https://emojipedia.org/black-heart-suit/
- https://emojipedia.org/heavy-black-heart/

Issue:

## What I did

## How to test

Is this testable with Jest or Chromatic screenshots?
Does this need a new example in the kitchen sink apps?
Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

For maintainers only: Please tag your pull request with at least one of the following:
`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

2018-06-26 17:20 UTC, Hypnosphi requested changes
It renders black on Chrome on my mac:
https://deploy-preview-3799--storybooks.netlify.com

![image](https://user-images.githubusercontent.com/6651625/41928655-2cd69934-7976-11e8-9b10-bc24f5415cea.png)

2018-06-27 07:29 UTC, moigagoo commented
@Hypnosphi I guess there's no universal solution then. It either works on Windows (not only Edge, I also checked Chrome) or macOS. Should I close the PR?

2018-06-27 13:51 UTC, igor-dv commented
What about OS detection?

2018-06-27 19:02 UTC, moigagoo commented
@igor-dv 

> What is about OS detection?

Honestly, that sounds like way too much work for such an insignificant feature ¯\_(ツ)_/¯

2018-06-28 13:51 UTC, closed without merging