horizontal display for addon-knobs radios UI
storybookjs/storybook pull request #3922
Opened 2018-07-26 12:09 UTC by astrotim

Issue:

Recently merged "radios" knob [(#3894)](https://github.com/storybooks/storybook/pull/3894) is a great new addition from @brycemhammond. The existing implementation, however, displays the radio inputs vertically, and since space can be limited in the addons panel, I propose that the radio inputs be displayed horizontally.

## What I did

Added three lines of CSS to display the `radios` knobs UI horizontally.

**Before**

<img src="http://astronautweb.co/wp-content/uploads/2018/07/radios-vert.png" height="67" alt="before" />

**After**

<img src="http://astronautweb.co/wp-content/uploads/2018/07/radios-horiz.png" height="45" alt="after" />

## How to test

Is this testable with Jest or Chromatic screenshots? 
No.
Does this need a new example in the kitchen sink apps? 
No.
Does this need an update to the documentation?
No.

If your answer is yes to any of these, please make sure to include it in your PR.

For maintainers only: Please tag your pull request with at least one of the following:
`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

2018-07-26 20:46 UTC, Primigenus commented
This wouldn't work for all situations since some people might use the addons panel docked to the side and with very little horizontal space available. Longer labels for each radio button would also run off the side.

2018-07-27 02:18 UTC, astrotim commented
@Primigenus The CSS includes `flexWrap: wrap` so the radio inputs will wrap across multiple lines, rather than running off the side. But I get what you're saying about users that have the addons panel docked to the side.

How about I include a display prop with `horizontal | vertical` options?

2018-07-27 06:09 UTC, ndelangen commented
I checked out:
https://deploy-preview-3922--storybooks-official.netlify.com/?selectedKind=Addons%7CKnobs.withKnobs&selectedStory=tweaks%20static%20values%20organized%20in%20groups&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs

And this solution seems fine to me.
What do you think @Primigenus ?

2018-07-27 17:51 UTC, Primigenus commented
LGTM with flexWrap! Thanks!

2018-07-28 12:11 UTC, Hypnosphi commented
I'd prefer to use button group for horizontal display instead

2018-07-28 12:13 UTC, Hypnosphi requested changes
I'd prefer to use a button group for horizontal display instead. Otherwise it will be too confusing if you have one radio group next to another:
<img width="352" alt="bildschirmfoto 2018-07-28 um 15 20 46" src="https://user-images.githubusercontent.com/6651625/43356476-ea0177ba-9279-11e8-9b6e-c5dd2987ae1f.png">

2018-07-29 23:29 UTC, astrotim commented
@Hypnosphi what exactly do you mean by "button group"? Are you referring to styling the inputs as buttons which was popularised by Bootstrap? Are you requesting this to be developed as a different knob to 'radios', or are you requesting that the existing 'radios' knob have an option to style it as a group of buttons?

IMO, I don't think the screenshot you've included looks confusing. The two sets of radios each have an obvious label and are separated by a dividing line.

2018-07-29 23:40 UTC, Hypnosphi commented
Yes, something like this: 

![](http://i.stack.imgur.com/V2XqL.jpg)

I think it should work as "inline" option for radio knob or something like that. Actually, we could merge `select` and `radio` knobs together because they’re are just different presentations of the same control. It could have some more generic name, like "options" or "enum". It would be more consistent with other knob names as they represent the data type not the actual ui element.

If we're going to do that, right now is the best time because we're approaching a major release and xan introduce breaking changes

2018-07-29 23:41 UTC, Hypnosphi commented
>  I don't think the screenshot you've included looks confusing

Good for you =) As for me, it requires a bit of mental effort comparing to conventional vertical radios

2018-07-30 00:32 UTC, astrotim commented
I think adding styling like this introduces a bunch of edge case overhead, primarily when the buttons don't fit within the available horizontal space. I don't really want to go down that road.

2018-07-30 00:35 UTC, Hypnosphi commented
That's why it's good to have it as an option: people could use it or not depending on how they position their addons panel

2018-07-30 00:39 UTC, astrotim commented
Sure, that's fair enough, but I'd prefer to scope the horizontal layout of native UI to the option, rather than introduce a different UI altogether.

2018-07-30 02:38 UTC, Primigenus commented
How about defaulting to a vertical list if the panel is docked on the side and to a horizontal layout if it's docked at the bottom?

2018-07-31 08:30 UTC, ndelangen commented
Here's an idea:

The select, radios are actually similar if not equal in implementation but their display is just different.
I'd suggest we merge this as is, and at a later stage we reform/refactor into 1 generic "pic a few from a list of options" knob that has different display-modes.

One of those can be what you're suggesting @Hypnosphi and others can choose what they prefer. That way everyone wins.

2018-07-31 08:30 UTC, ndelangen approved these changes

2018-07-31 10:39 UTC, astrotim commented
@ndelangen awesome idea! #winning 

On the subject of display modes, I've recently been wondering if the `select` UI could be updated to use [react-select](https://react-select.com) under the hood. I might have a crack at it...

2018-08-01 06:03 UTC, ndelangen commented
@Hypnosphi do you agree with this action?

@astrotim If you're going to continue contributing I'd to invite you to the storybook organisation. Would you be able to do a online meeting some time this week?

2018-08-02 15:55 UTC, Hypnosphi approved these changes

2018-08-02 15:56 UTC, Hypnosphi commented
@ndelangen yes, this is basically what I've suggested in https://github.com/storybooks/storybook/pull/3922#issuecomment-408714316

It would be nice to do that in 4.0

2018-08-02 20:47 UTC, merged

2018-08-02 20:49 UTC, ndelangen commented
Yes let'd do that! I have a online meeting with with @astrotim tomorrow early morning 8 UTC+2. You can of course join if you'd like? 👍