UPGRADE packages
storybookjs/storybook pull request #3996
Opened 2018-08-10 14:41 UTC by ndelangen

UPGRADE more packages

2018-08-14 21:30 UTC, danielduan approved these changes

2018-08-15 07:21 UTC, pksunkara requested changes

2018-08-15 09:15 UTC, ndelangen commented
Yeah I do

2018-08-27 09:34 UTC, pksunkara commented
Please upgrade universal-dotenv to `^1.9.0`

2018-08-27 10:39 UTC, ndelangen commented
strange that that upgrade doesn't come up when performing `yarn upgrade-interactive --latest` :(

I will @pksunkara

2018-08-31 15:49 UTC, merged