Remove gh-pages deploy in favor of netlify
storybookjs/storybook pull request #4128
Opened 2018-09-06 00:35 UTC by shilman

Issue: #4126 

## What I did

- Remove gh-pages deploy from circle config
- Keep the docs build just so we can be sure that it builds
- Keep the deploy step as a placeholder

## How to test

Not really testable until we merge this into a tag `vX.Y.Z` commit. But I've been messing around with this for an hour or so, and am confident it's safe.

Is this testable with Jest or Chromatic screenshots?
Does this need a new example in the kitchen sink apps?
Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

For maintainers only: Please tag your pull request with at least one of the following:
`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

2018-09-06 06:29 UTC, pksunkara commented on .circleci/config.yml
> +            echo "Nothing to deploy"
You can remove the whole job.

2018-09-06 10:30 UTC, ndelangen approved these changes
please remove the whole job from config

2018-09-06 13:32 UTC, pksunkara requested changes
https://github.com/storybooks/storybook/issues/4126#issuecomment-419094402

2018-09-06 20:07 UTC, pksunkara commented
@shilman Before merging this PR, could you please address this? https://github.com/storybooks/storybook/issues/4126#issuecomment-419094402. We need to figure out what process we are going to follow.

2018-09-07 18:47 UTC, pksunkara approved these changes

2018-09-07 18:48 UTC, pksunkara commented
I actually realized that the current deploy job is broken anyway because of circleci tag filter rule. So, I am merging this.

2018-09-07 18:48 UTC, merged