removed yarn workspaces and added packages to lerna.json
storybookjs/storybook pull request #4275
Opened 2018-10-03 19:05 UTC by dakebl

Issue: https://github.com/storybooks/storybook/issues/4204

## What I did
I removed the yarn workspaces config from package.json and added the directory paths to lerna.json

## How to test

Is this testable with Jest or Chromatic screenshots? No
Does this need a new example in the kitchen sink apps? No
Does this need an update to the documentation? No

If your answer is yes to any of these, please make sure to include it in your PR.

For maintainers only: Please tag your pull request with at least one of the following:
`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

2018-10-03 19:17 UTC, gabrielcsapo commented
@dakebl is there a performance change in this respect? When you would run `yarn` would it pull in the lerna dependencies?

2018-10-03 22:14 UTC, dakebl commented
Hey @gabrielcsapo, sorry for the late response. It looks like a received a false positive when I raised this PR due to my setup. I've since worked on it a little further and it looks like yarn workspaces and lerna can play nicely together once lerna.json has the packages array added to it. 

To test this, I:
- removed all of the node_modules with `lerna clean`
- ran `yarn` to install and link the packages
- ran `yarn publish:alpha -- --npm-skip`. Which seems to be correctly generating the relevant release in my forked repo. 

Without the npm publishing portion of the script however, I can't verify the performance of the script or detect any further errors that happen during the process. Would you be able to test this?

2018-10-04 08:40 UTC, pksunkara requested changes

2018-10-04 08:40 UTC, pksunkara commented on lerna.json
> +    "lib/cli/test/run/*"
This needs to be removed. That was the issue in #4204 in the first place.

2018-10-04 22:19 UTC, closed without merging