Removed react-native-vanilla and react-native-typescript examples.
storybookjs/storybook pull request #4311
Opened 2018-10-07 13:17 UTC by Gongreg

## Removed react native vanilla/react native typescript examples.

These examples are not really maintained. Since we are removing packager from storybook and trying to unify experience for crna/rn vanilla, there is no need to keep this code.

2018-10-07 21:04 UTC, pksunkara requested changes
Also, please remove the `--reactnative` from CONTRIBUTING.md. Otherwise, the PR looks great.

2018-10-07 21:04 UTC, pksunkara commented on .circleci/config.yml
>            command: yarn bootstrap --reactnative --reactnativeapp
`--reactnative` flag should be removed from this line.

2018-10-07 21:04 UTC, pksunkara commented on .teamcity/OpenSourceProjects_Storybook/buildTypes/OpenSourceProjects_Storybook_ReactNative.kt
> -        }
There are 2 `--reactnative` flags in this file in other steps. Please correct them.

2018-10-08 06:32 UTC, Gongreg commented
Thanks @pksunkara, I've updated my PR. :)

2018-10-08 07:25 UTC, pksunkara approved these changes

2018-10-08 07:25 UTC, merged