Type safe select
storybookjs/storybook pull request #4314
Opened 2018-10-07 20:36 UTC by ca057

Issue:

This solves the case in the `select`-knob when you pass in an array or an object where the values are not strings but the prop the knob is used for expects another type (e.g. a number), see for example issue #4106 

## What I did
The passed in options of the `select`-knob are stored in the local state, so they are not converted to strings when setting them as a value of the `option`-element. On a selection, the original value will be received from the state.

## How to test

Is this testable with Jest or Chromatic screenshots?
Does this need a new example in the kitchen sink apps? yes - see added story for testing.
Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

For maintainers only: Please tag your pull request with at least one of the following:
`["cleanup", "BREAKING CHANGE", "feature request", "bug", "documentation", "maintenance", "dependencies", "other"]`

2018-10-10 18:57 UTC, ndelangen requested changes

2018-10-10 18:57 UTC, ndelangen commented on addons/knobs/src/components/types/Select.js
> +  static getDerivedStateFromProps({ knob }) {
I think we can instead use memoization here to achieve the same performance.

What do you think? It's usually recommended to use memoization over getDerivedStateFromProps.

2018-10-10 18:57 UTC, ndelangen commented on examples/cra-kitchen-sink/src/stories/type-safe-select.stories.js
> +import React from 'react';
Should move this into the official example for addon knobs, the cra example should be a lean and simple showcase our compatibility with CRA, not demo every possible addon/options. That's what the official example is for 😄

2018-10-10 18:58 UTC, ndelangen commented
Awesome work @ca057 !

Thank you for improving the knobs addon, this makes a ton of sense.

What do you think about my comment of the usage of getDerivedStateFromProps? Happy to keep it if you feel this is a better solution.

2018-10-11 16:52 UTC, ca057 commented
Hey @ndelangen !

Thanks for the feedback! I’m happy to improve that 👍

2018-12-01 23:36 UTC, igor-dv commented
Any plans on finishing this PR?

2018-12-02 12:56 UTC, ca057 commented
> Any plans on finishing this PR?

Hey - yes! I have it open for the whole weekend to continue it again. Sorry, I was out the last month. Let me update my PR to include the latest changes and work on the comments from @ndelangen .

2018-12-06 13:02 UTC, ca057 commented
@igor-dv I checked out the latest version of Storybook and saw that this feature was added in the meantime by another PR. Can you check the latest version please and confirm this? I would then close this PR. Thanks for your patience.

2018-12-13 08:54 UTC, ndelangen commented
Yeah this seems to be fixed already, thank you @ca057 for your time and energy.
Bit sad your PR didn't get merged, but want to let you know I truly appreciate the effort you put in.

2018-12-13 08:54 UTC, closed without merging