V5 style refinements
storybookjs/storybook pull request #5444
Opened 2019-02-01 00:25 UTC by domyen

Note: Based on #5426, #5425, #5428 (merge this one first)
Issue: More progress on decomposing stories and components in the UI

## What I did
- Added placeholder stories for Sidebar
- Added Global styles on `body`
- Refactored Sidebar explorer, treeview, and StoriesExplorer into one file
- Removed unused files leftover from Tom's refactor
- Minor tweaks to styles and how we organize Storybook's own stories

2019-02-01 00:45 UTC, tmeasday requested changes
Seems good apart from (a) surplus component and (b) crippling of the search?

2019-02-01 00:45 UTC, tmeasday commented on lib/ui/src/components/sidebar/SidebarList.js
> +export default SidebarList;
What is this component? I think what you call the `SidebarList` is the `StoriesExplorer` which already is built and has these stories

2019-02-01 00:45 UTC, tmeasday commented on lib/ui/src/components/sidebar/SidebarSearch.stories.js
> +));
OI! What did you do to my stories!!

2019-02-01 05:41 UTC, tmeasday approved these changes

2019-02-01 14:58 UTC, ndelangen commented
https://circleci.com/workflow-run/5d2d070c-1e99-4d0d-a191-d5c5c6738d98

2019-02-01 14:59 UTC, ndelangen commented
@domyen I think there's a few regressions here, also the fonts look a bit too big, (maybe that's on purpose?)

Do you want to fix them in this branch?

2019-02-01 16:06 UTC, domyen commented
I'm working on the styling infra so expect a lot of visual regressions while work is in progress. 

Though I'd prefer to merge into `next` often, it might not make sense given the breadth of visual changes and all the story renaming/editing/removing. How about I keep this branch up to date with `next` and submit the PR when closer to stable? @tmeasday 

@ndelangen Yea I'd prefer to fix them on this branch.

2019-02-09 03:08 UTC, shilman commented
@domyen merging this now to get a beta out

2019-02-09 03:09 UTC, merged