Fix/tool addons
storybookjs/storybook pull request #5452
Opened 2019-02-01 12:47 UTC by ndelangen

fixes: https://github.com/storybooks/storybook/issues/5416

I removed the need for tool addons to find the iframe, instead they can inject global styles, hwihc is marginally better then setting inline styles.

Long term i want to add a addon-type to wrap the preview component, so this can be done very cleanly.

@Ailrun care to review?

2019-02-01 16:49 UTC, ndelangen commented
Weird the image tests work on my machine..

2019-02-01 17:14 UTC, ndelangen commented
darnit

2019-02-02 02:06 UTC, tmeasday requested changes
I'm the first to do a complicated list comphrension but I think this one might be a step too far ;)

2019-02-02 02:06 UTC, tmeasday commented on addons/viewport/src/Tool.js
> +              acc.selected = id;
I don't understand this code. Does it keep setting `acc.selected` if `state.selected` isn't in the list? It seems like it'll do this for every item in the list.

I think this code is overly complex for what it is trying to do -- or maybe I don't understand it? In either case I think it needs to be clearer. I *think* this is what it shoudl probably look like:

```js
const items = list && list.length && list.map(({ name, styles: value, id }) => ({name, value, id});

// It actually will be the *last* element in the list in the code above I think, but I doubt this is what you meant?
const selected = (state.selected === 'responsive' || list.find(i => i.id === state.selected))  ? state.selected : list[0].id;

return {
  list,
  selected,
  isRotated: state.isRotated,
};
```

2019-02-02 02:06 UTC, tmeasday commented on addons/backgrounds/src/Tool.js
> +          acc.items.push({ name, value });
Same comment here as for the other addon

2019-02-04 14:19 UTC, ndelangen commented
@tmeasday I improved to code, thanks!

2019-02-04 21:04 UTC, merged