CHANGE the keyboard shortcuts of toggleNav & togglePanel
storybookjs/storybook pull request #5677
Opened 2019-02-20 10:27 UTC by ndelangen

Issue: https://github.com/storybooks/storybook/issues/5666

## What I did
FLIP the shortcuts

2019-02-20 10:53 UTC, tmeasday approved these changes

2019-02-20 15:24 UTC, shilman requested changes
@ndelangen missed one and the tests are failing:

```
 FAIL  lib/ui/src/core/shortcuts.test.js
  ● shortcuts api › sets defaults, augmenting anything that was persisted
```

2019-02-20 18:16 UTC, ndelangen commented
Fixed

2019-02-21 06:24 UTC, shilman approved these changes

2019-02-21 06:24 UTC, merged