docs(addons): add hint about addon tab order
storybookjs/storybook pull request #6021
Opened 2019-03-11 15:45 UTC by HerrBertling

which I missed and I guess would be rather helpful for others searching for this.

Issue: #6019 

## What I did

Added a short paragraph about how to change the tab order. I also inserted some headlines to structure the page a bit more. Also, because of the injected paragraph, I changed the sentence about the usage since it now lacked context.

## How to test

1. Start the docs subfolder as described in its readme.
1. Navigate to "Using addons".
1. Read the sentence 😆

2019-03-11 20:15 UTC, shilman approved these changes
LGTM tho I'm not sure this still makes sense in SB5 where the notes addon is a `TAB` type? @ndelangen?

2019-03-11 20:18 UTC, shilman requested changes
On second thought I think this doesn't make sense in SB5 since addon-notes doesn't show up in the addons panel anymore. Can you use an example like `knobs` that does? cc @ndelangen

2019-03-12 07:53 UTC, HerrBertling commented
> Can you use an example like knobs that does?

Sure!

2019-03-16 00:16 UTC, ndelangen approved these changes

2019-03-16 00:48 UTC, shilman approved these changes

2019-03-16 00:49 UTC, merged