Check if regex and regex.test is available before calling it
storybookjs/storybook pull request #608
Opened 2016-11-08 12:27 UTC by kitze

Trying to fix #607 

https://github.com/storybooks/react-storybook/issues/607

2016-11-08 12:29 UTC, arunoda commented
We need to do this.
But I wanna know about the real cause of the #607 .
Could you reply to my comment on #607?

2016-11-08 12:32 UTC, kitze commented
@arunoda just replied.

2016-11-08 17:30 UTC, arunoda requested changes
After that, we are good to go.

2016-11-08 17:30 UTC, arunoda commented on src/server/config.js
> +      return value || [].concat(loader.test).some((loader) => {
Could you rename this loader name into something like `matcher`.
Like this:

```js
return value || [].concat(loader.test).some((matcher) => { ...
```

2016-11-09 09:30 UTC, kitze commented on src/server/config.js
> +      return value || [].concat(loader.test).some((loader) => {
@arunoda done!

2016-11-09 10:25 UTC, arunoda approved these changes

2016-11-09 10:26 UTC, arunoda commented
Awesome.

2016-11-09 10:26 UTC, merged