Fix performance of Angular rerender
storybookjs/storybook pull request #6094
Opened 2019-03-14 19:21 UTC by jonrimmer

Issue: #4098 

## What I did

- Rewrote forced render handling for Angular to not recreate the whole app, but instead send the updated props to the application using RxJS, then trigger change detection.
 - Added a `disableDebounce` option to knobs so you can disable the 350ms debounce if you know the re-rendering of the framework you're using isn't broken.

## How to test

Run the Angular exa,ple and use the knobs. Observe that they update immediately and without lag.

2019-03-15 03:14 UTC, shilman requested changes
@jonrimmer Thanks for this---looks like an awesome solution to a thorny problem! I'm not familiar with Angular enough to do a review, hoping @igor-dv @kroeder @CodeByAlex can take a look.

My two suggestions:
- Use `addParameters({knobs: {disableDebounce: true}}` instead of `withKnobs({ disableDebounce: true })` => we're trying to migrate everything over to parameters across the board
- I think the knobs debouncing by @CodeByAlex was mostly for angular. If this PR solves the problem for angular, can we also remove debouncing in the knobs addon?

2019-03-15 09:35 UTC, jonrimmer commented
@shilman No problem, I'll update it as you suggest.

Centralised debouncing should be removable if each framework's app implements forced re-render in a way that's sympathetic to its method of receiving updates and updating the DOM. For React and React-esque frameworks that should already be the case, and this PR fixes the situation for Angular.

What I'm not clear about is what the situation is like for other frameworks like Polymer, Vue, etc. It certainly seems like Vue was affected prior to the debounce being added: https://github.com/storybooks/storybook/issues/6005

2019-03-15 09:48 UTC, ndelangen commented
@jonrimmer I invited you to the GitHub organisation so you con contribute more easily 👍

2019-03-15 09:51 UTC, ndelangen approved these changes

2019-03-15 09:51 UTC, ndelangen commented
Looks good to me, let's get a second opinion out of @kroeder before merging

2019-03-15 10:10 UTC, jonrimmer commented
@ndelangen Thanks, I really appreciate it.

2019-03-15 10:26 UTC, shilman commented
@jonrimmer Good call on making sure Vue works properly, so we can potentially remove global debouncing separately. Super happy with this solution for Angular tho--great work!

2019-03-15 10:33 UTC, CodeByAlex commented
@shilman @jonrimmer LGTM

2019-03-16 10:57 UTC, gaetanmaisse approved these changes

2019-03-18 03:56 UTC, shilman approved these changes

2019-03-18 08:13 UTC, backbone87 commented
since the 4.2 alpha introduced my changes to the storybook vue, debouncing the knobs should **not** be necessary at all for vue, since we properly change the props of the components in a reactive "vue way".

2019-03-19 12:52 UTC, merged