Fix addon-knobs ObjectType knob react warning #5276
storybookjs/storybook pull request #6159
Opened 2019-03-18 20:13 UTC by leoyli

Issue: #5276 

## What I did

- Fixed the `getDerivedStateFromProps` console warning due to no initial state provided to React.

## How to test

- Is this testable with Jest or Chromatic screenshots?
No

- Does this need a new example in the kitchen sink apps?
No

- Does this need an update to the documentation?
No

If your answer is yes to any of these, please make sure to include it in your PR.

2019-03-19 03:19 UTC, shilman commented
@leoyli getting some linting errors:

```
/tmp/storybook/addons/knobs/src/components/types/Object.js
  12:7  error  Unused state field: 'values'  react/no-unused-state
  14:7  error  Unused state field: 'state'   react/no-unused-state
```

2019-03-19 13:47 UTC, leoyli commented
@shilman, thanks for the heads up! For some reason I've made a typo here... I've made a correction. :)

2019-03-21 15:18 UTC, leoyli commented
@shilman, I still see 1 checks is neutral/pending... Is this a blocker?! If so what should I do?!

2019-03-22 03:59 UTC, shilman requested changes
Hi @leoyli This fixes the warning but looks like it causes a bug. When I run `official-storybook` on this branch I don't see the Styles options as I expect in the knobs UI. Here's what it should look like on `next`:

<img width="998" alt="Storybook" src="https://user-images.githubusercontent.com/488689/54799850-ee1b8900-4c99-11e9-9688-284cb500776b.png">

Mind digging in and see if you can figure out what's wrong?

2019-03-22 05:13 UTC, leoyli commented
@shilman, Oh yes, I'm happy to make contributions to make this thing great.  I will find a time during weekend to work on this. Thank you for your review and catching my bug!

2019-03-23 02:30 UTC, leoyli commented
@shilman, I can see the problem you've mentioned.  I have just committed a change to fix this, which is  simpler and safer I believe. :) I have test in my local machine and ensure the knob running as expected and no printing `ObjectType` errors.

2019-03-23 04:38 UTC, shilman approved these changes
LGTM and working great. Thanks for fixing this @leoyli !

2019-03-23 04:38 UTC, merged

2019-03-23 04:40 UTC, leoyli commented
Thank you for your review, I will try to find what else I can contribute!