Added missing option
storybookjs/storybook pull request #6195
Opened 2019-03-20 12:23 UTC by mortal94

isToolshown was missing from documentation so i've added it.
It allows to control if to show or hide the toolbar above the story.

2019-03-20 17:58 UTC, wuweiweiwu submitted a review, later dismissed

2019-03-20 20:02 UTC, shilman requested changes
Thanks for this! I didn't know about this option.

However, `addon-options` is deprecated as it says at the top of the file, so changes to the documentation should be added to `docs/src/pages/configurations/options-parameter/index.md` instead.

Also, would you mind updating `MIGRATION.md` with the new option as well?

2019-03-20 20:21 UTC, mortal94 commented
Sure!

2019-03-20 21:51 UTC, wuweiweiwu commented
Oh I didn't realize that options was being deprecated. Excuse my oversight

2019-03-21 04:12 UTC, shilman approved these changes

2019-03-21 04:13 UTC, shilman commented
Thanks for the fix @mortal94

2019-03-21 04:13 UTC, merged