REMOVE `sortStoriesByKind` from docs & implementation
storybookjs/storybook pull request #6858
Opened 2019-05-22 07:43 UTC by ndelangen

Issue: https://github.com/storybooks/storybook/issues/5827

remove the documentation around the sorting of stories until we've addressed the regression in 5.2

## What I did
Remove references from the docs

2019-05-23 00:46 UTC, tmeasday approved these changes
LGTM

2019-05-23 01:39 UTC, shilman requested changes
How about something in MIGRATION.md also?

2019-05-24 16:02 UTC, ndelangen commented
@shilman done

2019-05-25 05:51 UTC, shilman approved these changes

2019-05-25 05:52 UTC, merged