UPGRADES
storybookjs/storybook pull request #7329
Opened 2019-07-06 21:40 UTC by ndelangen

2019-07-07 08:42 UTC, shilman commented on lib/ui/src/index.js
> +  console.log('IS CALLED');
???

2019-07-07 08:46 UTC, shilman requested changes
Please reformat this PR:
- sensible title
- description
- coherent set of commits that match the description

2019-07-07 12:35 UTC, ndelangen commented
I'm running into memory issues, I've tried:
- upping the memory limit of node (FAIL)
- disabling parallel in TerserPlugin (gives hint that the problem is in source-maps)
- disabling source-maps (FIXES)

I'd like to NOT disable source-maps, I'm investigating if:
- disabling cache will help.

2019-07-07 14:04 UTC, shilman commented
@ndelangen also seeing memory issues on this one too: https://github.com/storybookjs/storybook/pull/7272

2019-07-07 20:31 UTC, ndelangen commented
@shilman do you want me to change the git history to improve the commit messages?

What is your opinion on my solution for the memory issue? I was able to take it away by disabling source-maps for the official example.

2019-07-08 13:15 UTC, ndelangen commented
We discovered that it's the storysource loader, in combination with terser that's creating a memory problem.

We're optimising the storysource loader to solve this problem.

2019-07-08 13:16 UTC, shilman requested changes
Comments inline

2019-07-08 13:16 UTC, shilman commented on examples/official-storybook/package.json
> +    "express-graphql": "^0.8.0",
whitespace

2019-07-08 13:16 UTC, shilman commented on examples/official-storybook/webpack.config.js
> +        parallel: false,
we want this true, right?

2019-07-08 13:18 UTC, ndelangen commented on examples/official-storybook/webpack.config.js
> +        parallel: false,
yes, in the end, this should be true.

2019-07-08 16:02 UTC, merged