Feature/jest redesign
storybookjs/storybook pull request #7424
Opened 2019-07-16 02:42 UTC by CodeByAlex

##  What I did

Redesigned and refactored the Jest addon to follow the pattern of the accessibility addon.
Parsing now works with new jest output format as well as the old format.

There is more data coming to this addon but this is just a redesign.
![jest-design-demo](https://user-images.githubusercontent.com/29763590/61170831-ca2bce00-a53c-11e9-887d-eb6abb64bdbd.gif)

## How to test

- Is this testable with Jest or Chromatic screenshots? yes
- Does this need a new example in the kitchen sink apps? no
- Does this need an update to the documentation?  no

If your answer is yes to any of these, please make sure to include it in your PR.

2019-07-17 17:27 UTC, domyen commented
👏 This looks amazing @CodeByAlex! 

Things I noticed from a visual design POV:
- Remove the extra horizontal borders (It looks like there are two between the subheader and first item)
- Reduce the dimensions of the status gauge to 30x6 (i.e., make it shorter)
- Do we need the % passed? I can see how this is useful in aggregate across a whole app, but it doesn't add much information at the component level. I'm likely only encountering a handful of tests at the component level.

2019-07-17 17:37 UTC, shilman requested changes
Awesome improvement -- this is so much better! 💯 

Left a couple code changes. The unit tests are for documentation more than anything in this case, I'm assuming they work.

2019-07-17 17:37 UTC, shilman commented on addons/jest/src/components/Result.tsx
> +  state = {
Can we use hooks for this instead of class components 🤢

2019-07-17 17:37 UTC, shilman commented on addons/jest/src/components/Message.tsx
> +const getConvertedText: (msg: string) => MsgElement[] = (msg: string) => {
Can you add a couple unit tests for this?

2019-07-17 17:37 UTC, shilman commented on addons/jest/src/components/Message.tsx
> +const getTestDetail: (msg: string) => TestDetail = (msg: string) => {
Can you add a couple unit tests for this?

2019-07-17 17:41 UTC, domyen requested changes

2019-07-17 17:41 UTC, domyen commented on addons/jest/src/components/Message.tsx
> +  background: '#f2f2f2',
Use the color palette `theme.color.lighter`

2019-07-17 17:41 UTC, domyen commented on addons/jest/src/components/Message.tsx
> +  borderBottom: '1px solid rgb(226, 226, 226)',
replace with `theme.appBorderColor`

2019-07-17 17:41 UTC, domyen commented on addons/jest/src/components/Panel.tsx
> +  color: '#666666',
`theme.color.dark`

2019-07-17 17:41 UTC, domyen commented on addons/jest/src/components/Panel.tsx
> +  backgroundColor: '#FF4400',
theme.color.negative

2019-07-17 17:41 UTC, domyen commented on addons/jest/src/components/Panel.tsx
> +  width: '50px',
Can we make this thinner? `30px`

2019-07-17 17:41 UTC, domyen commented on addons/jest/src/components/Panel.tsx
> +  height: '10px',
and shorter --> `6px`

2019-07-17 17:41 UTC, domyen commented on addons/jest/src/components/Panel.tsx
> +    backgroundColor: '#66BF3C',
theme.color.positive

2019-07-17 17:41 UTC, domyen commented on addons/jest/src/components/Panel.tsx
> +    boxShadow: '1px 0 0 white',
From a visual acuity standpoint adding 1px white border between the red and green doesn't add much. Can we remove this?

2019-07-17 17:41 UTC, domyen commented on addons/jest/src/components/Panel.tsx
> +                  <div id="failing-tests" title={`${failedNumber} Failed`} color="#FF4400">
This should use the theme colors rather than being hardcoded in.

2019-07-17 17:41 UTC, domyen commented on addons/jest/src/components/Panel.tsx
> +                  <div id="passing-tests" title={`${successNumber} Passed`} color="#66BF3C">
Theme colors 🙏

2019-07-17 17:41 UTC, domyen commented on addons/jest/src/components/Result.tsx
> +                color="#9DA5AB"
`theme.color.mediumdark`

2019-07-17 20:13 UTC, CodeByAlex commented
Thanks, @Dom. I'll get those colors turned over to tokens asap. And it does look cleaner with your suggestions so I'll commit those changes.

Cheers, @shilman. Ill turn the component into a hook so you don't 🤢 and add some unit tests

2019-07-19 11:58 UTC, ndelangen commented on addons/jest/src/components/Panel.tsx
> +      <NoTests>This story has no tests configured</NoTests>
It would be nice to add some documentation here, on how to get it set up so there ARE tests.

2019-07-19 11:59 UTC, ndelangen commented on addons/jest/src/components/Result.tsx
> +              style={{
I think this should be in a `rotate` prop.

2019-07-19 12:00 UTC, ndelangen approved these changes

2019-07-19 12:01 UTC, ndelangen commented
Code looks good as is, some improvements would be good, but I'd be ok merging as is, and improving it later.

2019-07-19 14:11 UTC, CodeByAlex commented
> Code looks good as is, some improvements would be good, but I'd be ok merging as is, and improving it later.

@ndelangen That would be great. I can definitely take these comments as next steps. I can add more tests, docs, and tweaks in the next PR if that works for everyone. Would like to get feedback as soon as possible from users.

2019-07-20 03:42 UTC, merged

2019-07-22 13:23 UTC, fabiradi commented
Unfortunately, the redesign handles **skipped tests** (pending) and **todos** (todo) differently: They currently **don't show up in the list**. Previously, they were counted as "failed", but shown in "green" (like "passed"). This was still not perfect, but – at least – they were displayed.

![jest-failed-tests](https://user-images.githubusercontent.com/5428213/61635700-691a9d80-ac94-11e9-938c-c63251304ab2.png)

```javascript
test.todo('This is a todo');
xit('This is a skipped test', () => {});
```

ℹ️ `jest test` lists skipped tests and todo separately in its summary.
<img width="382" alt="jest-summary" src="https://user-images.githubusercontent.com/5428213/61635478-f5789080-ac93-11e9-8d43-b4b3d3017fdc.png">

It would be nice to have all tests listed, either as passed or failed. Displaying skipped tests as todos differently is something for a feature report ...

2019-07-22 13:27 UTC, ndelangen commented
Should be easy to add a few extra tabs for those types of tests reports I think.

Would you be interested in contributing that feature @fabiradi ?

2019-07-22 22:02 UTC, fabiradi commented
> Should be easy to add a few extra tabs for those types of tests reports I think.
> 
> Would you be interested in contributing that feature @fabiradi ?

😃  I actually thought about it and already took a [peek into the source code](https://github.com/storybookjs/storybook/blob/next/addons/jest/src/components/Panel.tsx). The counts are "simple" filters on strings and should be easy to duplicate for a couple of more tabs – fixing the wrong "failed" count.

```javascript
const successNumber = result.assertionResults
    .filter(({ status }) => status === 'passed').length;
const failedNumber = result.assertionResults.length - successNumber;
```

I have three questions up front:

1. **Colors:** Where can I find suitable color definitions? The [Storybook brand colors](https://github.com/storybookjs/brand#colors) are not used for red (failed) and green (passed) tests. How would a get a yellow and violet? I could use "Gold" and "Purple" from the brand guide.
2. **Visiblity of Tabs:** Would the tabs for "skipped" and "todo" be displayed all the time or hidden when the count = 0? The failed tab seems to be visible even when no test failed. I'm not sure if that would be okay for skipped and todo ...
3. **Form of Contribution:** Where/how would I contribute? Is this a separate issue or an addition to this issue?

:wave: As this would be my first contribution, I still have to take a look into the [contribution guide](https://github.com/storybookjs/storybook/blob/next/CONTRIBUTING.md)...

2019-07-22 23:15 UTC, CodeByAlex commented
@fabiradi That sounds great! 

You can check out the brand colors here: https://storybook-design-system.netlify.com/?path=/docs/design-system-color--all
I think the tabs should be persistent in the same way that the a11y addon tabs are.
The form of contribution is up to you. Maybe create a feature request and then reference it in the PR.

Looking forward to seeing this addition 👍