Edit page addon
storybookjs/storybook pull request #7939
Opened 2019-08-31 00:20 UTC by atanasster

Issue: 
allow hooks for the UI around the iFrame
create addon that will use the hooks and will display edit this page links

## What I did
1. added two hook types to lib/addons/types.ts
```
  IFRAME_START = 'iframe_start',
  IFRAME_END = 'iframe_end',
```

2. Updated the lib/ui/preview component to display any add ons registered for those hooks
```
const iFrame = (
    <Fragment>
      {iframeStart.map(({ render }) => render())}
      {base}
      {iframeEnd.map(({ render }) => render())}
    </Fragment>
  );
```
3. Added addon edit-page

4. Update examples/official-storybook base_button.stories.js (the first story that shows up in the example)

5. Updated site, other documentation that I found mentioning addons

## How to test

Please review the functionality as well as the appearance of the default edit page panel - it uses the background color of toolbar

2019-09-03 17:36 UTC, atanasster commented
@domyen ,I am attaching screenshots of how the addon looks in Preview and Docs pages both in light and dark theme, if you can please review and let me know your input.

```
const StyledContainer = styled.div<{}>(({ theme }) => ({
  padding: '10px',
  background: theme.background.bar,
  borderBottom: `1px solid ${theme.color.border}`,
}));
```
![screenshot808](https://user-images.githubusercontent.com/6075606/64195544-bf602c00-ce4f-11e9-98a8-03667c10e230.jpg)

![screenshot809](https://user-images.githubusercontent.com/6075606/64195551-c38c4980-ce4f-11e9-8763-bbac5397c4e1.jpg)


![screenshot810](https://user-images.githubusercontent.com/6075606/64195562-c71fd080-ce4f-11e9-933a-aa212ece1b1b.jpg)


![screenshot811](https://user-images.githubusercontent.com/6075606/64195576-cb4bee00-ce4f-11e9-9347-4e20a0009381.jpg)

2019-09-11 16:37 UTC, domyen commented
Firstly, this is awesome Atanas! 😍👏

There are a few modalities here that are kind of nuanced.

**Canvas**
This is a component dev environment primarily so having the edit button in the iframe would be pretty distracting and subject to the users global styles. 

![image](https://user-images.githubusercontent.com/263385/64715916-5308ac80-d48f-11e9-8825-4837dd86a736.png)


**Docs**
This is where you can view docs in a new tab while developing your components. I think the above solution would work well too:

![image](https://user-images.githubusercontent.com/263385/64715927-5dc34180-d48f-11e9-8b9b-1ffaf817e93b.png)


**Docs build**
This is the static site intended for read-only use that SB docs generates. It has no toolbar. So the inline solution would be the best choice. I'd suggest placing it at the end similar to what Shopify Polaris does [here](https://polaris.shopify.com/components/images-and-icons/avatar#navigation). @shilman do you think this could be injected into a DocsPage slot somehow?

![image](https://user-images.githubusercontent.com/263385/64716639-b7783b80-d490-11e9-9114-a570862aa99a.png)

2019-09-11 22:07 UTC, shilman commented
@domyen looks great. i'm not sure the best way to fit that into DocsPage -- I'll have to chew on it. There's currently no "addons API" for DocsPage, you're getting into uncharted territory here. 😄

2019-09-12 03:04 UTC, atanasster commented
Thanks for the feedback @domyen.
@shilman - so should I remove completely the API to insert elements before/after the IFrame? And add an API to docs page to insert elements before/after the docs content?

2019-10-29 04:44 UTC, shilman commented
@atanasster I propose a slightly different approach, which is an `IFRAME_DECORATOR` slot, that takes a decorator function, which renders **AROUND** the iframe. That way the user can:
- insert something before or after or both
- insert something around (e.g. to change size, a la viewports addon)

2019-10-29 07:15 UTC, ndelangen requested changes

2019-10-29 07:15 UTC, ndelangen commented on lib/addons/src/types.ts
> +  IFRAME_START = 'iframe_start',
Sorry, I don't think this API is a good idea.

I want to be super careful with adding addon types, as we'll be stuck with supporting them forever.

I'd rather have a single IframeWrapper type addon, which I might have a usecase for when i want to extract the zoom functionality into an addon.

I think you can do everything in a wrapper you could do with a pre & post

2019-10-29 14:06 UTC, atanasster commented
@ndelangen @shilman - it turns out there was already a `types.PREVIEW` wrapper used by the a11y addon. 

I ended up just adding an example for the preview_wrapper in the dev-kits example.

2019-10-29 14:11 UTC, shilman approved these changes
LGTM! @ndelangen ?

2019-10-29 15:30 UTC, ndelangen approved these changes

2019-11-07 10:58 UTC, merged