ADD cli test in github actions
storybookjs/storybook pull request #8064
Opened 2019-09-12 14:31 UTC by ndelangen

Issue: -cli test run in travis, but always, even if unchanged-

## What I did
I changed the github actions workflow so that there's a workflow for the cli tests

2019-09-13 10:03 UTC, Hypnosphi requested changes
Actually, there's much sense in running those tests on changes in `core` and other packages. There are ways to make the output of cli broken without touching cli code. Basically, those tests can discover hidden breaking changes

2019-09-15 21:03 UTC, ndelangen commented on .github/workflows/tests-cli.yml
> +    - 'lib/cli/*'
I tried, don't think they are unfortunately

2019-09-15 21:05 UTC, ndelangen commented on .github/workflows/tests-cli.yml
> +        node-version: [10]
Node is is EOL jan 2020

I could change it to 8 if you'd like

2019-09-15 21:05 UTC, ndelangen commented on lib/cli/README.md
> +<!-- dummy change to test cli action -->
yes

2019-09-16 12:27 UTC, Hypnosphi commented on .github/workflows/tests-cli.yml
> +        node-version: [10]
We can only change node support in major releases

2019-10-04 08:42 UTC, ndelangen commented
@Hypnosphi I read you loud and clear. I've changed the config so it only runs on if there's a change in /lib or /app

I don't think a change in /addons would ever require a run of the cli tests.. Do you agree?

@shilman fixed

2019-10-04 09:15 UTC, Hypnosphi commented
> I don't think a change in /addons would ever require a run of the cli tests.. Do you agree?

Sure. We don't have any pre-installed addons, right?

2019-10-04 09:15 UTC, Hypnosphi approved these changes

2019-10-04 11:04 UTC, ndelangen commented
> Sure. We don't have any pre-installed addons, right?

addon links & actions are installed by default when you use `sb init`

2019-10-04 11:05 UTC, ndelangen commented
I had to disable the paths filtering for now because:
https://github.community/t5/GitHub-Actions/Preserve-status-from-previous-action-run/m-p/33821#M1661

2019-10-04 11:06 UTC, ndelangen commented
I've removed the cache from travis, it spends ages storing those, I wonder whether it's a net loss.

2019-10-04 11:07 UTC, ndelangen commented
Depending on which is faster GitHub actions or Travis, I'll keep either one for these tests.

If GitHub actions is faster, I might repurpose travis to do some other CI stuff.

2019-10-04 13:00 UTC, ndelangen commented
<img width="1539" alt="Screenshot 2019-10-04 at 14 58 41" src="https://user-images.githubusercontent.com/3070389/66209364-78b45a80-e6b7-11e9-9d67-411278ca7a11.png">

VS

<img width="698" alt="Screenshot 2019-10-04 at 14 59 00" src="https://user-images.githubusercontent.com/3070389/66209475-b44f2480-e6b7-11e9-9bb9-c3e7bed9f216.png">

2019-10-04 13:02 UTC, ndelangen commented
GitHub as a few minutes faster, sadly the tests will have to run on all commits, merging this, and disabling Travis for now. I'll repurpose it for something at some point

2019-10-04 13:35 UTC, merged