Addon-docs: Add jest-transform.js to convert .mdx => .js for storyshots
storybookjs/storybook pull request #8189
Opened 2019-09-25 09:04 UTC by ndelangen

This replaces https://github.com/storybookjs/storybook/pull/7330 since that PR no longer has a repository and cannot be contributed on anymore :(

2019-09-26 16:33 UTC, edelgado commented
Can't wait for this either, thanks! Maybe remove the dependency on `deasync-promise` as explained in https://github.com/storybookjs/storybook/pull/7330#issuecomment-532885357 ? Thanks!

2019-09-26 23:30 UTC, ndelangen commented
Would you like to contribute to this PR @edelgado?

2019-09-27 14:18 UTC, edelgado commented
@ndelangen sure thing! Thanks for the access, will submit a commit soon.

2019-09-27 23:06 UTC, shilman requested changes
NICE!! looking very clean. would it be possible to update the documentation as well?

2019-09-29 19:22 UTC, edelgado commented
@shilman Absolutely! Added to both add-ons to make it easier on the users.

2019-10-01 14:05 UTC, shilman requested changes
Thanks @edelgado, this looks great. Last request: can we add this to our monorepo somehow to test it?

2019-10-04 22:33 UTC, edelgado commented
> Thanks @edelgado, this looks great. Last request: can we add this to our monorepo somehow to test it?

Hi @shilman, not sure what you mean by this.  First time contributing so I'm not familiar with that task. Could you point me in the right direction please?

2019-10-07 13:54 UTC, ndelangen commented
@shilman what do you require?

2019-10-07 22:17 UTC, Hypnosphi commented on addons/docs/README.md
> +   "^.+\\.mdx?$": "@storybook/addon-docs/jest-transform-mdx"
Does it mean that we load `.md` extension as well?

2019-10-08 01:21 UTC, shilman commented
@Hypnosphi I tried adding MDX snapshotting to the HTML example and am getting this error:

```
$ yarn jest --testPathPattern htmlshots.test.js
yarn run v1.19.0
$ /Users/shilman/projects/storybookjs/storybook/node_modules/.bin/jest --testPathPattern htmlshots.test.js
 FAIL  examples/html-kitchen-sink/tests/htmlshots.test.js
  ● Test suite failed to run

    SyntaxError: unknown: Expected corresponding JSX closing tag for <MDXLayout> (30:40)

      28 | <p>{\`Hallelujah! HTML is working out of the box without modification.
      29 | `}</code></pre>
    > 30 | <p>{`How you like them apples?!\`}`}</p></p>
         |                                         ^
      31 | <pre><code parentName="pre" {...{}}>{`<Story name="heading" height="100px" mdxType="Story">
      32 | `}</code></pre>
      33 | <p>{`  {'`}<h1>{`Hello World`}</h1>{`'}`}</p>
```

Flying blind here...

2019-10-09 11:40 UTC, Hypnosphi commented
@shilman looks like you're adding the transform twice, as it's already present in `config.transform`.

In my case, the html snapshotting went [OK](https://github.com/storybookjs/storybook/pull/8189/files#diff-0e77f87cfc13fb718f853594cd0233e5), but storyshots-integrity complained, probably because its algorythm doesn't know anything about mdx extension yet

2019-10-10 08:43 UTC, shilman commented
@Hypnosphi I fixed the integrity error in my latest commit. However, I'm not sure what's going on with Vue/Angular.

2019-10-10 10:22 UTC, Hypnosphi commented
@shilman not really

2019-10-24 12:44 UTC, shilman commented
@ndelangen and I were able to get angular working. Vue is not working due to a babel issue, and I've temporarily disabled it to move this forward. I'll follow up with @Aaron-Pool to see if we can get that working. Pretty sure it's more of a Vue/Babel issue than a Jest/MDX one.

2019-10-24 13:42 UTC, merged

2020-08-07 07:32 UTC, albert-schilling commented on addons/docs/README.md
> +   "^.+\\.[tj]sx?$": "babel-jest",
Isn't there a pipe symbol missing: [t|j] ? As here: https://github.com/facebook/jest/tree/master/packages/babel-jest#setup

2020-08-07 07:33 UTC, albert-schilling commented on addons/storyshots/storyshots-core/README.md
> +    "^.+\\.[tj]sx?$": "babel-jest",
Isn't the pipe symbol necessary? [t|j]