Migrate @storybook/mithril to TypeScript
storybookjs/storybook pull request #8320
Opened 2019-10-07 19:04 UTC by hcz

Issue: #5030

## What I did
Migrate @storybook/mithril to Typescript

## How to test

Everything should function the same, except the package should now have type definitions.

2019-10-09 07:32 UTC, hcz commented
@shilman What should I do more? Some checks were failed

2019-10-09 08:11 UTC, shilman commented
@hcz Looks good -- I just added an extra label! I think one of our typescript posse should review & then we can merge.

2019-10-17 14:32 UTC, ndelangen requested changes

2019-10-17 17:18 UTC, hcz commented on app/mithril/package.json
> +    "@types/mithril": "^2.0.0",
> should be a regular dependency IMHO

Ok, fixed c925c87

2019-10-17 17:33 UTC, ndelangen approved these changes

2019-10-17 17:33 UTC, ndelangen commented
good to merge!

2019-10-17 17:34 UTC, ndelangen commented
I invited you to the org @hcz !

2019-10-18 00:58 UTC, shilman approved these changes
Great job @hcz !!! 🚀

2019-10-18 00:59 UTC, merged

2019-11-22 18:42 UTC, davidroman0O commented
I know it's merged but anyone have an example of Mithril + TypeScript ?

Or this merge is not yet release? maybe?

I tried to setup one (multiple times) and I still have a lot of errors with `esModuleInterop` flag and others from simple TypeScript helloworld like components.

2019-11-25 09:51 UTC, ndelangen commented
@davidroman0O This feature will be released in 5.3 (see milestone)
You can try this today by upgrading to the beta.

We'd love to hear your feedback. A more detailed report of what you tried, and what errors you got would help./

2019-11-25 14:15 UTC, davidroman0O commented
@ndelangen  Oh yeah ! 😄 

Thx!