Addon-docs: Fix React.forwardedRef/memo props
storybookjs/storybook pull request #8445
Opened 2019-10-16 15:04 UTC by darmawanalbert

Issue: #7933 

## What I did
Fix Props block rendering issue when using `React.forwardRef` by checking whether the target should be calling `render()` first to get the list of `propTypes` or not.

## How to test

- Is this testable with Jest or Chromatic screenshots? No
- Does this need a new example in the kitchen sink apps? No
- Does this need an update to the documentation? No

2019-10-16 15:18 UTC, shilman approved these changes
Thank you @darmawanalbert -- this is really awesome!! 

This code makes sense, but since it's React-specific, would it be possible to put it inside the `getPropDefs` function returned from `inferPropDefs`?

Also, if it's a similar fix, would you mind also adding `React.memo` support and test case while you're at it?

2019-10-16 15:18 UTC, shilman requested changes
Meant to request changes in my prev review :)

2019-10-18 09:34 UTC, darmawanalbert commented
@shilman sure, let me try it on `React.memo()`

2019-10-18 10:39 UTC, darmawanalbert commented
@shilman I have added another logic to fix #6298 and move it to `getPropDefs` function 🙇

2019-10-19 02:07 UTC, shilman approved these changes
This is freakin' awesome @darmawanalbert! Thanks so much for the fix!!!

2019-10-19 02:10 UTC, merged