Fix 'path is required in .pageview()' in GA addon
storybookjs/storybook pull request #8468
Opened 2019-10-18 02:23 UTC by soundasleep

See https://github.com/storybookjs/storybook/issues/6012

This uses the fix in https://github.com/thundermiracle/storybook-loader/pull/19/files. Not tested - I don't have Typescript running locally.

2019-10-18 14:59 UTC, ndelangen approved these changes

2019-10-19 01:57 UTC, shilman requested changes
Any chance you can test this? I have very little confidence that renamimg a variable would fix the problem, since it's not passed as a named argument.

2019-10-19 01:58 UTC, shilman requested changes
Any chance you can test this? I have very little confidence that renamimg a variable would fix the problem, since it's not passed as a named argument.

2019-10-22 22:30 UTC, ndelangen commented
@shilman WDYM?
It's invoking this API:
https://github.com/storybooks/storybook/blob/edb1896038f68db7d3f1e44faed021428d499fca/lib/api/src/modules/url.ts#L96-L103

that returns both a url and a path ?

2019-10-23 01:07 UTC, shilman commented
@ndelangen so you think it's erroring because it's being passed a URL instead of a path. Can you test it? I'm not keen to merge a change that hasn't been tested.

2019-11-12 07:13 UTC, vesahyp commented
Facing the same issue. As a temporary workaround i've added the same STORY_CHANGED event listener to another internal addon:
`    api.on(STORY_CHANGED, () => {
        const { path } = api.getUrlState();
        ReactGA.pageview(path);
      });
`

Switching `url` to `path` works.

2019-11-12 08:59 UTC, shilman commented
Thanks @vesahyp! Merging!

2019-11-12 08:59 UTC, merged