fix 8294: check context in source-loader
storybookjs/storybook pull request #8773
Opened 2019-11-09 13:52 UTC by donaldpipowitch

Issue: https://github.com/storybookjs/storybook/issues/8294

## What I did

I added a warning for people like me who misconfigured the `@storybook/source-loader`. If I understand correctly, it should only be used for files containing stories. In my webpack config it was applied to all source code files.

## How to test

Checkout my PR, `cd lib/source-loader && yarn prepare && yarn link`. After that `$ git clone git@github.com:donaldpipowitch/storybook-bug-demo-source-loader-context-null.git && cd storybook-bug-demo-source-loader-context-null && yarn && yarn link "@storybook/source-loader" && yarn storybook`. You should see the warning.

2019-11-09 14:13 UTC, shilman requested changes
Thanks @donaldpipowitch, this is great! Mind updating this to use `@storybook/node-logger` instead?

2019-11-10 18:52 UTC, donaldpipowitch commented
@shilman sure :) Thank you for the fast review.

2019-11-10 19:10 UTC, donaldpipowitch commented
> Mind updating this to use `@storybook/node-logger` instead?

@shilman did you meant `@storybook/client-logger` by any chance? Because I changed `lib/source-loader/src/client/preview.js` (inside `client`).

2019-11-10 23:42 UTC, shilman approved these changes

2019-11-10 23:45 UTC, shilman requested changes
@donaldpipowitch You're right, it's client-logger

2019-11-11 06:27 UTC, donaldpipowitch commented
@shilman Fixed 👍

2019-11-11 09:55 UTC, merged