test(react-native): add detox test accessibility
storybookjs/storybook pull request #9057
Opened 2019-12-04 16:57 UTC by wilau2

React-Native

Add test accessibility on navigation bar items.

Tools like detox are a lot more performant searching by.id than by.text to tap on those elements.

2019-12-04 19:26 UTC, marksinkovics approved these changes

2019-12-05 00:59 UTC, shilman commented
@wilau2 @marksinkovics we're getting TS build errors of the following form, mind adding a fix?

```
src/preview/components/OnDeviceUI/navigation/bar.tsx(28,11): error TS2769: No overload matches this call.
  Overload 1 of 2, '(props: Readonly<Props>): Button', gave the following error.
    Type '{ children: string; onPress: (id: number) => void; id: number; testID: string; active: boolean; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Button> & Readonly<Props> & Readonly<{ children?: ReactNode; }>'.
      Property 'testID' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Button> & Readonly<Props> & Readonly<{ children?: ReactNode; }>'.
  Overload 2 of 2, '(props: Props, context?: any): Button', gave the following error.
```

2019-12-05 08:13 UTC, Gongreg commented
Hey, @wilau2, thank you for the PR.

Just a suggestion, but you can create a websocket server and switch the stories with websockets instead of manually clicking on the stories. You can take a look in https://github.com/wix-incubator/rnsst (this one is using websockets to switch stories and take screenshots, but you could create logic necessary for you similiar to it).

2019-12-05 08:15 UTC, Gongreg requested changes
You need to add testID prop in here: https://github.com/storybookjs/storybook/blob/next/app/react-native/src/preview/components/OnDeviceUI/navigation/button.tsx . Otherwise the testID will not work.

2020-01-29 17:17 UTC, ndelangen commented
We need to move this to the react-native repo

2020-02-08 15:03 UTC, shilman commented
The packages `@storybook/react-native` and `@storybook/react-native-server` have been moved to the repository https://github.com/storybookjs/react-native

The move is the first part of an effort to revitalize Storybook for RN. Its purpose is to make it easier for Storybook for RN to be versioned independently of the rest of Storybook—both Storybook and RN have been moving quickly, and Storybook for RN has been getting crushed in between AND subject to the versioning constraints of the rest of Storybook.

I’m closing this PR for now, since those packages no longer exist in this repo. Please retarget your changes to https://github.com/storybookjs/react-native. Thank you for your contribution & patience!

2020-02-08 15:03 UTC, closed without merging