Eslint strict
storybookjs/storybook pull request #911
Opened 2017-04-17 14:44 UTC by ndelangen

Issue: -should create one-

## What I did
As described in review comments #904 linting is rather non-strict right now.
Though I'm personally of the opinion too strict linting can be harmful, I agree, we could make it a bit more strict to weed out some bad code we have and prevent bad come from getting pushed to master.

## How to test
run `npm run lint`

2017-04-28 13:33 UTC, subpopular commented on packages/addon-info/src/components/PropVal.js
> +  return <span>{`{ ${content} }`}</span>;
nice!

2017-04-28 18:48 UTC, theinterned commented
question: I've got this error:

```console
/Users/user/src/theinterned-storybook/packages/storybook-ui/src/modules/ui/components/left_panel/text_filter.test.js
  1:1  error  'enzyme' should be listed in the project's dependencies. Run 'npm i -S enzyme' to add it  import/no-extraneous-dependencies
```
this is due to enzyme being in the root `package.json` is it appropriate just add an `eslint-disable-line` or should we modify the eslint-config?

2017-05-02 14:51 UTC, theinterned commented
@UsulPro has fixed some issues in the **addon-info** package in this PR: https://github.com/storybooks/storybook/pull/980

2017-05-08 02:42 UTC, theinterned commented
I thought I'd give an update on my work. 

I'm down to `✖ 72 problems (64 errors, 8 warnings)`

For the time being I'm skipping jsx-a11y issues as I didn't feel comfortable fixing a number of the UI-related issues without running the "kitchen-sink" project and generally making more nuanced decisions. I plan to tackle that in a separate PR.

My PR is here https://github.com/storybooks/storybook/pull/1000

@ndelangen does it make sense to close that one in favour of this?

2017-05-09 05:54 UTC, ndelangen commented
closed in favour of https://github.com/storybooks/storybook/pull/1000

2017-06-01 05:52 UTC, ndelangen commented
Re-opening, will be closing #1000

2017-06-04 13:43 UTC, shilman approved these changes
@ndelangen this is looking much better. there is still some weirdness with the `prettier` config, but I couldn't figure out how to get rid of it:

```
/Users/shilman/projects/storybook/new/storybook/lib/ui/src/modules/ui/components/shortcuts_help.js
   69:53  warning  Delete `·(`  prettier/prettier
   75:3   warning  Delete `)`   prettier/prettier
   ...
```

Also when I run `npm run lint:js -- --fix` it removes a bunch of these parens and makes the code harder to read.

Finally, there are some warnings when I run the test suite.

Nevertheless, I think this is good to merge. What do you think?

2017-06-06 08:53 UTC, shilman requested changes
Hey this looks great but I think we should get it merged and then do refinements on the merged version. I think this PR is getting out of control?

2017-06-06 08:53 UTC, shilman commented on .remarkrc
> +        "configFile": "/Users/dev/Projects/GitHub/storybook/react-storybook/.eslintrc-markdown.js"
@ndelangen ???

2017-06-06 08:53 UTC, shilman commented on docs/pages/addons/api/index.md
> +addonAPI.register('my-organisation/my-addon', (storybookAPI) => {
@ndelangen can we put this in a different PR? i think it is unrelated to eslint?

2017-06-06 09:49 UTC, ndelangen commented on .remarkrc
> +        "configFile": "/Users/dev/Projects/GitHub/storybook/react-storybook/.eslintrc-markdown.js"
Will fix this

2017-06-06 10:42 UTC, shilman requested changes
@ndelangen I am seeing an error trying to run gatsby in the docs

```
npm run dev
```

Huge string of errors:
```
ERROR in ./~/css-loader!./~/postcss-loader/lib!./components/Docs/Content/style.css
Module build failed: Error: No PostCSS Config found in: /Users/shilman/projects/storybook/new/storybook/docs/components/Docs/Content
    at Error (native)
    at /Users/shilman/projects/storybook/new/storybook/docs/node_modules/postcss-load-config/index.js:51:26

 @ ./components/Docs/Content/style.css 4:14-130 18:2-22:4 19:20-136
...
```

2017-06-06 18:57 UTC, ndelangen commented
It's fixed @shilman !

2017-06-06 18:58 UTC, ndelangen commented
I'm ready to merge this, who can test locally and approve?

2017-06-06 20:20 UTC, merged