Fix Doc Links
storybookjs/storybook pull request #927
Opened 2017-04-21 18:13 UTC by danny-andrews

## What I did

Fixed doc links

## How to test

Click the links

2017-04-23 18:57 UTC, ndelangen requested changes

2017-04-23 18:57 UTC, ndelangen commented on packages/react-storybook/README.md
> +* [Basics](https://getstorybook.io/docs/react-storybook/basics/introduction)
Can you change these links to point to the new website instead? https://storybooks.js.org ?

2017-04-23 18:58 UTC, ndelangen commented
Thanks for this PR! @danny-andrews, if you can change the links to point to the new website, I can merge this!

2017-04-24 15:31 UTC, danny-andrews commented
@ndelangen Done! I can squash if needed.

2017-04-24 18:03 UTC, ndelangen approved these changes

2017-04-24 18:10 UTC, merged

2017-04-24 18:11 UTC, ndelangen commented
Thank you @danny-andrews, I hope to see more PR's by you in the future! 🙇