CSF: Use `__namedExportsOrder` array in loader if provided
storybookjs/storybook pull request #9315
Opened 2020-01-03 16:21 UTC by daKmoR

closes #9136
follow up of https://github.com/storybookjs/storybook/pull/9181

## What I did

As discussed in https://github.com/storybookjs/storybook/pull/9181 there have been 2 solutions to guarantee a story order if loaded via es modules. I went for the object. However, I have been missing the use case of rexports

```js
const myStory = () => html`Foo`;
export { myStory as notMyStory };
```

which currently produces the following `export const __orderedExports = { notMyStory };` which fails as `notMyStory` is not a local variable.

Therefore we should go with the previously discussed array of strings.

This Pull Request changes how loaders can guarantee the order of stories

Before:
```js
export const __orderedExports = { notMyStory };
```

After:
```js
export const __namedExportsOrder = ['notMyStory'];
```

## How to test

- use storybook without webpack and provide this export

## Notes

Related PR where we found the issue
https://github.com/open-wc/open-wc/pull/1171

2020-01-03 16:25 UTC, LarsDenBakker requested changes

2020-01-03 16:25 UTC, LarsDenBakker commented on lib/core/src/client/preview/start.js
>        // prefer a user/loader provided `__orderedExports` object if supplied as es module exports
```suggestion
      // prefer a user/loader provided `__namedExportsOrder ` object if supplied as es module exports
```

2020-01-03 16:30 UTC, daKmoR commented on lib/core/src/client/preview/start.js
>        // prefer a user/loader provided `__orderedExports` object if supplied as es module exports
good catch - rephrased 👍

2020-01-04 05:09 UTC, shilman approved these changes
LGTM

2020-01-04 05:19 UTC, merged