Correct the file path for the Button story
storybookjs/storybook pull request #9325
Opened 2020-01-04 19:42 UTC by DaleSeo

Issue: I happened to notice that the file path for the Button story was incorrect when looking at [Storybook for React tutorial](https://www.learnstorybook.com/intro-to-storybook/react/en/get-started/).

## What I did

Corrected the file path for the Button story.

## How to test

- Is this testable with Jest or Chromatic screenshots?
- Does this need a new example in the kitchen sink apps?
- Does this need an update to the documentation?

If your answer is yes to any of these, please make sure to include it in your PR.

2020-01-05 05:11 UTC, shilman approved these changes
~~Thanks @DaleSeo, good catch! However, the Button stories are actually located at `1-Button.stories.js`! Mind updating?~~

~~Also, this seems to be a problem across the `Welcome` component in ALL frameworks. Any chance you might be able to update the others? I'd really appreciate it!~~

2020-01-05 05:11 UTC, shilman requested changes
Thanks @DaleSeo, good catch! However, the Button stories are actually located at `1-Button.stories.js`! Mind updating?

Also, this seems to be a problem across the `Welcome` component in ALL frameworks. Any chance you might be able to update the others? I'd really appreciate it!

2020-01-05 22:34 UTC, DaleSeo commented
Oops! Sorry @shamin, you're right. I've updated it!

In terms of updating the others, since I'm not very familiar with this project, I just manually searched for some places and tried to update as much as I could.

I also look for the vue example and found it has the correct path.

https://github.com/storybookjs/storybook/blob/4e099490a2006b5aa7603b895a557d1a4dee6fae/examples/vue-kitchen-sink/src/stories/Welcome.vue#L31

2020-01-05 22:36 UTC, DaleSeo commented
I think my changes break some snapshot testing. I guess I need to learn `just -u` to update the snapshots?

2020-01-06 02:24 UTC, shilman commented
Thanks! Yeah, you should be able to do `yarn test --core --update`

2020-01-07 01:37 UTC, DaleSeo commented
@shilman I've updated the snapshots but I think chromatic tests are failing now. Could you advise?

2020-01-07 01:43 UTC, shilman commented
Thanks @DaleSeo!! I'll take care of Chromatic & merge. Much appreciated 🙏🙏🙏

2020-01-07 17:13 UTC, ndelangen approved these changes

2020-02-04 09:02 UTC, ndelangen approved these changes

2020-02-04 09:02 UTC, merged