#959 add a max-height and center element with alignItems: center
storybookjs/storybook pull request #961
Opened 2017-04-26 18:41 UTC by wcastand

Issue:

## What I did

I added some style to the tabtitles to center his children.

## How to test

In the example, add a react component as a Title with an `button` for example and some padding or margin.

2017-04-27 02:41 UTC, UsulPro commented on packages/storybook-ui/src/modules/ui/components/down_panel/style.js
> +    maxHeight: 60,
When this at the right side and there are a lot of tabs - they go in several rows. So maxHeight will break it. Better to put it to the tab style individually.

2017-04-27 02:44 UTC, UsulPro commented
@wcastand thanks for PR.

Consider applying maxHeight and overflow to the `tablink` style

2017-04-27 08:25 UTC, wcastand commented
I put max-Height in the tablink style.
I didn't know how to test it on the right panel in the example of storybook-ui, so let me know if i miss something again.

Thanks for the help on this :)

2017-04-27 17:36 UTC, UsulPro commented on packages/storybook-ui/src/modules/ui/components/down_panel/style.js
> +    overflow: 'hidden',
just remove it from here:
```
maxHeight: 60,
overflow: 'hidden',
```

2017-04-27 17:38 UTC, usulpro requested changes
remove
```
maxHeight: 60,
overflow: 'hidden',
```
from `tabbar`

2017-04-28 09:34 UTC, wcastand commented
I think we're good now :)

2017-04-28 10:42 UTC, ndelangen approved these changes
Looks good to me, tested locally

2017-04-28 11:30 UTC, merged