Test storyshots
storybookjs/storybook pull request #971
Opened 2017-04-28 10:43 UTC by tmeasday

Issue:

We didn't have a good way to test storyshots.

## What I did

Added storyshots to CRA app.

## How to test

```
npm install
cd examples/cra-storybook
npm test
```

2017-04-28 10:44 UTC, tmeasday commented
Note from commit:

> Storyshots wants to plugin to the version used by the app, not have its own version. So its a clear peer dep.

> Not sure it should depend on *storybook* at all given it is optional whether the user uses it or `react-native-storybook`

2017-04-28 11:51 UTC, ndelangen commented
I pushed some fixed and updated your branch, hope you don't mind 👼

2017-04-28 13:26 UTC, ndelangen commented on examples/cra-storybook/package.json
> +    "storyshots": "*"
Lerna will do it's thing on that!

2017-04-28 13:36 UTC, ndelangen commented
Can this be used to help along https://github.com/storybooks/storybook/pull/896 ?

2017-05-01 03:11 UTC, tmeasday commented
> Can this be used to help along #896 ?

I think #896 would be served by the alternate approach mentioned in https://github.com/storybooks/storybook/issues/917

2017-05-01 03:44 UTC, tmeasday commented
Hmmm. This test is failing because I changed the dependency in storyshots to a peer dep, and the example project isn't using an addon.

I can see two solutions to the problem:

1. Return `@kadira/storybook-addons` to be a proper dep of storyshots (this still feels wrong as it is a plugin, and making it a direct dep is asking for versioning problems).

2. Follow this technique (https://github.com/storybooks/storybook/blob/9471a71933af45aa24c0db8d189c410809645b94/packages/storyshots/src/index.js#L15-L20) to check if the user has installed the addon package (i.e. is using any addons), and only mock if so.

I'm not sure of the best way to do 2. If you make the package a peer dep, and the user isn't using it, they will get a warning from npm, but things will work fine. This seems suboptimal though. The alternative is to just not specify anything in `package.json`.

Any advice @ndelangen?

2017-05-09 05:43 UTC, ndelangen commented
I think not having it as a listed dependency is OK in this case as long as we guard when requiring it.

2017-05-09 15:47 UTC, ndelangen commented
@tmeasday Do you think you can finish this now? Any more feedback needed? Let me know!

2017-05-10 06:26 UTC, tmeasday commented
I'll get something going with that technique now.

2017-05-11 04:27 UTC, tmeasday commented
> This test is failing because I changed the dependency in storyshots to a peer dep, and the example project isn't using an addon (so as a result addons never gets installed)

Actually this was wrong. Storybooks depends on addons by default. The issue is that due to nested `node_modules` structures in this development context, `storyshots` can't require the correct addons.

2017-05-15 02:54 UTC, tmeasday commented
OK I think I finally resolved this by using the `test-cra` app. I suspect we should get rid of the confusing `cra-storybook` example @ndelangen.

2017-05-15 06:18 UTC, shilman commented
Problems running `npm run bootstrap`:
```
lerna ERR! execute npm WARN enoent ENOENT: no such file or directory, open '/Users/shilman/projects/storybook/storybook/packages/addon-links/package.json'
lerna ERR! execute npm WARN react-storybook No repository field.
lerna ERR! execute npm WARN react-storybook No license field.
lerna ERR! execute /Users/shilman/projects/storybook/storybook/packages/react-storybook
```

2017-05-15 06:33 UTC, shilman approved these changes
~~Looks great!~~
~~Minor point: I prefer `renderOnly` to `justRender`, but it's all good.~~

OOPS WRONG PR.

2017-05-15 06:33 UTC, shilman commented on packages/storyshots/src/index.js
> +const hasDependency = function(name) {
😻

2017-05-15 06:36 UTC, tmeasday commented
> Minor point: I prefer renderOnly to justRender, but it's all good.

Isn't that the other PR? I think I prefer that too..

2017-05-15 06:52 UTC, tmeasday commented
LMK if you want me to rebase this onto https://github.com/storybooks/storybook/pull/1031

2017-05-15 12:38 UTC, tmeasday commented
@ndelangen Please!

2017-05-15 13:23 UTC, ndelangen commented
pushed

2017-05-21 10:05 UTC, tmeasday commented
Ok, I think I finally fixed this. The tests should pass 😬

2017-05-21 10:06 UTC, tmeasday commented
See commit for more detail: https://github.com/storybooks/storybook/pull/971/commits/1c8f8e0ade576f1f5d5d19e4eb8ba680749a59e7

2017-05-21 10:10 UTC, shilman requested changes
Does the `options.mode` flag need to be added to docs?

2017-05-21 10:10 UTC, shilman commented on addons/storyshots/src/index.js
> +  const isRNStorybook = options.mode === 'react' || hasDependency('@storybook/react-native');
should be `react-native`?

2017-05-21 10:41 UTC, shilman approved these changes

2017-05-21 10:53 UTC, merged